const fall: Kigo[] = [
  {
    name: '藍の花',
    yomigana: 'あいのはな',
    kyukana: 'あゐのはな',
    season: 'fall',
    bodai: [],
    id: 1438,
  },
  {
    name: '青蜜柑',
    yomigana: 'あおみかん',
    kyukana: 'あをみかん',
    season: 'fall',
    bodai: [],
    id: 1439,
  },
  {
    name: '赤い羽根',
    yomigana: 'あかいはね',
    kyukana: '',
    bodai: ['愛の羽根'],
    season: 'fall',
    id: 1440,
  },
  {
    name: '赤蜻蛉',
    yomigana: 'あかとんぼ',
    kyukana: '',
    bodai: ['あきつ', '秋茜'],
    season: 'fall',
    id: 1441,
  },
  {
    name: '秋',
    yomigana: 'あき',
    kyukana: '',
    bodai: ['素秋', '金秋', '三秋', '九秋'],
    season: 'fall',
    id: 1442,
  },
  {
    name: '秋袷',
    yomigana: 'あきあわせ',
    kyukana: '',
    bodai: ['秋の袷'],
    season: 'fall',
    id: 1443,
  },
  {
    name: '秋麗',
    yomigana: 'あきうらら',
    kyukana: '',
    bodai: ['秋麗'],
    season: 'fall',
    id: 1444,
  },
  {
    name: '秋扇',
    yomigana: 'あきおうぎ',
    kyukana: 'あきあふぎ',
    bodai: ['秋扇', '秋の団扇', '扇置く', '捨扇', '捨団扇'],
    season: 'fall',
    id: 1445,
  },
  {
    name: '秋収め',
    yomigana: 'あきおさめ',
    kyukana: '',
    bodai: ['田仕舞'],
    season: 'fall',
    id: 1446,
  },
  {
    name: '秋惜しむ',
    yomigana: 'あきおしむ',
    kyukana: '',
    bodai: ['惜しむ秋'],
    season: 'fall',
    id: 1447,
  },
  {
    name: '秋風',
    yomigana: 'あきかぜ',
    kyukana: '',
    bodai: ['秋風', '秋の風', '金風', '爽籟', '色なき風', '律の風'],
    season: 'fall',
    id: 1448,
  },
  {
    name: '秋草',
    yomigana: 'あきくさ',
    kyukana: '',
    bodai: ['秋の草', '色草', '千草', '八千草'],
    season: 'fall',
    id: 1449,
  },
  {
    name: '秋蚕',
    yomigana: 'あきご',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1450,
  },
  {
    name: '秋鯖',
    yomigana: 'あきさば',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1451,
  },
  {
    name: '秋寒し',
    yomigana: 'あきさむし',
    kyukana: '',
    bodai: ['秋寒'],
    season: 'fall',
    id: 1452,
  },
  {
    name: '秋時雨',
    yomigana: 'あきしぐれ',
    kyukana: '',
    bodai: ['秋の時雨'],
    season: 'fall',
    id: 1453,
  },
  {
    name: '秋簾',
    yomigana: 'あきすだれ',
    kyukana: '',
    bodai: ['簾納む', '簾名残'],
    season: 'fall',
    id: 1454,
  },
  {
    name: '秋澄む',
    yomigana: 'あきすむ',
    kyukana: '',
    bodai: ['秋気澄む', '澄む秋', '空澄む'],
    season: 'fall',
    id: 1455,
  },
  {
    name: '秋高し',
    yomigana: 'あきたかし',
    kyukana: '',
    bodai: ['秋高（しゅうこう）', '天高し', '空高し'],
    season: 'fall',
    id: 1456,
  },
  {
    name: '秋出水',
    yomigana: 'あきでみず',
    kyukana: 'あきでみづ',
    bodai: ['秋の出水', '秋洪水'],
    season: 'fall',
    id: 1457,
  },
  {
    name: '秋茄子',
    yomigana: 'あきなす',
    kyukana: '',
    bodai: ['秋茄子', '秋の茄子', '名残茄子'],
    season: 'fall',
    id: 1458,
  },
  {
    name: '秋の朝',
    yomigana: 'あきのあさ',
    kyukana: '',
    bodai: ['秋暁'],
    season: 'fall',
    id: 1459,
  },
  {
    name: '秋の雨',
    yomigana: 'あきのあめ',
    kyukana: '',
    bodai: ['秋雨', '秋霖', '秋黴雨'],
    season: 'fall',
    id: 1460,
  },
  {
    name: '秋の海',
    yomigana: 'あきのうみ',
    kyukana: '',
    bodai: ['秋の波', '秋の浜'],
    season: 'fall',
    id: 1461,
  },
  {
    name: '秋の蚊',
    yomigana: 'あきのか',
    kyukana: '',
    bodai: ['残る蚊', '別れ蚊', '後れ蚊', '蚊の名残'],
    season: 'fall',
    id: 1462,
  },
  {
    name: '秋の蚊帳',
    yomigana: 'あきのかや',
    kyukana: '',
    bodai: ['秋蚊帳', 'かやの果', 'かやの別れ', '九月蚊帳', '蚊帳の名残'],
    season: 'fall',
    id: 1463,
  },
  {
    name: '秋の川',
    yomigana: 'あきのかわ',
    kyukana: 'あきのかは',
    bodai: ['秋川', '秋江'],
    season: 'fall',
    id: 1464,
  },
  {
    name: '秋の雲',
    yomigana: 'あきのくも',
    kyukana: '',
    bodai: ['秋雲（あきぐも）'],
    season: 'fall',
    id: 1465,
  },
  {
    name: '秋の暮',
    yomigana: 'あきのくれ',
    kyukana: '',
    bodai: ['秋の夕べ', '秋の夕暮'],
    season: 'fall',
    id: 1466,
  },
  {
    name: '秋の声',
    yomigana: 'あきのこえ',
    kyukana: '',
    bodai: ['秋声'],
    season: 'fall',
    id: 1467,
  },
  {
    name: '秋の潮',
    yomigana: 'あきのしお',
    kyukana: 'あきのしほ',
    bodai: ['秋潮'],
    season: 'fall',
    id: 1468,
  },
  {
    name: '秋の霜',
    yomigana: 'あきのしも',
    kyukana: '',
    bodai: ['秋霜', '露霜', '水霜'],
    season: 'fall',
    id: 1469,
  },
  {
    name: '秋の蟬',
    yomigana: 'あきのせみ',
    kyukana: '',
    bodai: ['秋蟬', '残る蟬'],
    season: 'fall',
    id: 1470,
  },
  {
    name: '秋の空',
    yomigana: 'あきのそら',
    kyukana: '',
    bodai: ['秋空（あきぞら）', '秋の天', '秋天'],
    season: 'fall',
    id: 1471,
  },
  {
    name: '秋の田',
    yomigana: 'あきのた',
    kyukana: '',
    bodai: ['秋田', '田の色', '稔田', '稲田'],
    season: 'fall',
    id: 1472,
  },
  {
    name: '秋の蝶',
    yomigana: 'あきのちょう',
    kyukana: 'あきのてふ',
    bodai: ['秋蝶'],
    season: 'fall',
    id: 1473,
  },
  {
    name: '秋の七草',
    yomigana: 'あきのななくさ',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1474,
  },
  {
    name: '秋の虹',
    yomigana: 'あきのにじ',
    kyukana: '',
    bodai: ['秋虹'],
    season: 'fall',
    id: 1475,
  },
  {
    name: '秋の野',
    yomigana: 'あきのの',
    kyukana: '',
    bodai: ['秋野', '秋郊', '秋の原'],
    season: 'fall',
    id: 1476,
  },
  {
    name: '秋の蠅',
    yomigana: 'あきのはえ',
    kyukana: 'あきのはへ',
    bodai: ['残る蝿'],
    season: 'fall',
    id: 1477,
  },
  {
    name: '秋の蜂',
    yomigana: 'あきのはち',
    kyukana: '',
    bodai: ['残る蜂'],
    season: 'fall',
    id: 1478,
  },
  {
    name: '秋の日',
    yomigana: 'あきのひ',
    kyukana: '',
    bodai: ['秋日', '秋日影', '秋日差', '秋の日入', '秋没日'],
    season: 'fall',
    id: 1479,
  },
  {
    name: '秋の灯',
    yomigana: 'あきのひ',
    kyukana: '',
    bodai: ['秋灯', '秋の燈', '秋燈', '秋ともし'],
    season: 'fall',
    id: 1480,
  },
  {
    name: '秋の昼',
    yomigana: 'あきのひる',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1481,
  },
  {
    name: '秋の蛍',
    yomigana: 'あきのほたる',
    kyukana: '',
    bodai: ['秋蛍', '残る蛍', '病蛍'],
    season: 'fall',
    id: 1482,
  },
  {
    name: '秋の水',
    yomigana: 'あきのみず',
    kyukana: 'あきのみづ',
    bodai: ['秋水', '水の秋'],
    season: 'fall',
    id: 1483,
  },
  {
    name: '秋の山',
    yomigana: 'あきのやま',
    kyukana: '',
    bodai: ['秋山', '秋嶺', '秋の峰', '山澄む', '山粧ふ', '山の秋'],
    season: 'fall',
    id: 1484,
  },
  {
    name: '秋の夕焼',
    yomigana: 'あきのゆうやけ',
    kyukana: 'あきのゆふやけ',
    bodai: ['秋夕焼', '秋の夕映'],
    season: 'fall',
    id: 1485,
  },
  {
    name: '秋の夜',
    yomigana: 'あきのよる',
    kyukana: '',
    bodai: ['秋の夜', '秋夜', '秋の宵', '夜半の秋'],
    season: 'fall',
    id: 1486,
  },
  {
    name: '秋晴',
    yomigana: 'あきばれ',
    kyukana: '',
    bodai: ['秋の晴', '秋日和'],
    season: 'fall',
    id: 1487,
  },
  {
    name: '秋彼岸',
    yomigana: 'あきひがん',
    kyukana: '',
    bodai: ['後の彼岸'],
    season: 'fall',
    id: 1488,
  },
  {
    name: '秋深し',
    yomigana: 'あきふかし',
    kyukana: '',
    bodai: ['深秋', '秋さぶ', '秋闌', '秋更くる', '秋深む'],
    season: 'fall',
    id: 1489,
  },
  {
    name: '秋遍路',
    yomigana: 'あきへんろ',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1490,
  },
  {
    name: '秋蒔',
    yomigana: 'あきまき',
    kyukana: '',
    bodai: [
      '菜種蒔く',
      '大根蒔く',
      '芥菜蒔く',
      '蚕豆蒔く',
      '豌豆蒔く',
      '罌粟蒔く',
      '紫雲英蒔く',
    ],
    season: 'fall',
    id: 1491,
  },
  {
    name: '秋祭',
    yomigana: 'あきまつり',
    kyukana: '',
    bodai: ['里祭', '村祭', '浦祭', '在祭'],
    season: 'fall',
    id: 1492,
  },
  {
    name: '秋繭',
    yomigana: 'あきまゆ',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1493,
  },
  {
    name: '秋めく',
    yomigana: 'あきめく',
    kyukana: '',
    bodai: ['秋づく'],
    season: 'fall',
    id: 1494,
  },
  {
    name: '通草',
    yomigana: 'あけび',
    kyukana: '',
    bodai: ['通草の実'],
    season: 'fall',
    id: 1495,
  },
  {
    name: '朝寒',
    yomigana: 'あささむ',
    kyukana: '',
    bodai: ['朝寒し'],
    season: 'fall',
    id: 1496,
  },
  {
    name: '蘆刈',
    yomigana: 'あしかり',
    kyukana: '',
    bodai: ['蘆刈る', '刈蘆', '蘆舟', '蘆火'],
    season: 'fall',
    id: 1497,
  },
  {
    name: '蘆の花',
    yomigana: 'あしのはな',
    kyukana: '',
    bodai: ['蘆の穂', '蘆の穂絮', '蘆', '蘆原', '蘆洲', '葭'],
    season: 'fall',
    id: 1498,
  },
  {
    name: '小豆',
    yomigana: 'あずき',
    kyukana: 'あづき',
    bodai: ['新小豆'],
    season: 'fall',
    id: 1499,
  },
  {
    name: '温め酒',
    yomigana: 'あたためざけ',
    kyukana: '',
    bodai: ['温め酒'],
    season: 'fall',
    id: 1500,
  },
  {
    name: '天の川',
    yomigana: 'あまのがわ',
    kyukana: 'あまのがは',
    bodai: ['銀河', '銀漢', '星河'],
    season: 'fall',
    id: 1501,
  },
  {
    name: '粟',
    yomigana: 'あわ',
    kyukana: 'あは',
    bodai: ['粟の穂', '粟畑'],
    season: 'fall',
    id: 1502,
  },
  {
    name: '阿波踊',
    yomigana: 'あわおどり',
    kyukana: 'あはをどり',
    season: 'fall',
    bodai: [],
    id: 1503,
  },
  {
    name: '生身魂',
    yomigana: 'いきみたま',
    kyukana: '',
    bodai: ['生御魂（いきみたま）', '生盆（いきぼん）', '蓮の飯'],
    season: 'fall',
    id: 1504,
  },
  {
    name: '幾秋',
    yomigana: 'いくあき',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1505,
  },
  {
    name: '十六夜',
    yomigana: 'いざよい',
    kyukana: 'いざよひ',
    bodai: ['十六夜の月', 'いざよふ月', '既望'],
    season: 'fall',
    id: 1506,
  },
  {
    name: '一位の実',
    yomigana: 'いちいのみ',
    kyukana: 'いちゐのみ',
    bodai: ['あららぎ', 'おんこ'],
    season: 'fall',
    id: 1507,
  },
  {
    name: '無花果',
    yomigana: 'いちじく',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1508,
  },
  {
    name: '銀杏散る',
    yomigana: 'いちょうちる',
    kyukana: 'いてふちる',
    season: 'fall',
    bodai: [],
    id: 1509,
  },
  {
    name: '銀杏黄葉',
    yomigana: 'いちょうもみじ',
    kyukana: 'いてふもみぢ',
    season: 'fall',
    bodai: [],
    id: 1510,
  },
  {
    name: '一遍忌',
    yomigana: 'いっぺんき',
    kyukana: '',
    bodai: ['遊行忌'],
    season: 'fall',
    id: 1511,
  },
  {
    name: '竃馬',
    yomigana: 'いとど',
    kyukana: '',
    bodai: ['かまどうま', 'かまどむし'],
    season: 'fall',
    id: 1512,
  },
  {
    name: '蝗',
    yomigana: 'いなご',
    kyukana: '',
    bodai: ['螽', '稲子', '螽採'],
    season: 'fall',
    id: 1513,
  },
  {
    name: '稲雀',
    yomigana: 'いなすずめ',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1514,
  },
  {
    name: '稲妻',
    yomigana: 'いなずま',
    kyukana: 'いなづま',
    bodai: ['稲光', '稲つるび'],
    season: 'fall',
    id: 1515,
  },
  {
    name: '犬蓼',
    yomigana: 'いぬたで',
    kyukana: '',
    bodai: ['赤のまんま', '赤のまま'],
    season: 'fall',
    id: 1516,
  },
  {
    name: '稲',
    yomigana: 'いね',
    kyukana: '',
    bodai: ['初穂', '稲穂', '陸穂', '粳', '糯', '稲田', '稲の秋'],
    season: 'fall',
    id: 1517,
  },
  {
    name: '稲刈',
    yomigana: 'いねかり',
    kyukana: '',
    bodai: ['稲刈る', '田刈', '刈稲', '稲束', '稲車', '稲舟'],
    season: 'fall',
    id: 1518,
  },
  {
    name: '稲扱き',
    yomigana: 'いねこき',
    kyukana: '',
    bodai: ['稲打ち', '脱穀', '稲埃'],
    season: 'fall',
    id: 1519,
  },
  {
    name: '稲の花',
    yomigana: 'いねのはな',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1520,
  },
  {
    name: '牛膝',
    yomigana: 'いのこづち',
    kyukana: 'ゐのこづち',
    season: 'fall',
    bodai: [],
    id: 1521,
  },
  {
    name: '猪',
    yomigana: 'いのしし',
    kyukana: 'ゐのしし',
    bodai: ['しし', '野猪'],
    season: 'fall',
    id: 1522,
  },
  {
    name: '茨の実',
    yomigana: 'いばらのみ',
    kyukana: '',
    bodai: ['野茨の実', '野ばらの実'],
    season: 'fall',
    id: 1523,
  },
  {
    name: '佞武多',
    yomigana: 'いぶた',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1524,
  },
  {
    name: '佞',
    yomigana: 'いぶた',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1525,
  },
  {
    name: '居待月',
    yomigana: 'いまちづき',
    kyukana: 'ゐまちづき',
    bodai: ['座待月', '居待', '十八夜の月'],
    season: 'fall',
    id: 1526,
  },
  {
    name: '芋',
    yomigana: 'いも',
    kyukana: '',
    bodai: ['里芋', '親芋', '子芋', '八頭', '芋畑'],
    season: 'fall',
    id: 1527,
  },
  {
    name: '芋嵐',
    yomigana: 'いもあらし',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1528,
  },
  {
    name: '芋煮会',
    yomigana: 'いもにかい',
    kyukana: 'いもにくわい',
    bodai: ['芋煮'],
    season: 'fall',
    id: 1529,
  },
  {
    name: '芋虫',
    yomigana: 'いもむし',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1530,
  },
  {
    name: '色変へぬ松',
    yomigana: 'いろかえぬまつ',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1531,
  },
  {
    name: '色鳥',
    yomigana: 'いろどり',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1532,
  },
  {
    name: '鰯',
    yomigana: 'いわし',
    kyukana: '',
    bodai: ['鰮', '真鰯'],
    season: 'fall',
    id: 1533,
  },
  {
    name: '鰯雲',
    yomigana: 'いわしぐも',
    kyukana: '',
    bodai: ['鱗雲', '鯖雲', '巻積雲'],
    season: 'fall',
    id: 1534,
  },
  {
    name: '鰯引く',
    yomigana: 'いわしひく',
    kyukana: '',
    bodai: ['鰯干す', '鰯網', '鰯船'],
    season: 'fall',
    id: 1535,
  },
  {
    name: '隠元豆',
    yomigana: 'いんげんまめ',
    kyukana: '',
    bodai: ['花ささげ', '千石豆', '味豆'],
    season: 'fall',
    id: 1536,
  },
  {
    name: '雨月',
    yomigana: 'うげつ',
    kyukana: '',
    bodai: ['雨名月', '雨の月', '月の雨'],
    season: 'fall',
    id: 1537,
  },
  {
    name: '鬱金の花',
    yomigana: 'うこんのはな',
    kyukana: '',
    season: 'fall',
    bodai: [],
    id: 1538,
  },
  {
    name: '薄紅葉',
    yomigana: 'うすもみじ',
    kyukana: 'うすもみぢ',
    season: 'fall',
    bodai: [],
    id: 1539,
  },
  {
    name: '大秦の牛祭',
    yomigana: 'うずまさのうしまつり',
    kyukana: '',
    bodai: ['牛祭'],
    season: 'fall',
    id: 1540,
  },
  {
    name: '鶉',
    yomigana: 'うづら',
    kyukana: '',
    bodai: ['鶉篭'],
    season: 'fall',
    id: 1541,
  },
  {
    name: '馬追',
    yomigana: 'うまおい',
    kyukana: 'うまおひ',
    bodai: ['すいっちょ', 'すいと', '馬追虫'],
    season: 'fall',
    id: 1542,
  },
  {
    name: '馬肥ゆる',
    yomigana: 'うまこゆる',
    kyukana: '',
    bodai: ['秋の馬', '秋の駒'],
    season: 'fall',
    id: 1543,
  },
  {
    name: '梅擬',
    yomigana: 'うめもどき',
    kyukana: '',
    bodai: ['落霜紅', '梅嫌'],
    season: 'fall',
    id: 1544,
  },
  {
    name: '末枯',
    yomigana: 'うらがれ',
    kyukana: '',
    bodai: ['末枯るる'],
    season: 'fall',
    id: 1545,
  },
  {
    name: '盂蘭盆会',
    yomigana: 'うらぼんえ',
    kyukana: 'うらぼんゑ',
    bodai: [
      '盂蘭盆',
      '盆',
      '新盆',
      '魂祭',
      '精霊祭',
      '魂棚',
      '霊棚',
      '盆供',
      '瓜の牛',
      '瓜の馬',
      '茄子の牛',
      '茄子の馬',
    ],
    season: 'fall',
    id: 1546,
  },
  {
    name: '漆紅葉',
    yomigana: 'うるしもみじ',
    kyukana: 'うるしもみぢ',
    season: 'fall',
    bodai: [],
    id: 1547,
  },
  {
    name: '浮塵子',
    yomigana: 'うんか',
    kyukana: '',
    bodai: ['ぬかばへ', 'こぬかむし'],
    season: 'fall',
    id: 1548,
  },
  {
    name: '運動会',
    yomigana: 'うんどうかい',
    kyukana: 'うんどうくわい',
    bodai: ['秋季運動会'],
    season: 'fall',
    id: 1549,
  },
  {
    name: 'エイサー',
    yomigana: 'えいさー',
    kyukana: '',
    season: 'fall',
    id: 1550,
    bodai: [],
  },
  {
    name: '枝豆',
    yomigana: 'えだまめ',
    kyukana: '',
    bodai: ['月見豆'],
    season: 'fall',
    id: 1551,
  },
  {
    name: '狗尾草',
    yomigana: 'えのころぐさ',
    kyukana: 'ゑのころぐさ',
    bodai: ['猫じゃらし'],
    season: 'fall',
    id: 1552,
  },
  {
    name: '蝦蔓',
    yomigana: 'えびづる',
    kyukana: '',
    bodai: ['えびづる', 'えびかづら'],
    season: 'fall',
    id: 1553,
  },
  {
    name: '楝の実',
    yomigana: 'おうちのみ',
    kyukana: 'あふちのみ',
    bodai: ['栴檀の実', '樗の実', '金鈴子'],
    season: 'fall',
    id: 1554,
  },
  {
    name: '苧殻',
    yomigana: 'おがら',
    kyukana: 'をがら',
    bodai: ['麻殻'],
    season: 'fall',
    id: 1555,
  },
  {
    name: '荻',
    yomigana: 'おぎ',
    kyukana: 'をぎ',
    bodai: ['荻の風', '荻の声', '荻原'],
    season: 'fall',
    id: 1556,
  },
  {
    name: '晩稲',
    yomigana: 'おくて',
    kyukana: '',
    season: 'fall',
    id: 1557,
    bodai: [],
  },
  {
    name: '白粉花',
    yomigana: 'おしろいばな',
    kyukana: '',
    bodai: ['おしろいの花', '花白粉', 'おしろい'],
    season: 'fall',
    id: 1558,
  },
  {
    name: '落鮎',
    yomigana: 'おちあゆ',
    kyukana: '',
    bodai: ['錆鮎', '渋鮎', '下り鮎', '子持鮎', '秋の鮎'],
    season: 'fall',
    id: 1559,
  },
  {
    name: '落穂',
    yomigana: 'おちぼ',
    kyukana: '',
    bodai: ['落穂拾ひ'],
    season: 'fall',
    id: 1560,
  },
  {
    name: '男郎花',
    yomigana: 'おとこえし',
    kyukana: 'をとこへし',
    bodai: ['をとこめし'],
    season: 'fall',
    id: 1561,
  },
  {
    name: '落し水',
    yomigana: 'おとしみず',
    kyukana: 'おとしみづ',
    bodai: ['水落す', '田水落す', '堰外す'],
    season: 'fall',
    id: 1562,
  },
  {
    name: '囮',
    yomigana: 'おとり',
    kyukana: 'をとり',
    bodai: ['囮番', '囮守', '囮篭'],
    season: 'fall',
    id: 1563,
  },
  {
    name: '踊',
    yomigana: 'おどり',
    kyukana: 'をどり',
    bodai: ['盆踊', '踊子', '踊笠', '踊太鼓', '踊唄', '踊櫓'],
    season: 'fall',
    id: 1564,
  },
  {
    name: '鬼貫忌',
    yomigana: 'おにつらき',
    kyukana: '',
    bodai: ['槿花扇忌'],
    season: 'fall',
    id: 1565,
  },
  {
    name: '尾花蛸',
    yomigana: 'おばなたこ',
    kyukana: '',
    season: 'fall',
    id: 1566,
    bodai: [],
  },
  {
    name: '女郎花',
    yomigana: 'おみなえし',
    kyukana: 'をみなへし',
    bodai: ['をみなめし'],
    season: 'fall',
    id: 1567,
  },
  {
    name: '万年青の実',
    yomigana: 'おもとのみ',
    kyukana: '',
    season: 'fall',
    id: 1568,
    bodai: [],
  },
  {
    name: '面輪板',
    yomigana: 'おもわいた',
    kyukana: '',
    bodai: ['星の貸物', '貸し小袖'],
    season: 'fall',
    id: 1569,
  },
  {
    name: '貝割菜',
    yomigana: 'かいわりな',
    kyukana: 'かひわりな',
    bodai: ['貝割れ菜'],
    season: 'fall',
    id: 1570,
  },
  {
    name: '案山子',
    yomigana: 'かがし',
    kyukana: '',
    bodai: ['かかし', '捨案山子'],
    season: 'fall',
    id: 1571,
  },
  {
    name: '柿',
    yomigana: 'かき',
    kyukana: '',
    bodai: ['甘柿', '渋柿', '富有柿', '木守柿'],
    season: 'fall',
    id: 1572,
  },
  {
    name: '柿紅葉',
    yomigana: 'かきもみじ',
    kyukana: 'かきもみぢ',
    season: 'fall',
    id: 1573,
    bodai: [],
  },
  {
    name: '懸巣',
    yomigana: 'かけす',
    kyukana: '',
    bodai: ['樫鳥', '橿鳥'],
    season: 'fall',
    id: 1574,
  },
  {
    name: '蜉蝣',
    yomigana: 'かげろう',
    kyukana: 'かげろふ',
    season: 'fall',
    id: 1575,
    bodai: [],
  },
  {
    name: '樫の実',
    yomigana: 'かしのみ',
    kyukana: '',
    season: 'fall',
    id: 1576,
    bodai: [],
  },
  {
    name: '鰍',
    yomigana: 'かじか',
    kyukana: '',
    bodai: ['石伏', '石斑魚', '川をこぜ', 'ぐず'],
    season: 'fall',
    id: 1577,
  },
  {
    name: '梶の葉',
    yomigana: 'かじのは',
    kyukana: 'かぢのは',
    season: 'fall',
    id: 1578,
    bodai: [],
  },
  {
    name: '風の盆',
    yomigana: 'かぜのぼん',
    kyukana: '',
    bodai: ['おわら祭', '八尾の廻り盆'],
    season: 'fall',
    id: 1579,
  },
  {
    name: '門火',
    yomigana: 'かどび',
    kyukana: '',
    bodai: ['迎火', '送火', '魂迎', '魂送', '苧殻焚く', '苧殻火'],
    season: 'fall',
    id: 1580,
  },
  {
    name: '鉦叩',
    yomigana: 'かねたたき',
    kyukana: '',
    season: 'fall',
    id: 1581,
    bodai: [],
  },
  {
    name: '鹿火屋',
    yomigana: 'かびや',
    kyukana: '',
    bodai: ['鹿火屋守'],
    season: 'fall',
    id: 1582,
  },
  {
    name: '南瓜',
    yomigana: 'かぼちゃ',
    kyukana: '',
    bodai: ['たうなす', 'なんきん', 'ぼうぶら', '鹿ヶ谷南瓜'],
    season: 'fall',
    id: 1583,
  },
  {
    name: '蟷螂',
    yomigana: 'かまきり',
    kyukana: '',
    bodai: ['たうらう', '鎌切', '斧虫', '疣毟', 'いぼむしり'],
    season: 'fall',
    id: 1584,
  },
  {
    name: '萱',
    yomigana: 'かや',
    kyukana: '',
    bodai: ['萱の穂', '萱原'],
    season: 'fall',
    id: 1585,
  },
  {
    name: '萱刈る',
    yomigana: 'かやかる',
    kyukana: '',
    season: 'fall',
    id: 1586,
    bodai: [],
  },
  {
    name: '榧の実',
    yomigana: 'かやのみ',
    kyukana: '',
    season: 'fall',
    id: 1587,
    bodai: [],
  },
  {
    name: '烏瓜',
    yomigana: 'からすうり',
    kyukana: '',
    season: 'fall',
    id: 1588,
    bodai: [],
  },
  {
    name: '雁',
    yomigana: 'かり',
    kyukana: '',
    bodai: [
      '雁',
      'かりがね',
      '真雁',
      '菱喰',
      '初雁',
      '雁渡る',
      '雁来る',
      '雁の列',
      '雁の棹',
      '雁行',
      '雁の声',
      '落雁',
    ],
    season: 'fall',
    id: 1589,
  },
  {
    name: '刈田',
    yomigana: 'かりた',
    kyukana: '',
    bodai: ['刈田道', '刈田嵐'],
    season: 'fall',
    id: 1590,
  },
  {
    name: '雁渡し',
    yomigana: 'かりわたし',
    kyukana: '',
    bodai: ['青北風'],
    season: 'fall',
    id: 1591,
  },
  {
    name: '榠櫨の実',
    yomigana: 'かりんのみ',
    kyukana: 'くわりんのみ',
    bodai: ['花梨の実'],
    season: 'fall',
    id: 1592,
  },
  {
    name: '刈萱',
    yomigana: 'かるかや',
    kyukana: '',
    bodai: ['めがるかや', 'をがるかや'],
    season: 'fall',
    id: 1593,
  },
  {
    name: '邯鄲',
    yomigana: 'かんたん',
    kyukana: '',
    season: 'fall',
    id: 1594,
    bodai: [],
  },
  {
    name: '竿燈',
    yomigana: 'かんとう',
    kyukana: '',
    season: 'fall',
    id: 1595,
    bodai: [],
  },
  {
    name: 'カンナ',
    yomigana: 'かんな',
    kyukana: '',
    bodai: ['花カンナ'],
    season: 'fall',
    id: 1596,
  },
  {
    name: '寒露',
    yomigana: 'かんろ',
    kyukana: '',
    season: 'fall',
    id: 1597,
    bodai: [],
  },
  {
    name: '桔梗',
    yomigana: 'ききょう',
    kyukana: 'ききやう',
    bodai: ['きちかう'],
    season: 'fall',
    id: 1598,
  },
  {
    name: '菊',
    yomigana: 'きく',
    kyukana: '',
    bodai: [
      '菊の花',
      '隠君子',
      '千代見草',
      '白菊',
      '黄菊',
      '大菊',
      '小菊',
      '初菊',
      '厚物咲',
      '懸崖菊',
      '菊畑',
      '菊の宿',
      '菊作り',
      '菊日和',
    ],
    season: 'fall',
    id: 1599,
  },
  {
    name: '菊供養',
    yomigana: 'きくくよう',
    kyukana: 'きくくやう',
    season: 'fall',
    id: 1600,
    bodai: [],
  },
  {
    name: '菊膾',
    yomigana: 'きくなます',
    kyukana: '',
    season: 'fall',
    id: 1601,
    bodai: [],
  },
  {
    name: '菊人形',
    yomigana: 'きくにんぎょう',
    kyukana: 'きくにんぎやう',
    bodai: ['菊師', '菊人形展'],
    season: 'fall',
    id: 1602,
  },
  {
    name: '菊枕',
    yomigana: 'きくまくら',
    kyukana: '',
    season: 'fall',
    id: 1603,
    bodai: [],
  },
  {
    name: '鬼城忌',
    yomigana: 'きじょうき',
    kyukana: 'きじやうき',
    season: 'fall',
    id: 1604,
    bodai: [],
  },
  {
    name: '啄木鳥',
    yomigana: 'きつつき',
    kyukana: '',
    bodai: ['けら', 'けらつつき', '赤げら', '青げら'],
    season: 'fall',
    id: 1605,
  },
  {
    name: '衣被',
    yomigana: 'きぬかつぎ',
    kyukana: '',
    season: 'fall',
    id: 1606,
    bodai: [],
  },
  {
    name: '絹雲',
    yomigana: 'きぬぐも',
    kyukana: '',
    bodai: ['巻雲'],
    season: 'fall',
    id: 1607,
  },
  {
    name: '砧',
    yomigana: 'きぬた',
    kyukana: '',
    bodai: ['碪', '砧打つ', '衣打つ'],
    season: 'fall',
    id: 1608,
  },
  {
    name: '茸',
    yomigana: 'きのこ',
    kyukana: '',
    bodai: ['菌', '茸', '茸飯', '舞茸', 'ひら茸'],
    season: 'fall',
    id: 1609,
  },
  {
    name: '黍',
    yomigana: 'きび',
    kyukana: '',
    bodai: ['黍の穂', '黍畑'],
    season: 'fall',
    id: 1610,
  },
  {
    name: '黍嵐',
    yomigana: 'きびあらし',
    kyukana: '',
    bodai: ['芋嵐'],
    season: 'fall',
    id: 1611,
  },
  {
    name: '休暇明け',
    yomigana: 'きゅうかあけ',
    kyukana: '',
    bodai: ['休暇果つ', '二学期'],
    season: 'fall',
    id: 1612,
  },
  {
    name: '凶作',
    yomigana: 'きょうさく',
    kyukana: '',
    bodai: ['不作', '凶年'],
    season: 'fall',
    id: 1613,
  },
  {
    name: '去来忌',
    yomigana: 'きょらいき',
    kyukana: '',
    season: 'fall',
    id: 1614,
    bodai: [],
  },
  {
    name: '霧',
    yomigana: 'きり',
    kyukana: '',
    bodai: [
      '朝霧',
      '夕霧',
      '夜霧',
      '山霧',
      '川霧',
      '狭霧',
      '霧襖',
      '霧雨',
      '濃霧',
      '霧笛',
    ],
    season: 'fall',
    id: 1615,
  },
  {
    name: '螽蟖',
    yomigana: 'きりぎりす',
    kyukana: '',
    bodai: ['ぎす', '機織'],
    season: 'fall',
    id: 1616,
  },
  {
    name: '桐の実',
    yomigana: 'きりのみ',
    kyukana: '',
    season: 'fall',
    id: 1617,
    bodai: [],
  },
  {
    name: '桐一葉',
    yomigana: 'きりひとは',
    kyukana: '',
    bodai: ['一葉', '一葉落つ'],
    season: 'fall',
    id: 1618,
  },
  {
    name: '金柑',
    yomigana: 'きんかん',
    kyukana: '',
    season: 'fall',
    id: 1619,
    bodai: [],
  },
  {
    name: '銀杏',
    yomigana: 'ぎんなん',
    kyukana: '',
    bodai: ['銀杏の実'],
    season: 'fall',
    id: 1620,
  },
  {
    name: '九月',
    yomigana: 'くがつ',
    kyukana: 'くぐわつ',
    season: 'fall',
    id: 1621,
    bodai: [],
  },
  {
    name: '九月尽',
    yomigana: 'くがつじん',
    kyukana: 'くぐわつじん',
    bodai: ['秋尽く'],
    season: 'fall',
    id: 1622,
  },
  {
    name: '枸杞の実',
    yomigana: 'くこのみ',
    kyukana: '',
    bodai: ['枸杞子'],
    season: 'fall',
    id: 1623,
  },
  {
    name: '臭木の花',
    yomigana: 'くさぎのはな',
    kyukana: '',
    bodai: ['常山木の花'],
    season: 'fall',
    id: 1624,
  },
  {
    name: '臭木の実',
    yomigana: 'くさぎのみ',
    kyukana: '',
    bodai: ['常山木の実'],
    season: 'fall',
    id: 1625,
  },
  {
    name: '草の市',
    yomigana: 'くさのいち',
    kyukana: '',
    bodai: ['草市', '盆市', '手向の市'],
    season: 'fall',
    id: 1626,
  },
  {
    name: '草の花',
    yomigana: 'くさのはな',
    kyukana: '',
    bodai: ['千草の花'],
    season: 'fall',
    id: 1627,
  },
  {
    name: '草の穂',
    yomigana: 'くさのほ',
    kyukana: '',
    bodai: ['穂草', '草の絮', '草の穂絮'],
    season: 'fall',
    id: 1628,
  },
  {
    name: '草の実',
    yomigana: 'くさのみ',
    kyukana: '',
    season: 'fall',
    id: 1629,
    bodai: [],
  },
  {
    name: '草雲雀',
    yomigana: 'くさひばり',
    kyukana: '',
    bodai: ['朝鈴', '金雲雀'],
    season: 'fall',
    id: 1630,
  },
  {
    name: '草紅葉',
    yomigana: 'くさもみじ',
    kyukana: 'くさもみぢ',
    bodai: ['草の綿', '色づく草'],
    season: 'fall',
    id: 1631,
  },
  {
    name: '薬掘る',
    yomigana: 'くすりほる',
    kyukana: '',
    bodai: ['薬採る', '薬草掘る', '千振引く', '茜掘る'],
    season: 'fall',
    id: 1632,
  },
  {
    name: '葛',
    yomigana: 'くず',
    kyukana: '',
    bodai: ['真葛', '真葛原', '葛の葉'],
    season: 'fall',
    id: 1633,
  },
  {
    name: '葛の花',
    yomigana: 'くずのはな',
    kyukana: '',
    season: 'fall',
    id: 1634,
    bodai: [],
  },
  {
    name: '葛掘る',
    yomigana: 'くずほる',
    kyukana: '',
    bodai: ['葛引く', '葛根掘る'],
    season: 'fall',
    id: 1635,
  },
  {
    name: '崩れ梁',
    yomigana: 'くずれやな',
    kyukana: 'くづれやな',
    season: 'fall',
    id: 1636,
    bodai: [],
  },
  {
    name: '下り梁',
    yomigana: 'くだりやな',
    kyukana: '',
    bodai: ['秋の梁'],
    season: 'fall',
    id: 1637,
  },
  {
    name: '梔子の実',
    yomigana: 'くちなしのみ',
    kyukana: '',
    bodai: ['山梔子'],
    season: 'fall',
    id: 1638,
  },
  {
    name: '轡虫',
    yomigana: 'くつわむし',
    kyukana: '',
    bodai: ['がちやがちや'],
    season: 'fall',
    id: 1639,
  },
  {
    name: '九年母',
    yomigana: 'くねんぼ',
    kyukana: '',
    bodai: ['香燈', 'くねぶ'],
    season: 'fall',
    id: 1640,
  },
  {
    name: '鞍馬の火祭',
    yomigana: 'くらまのひまつり',
    kyukana: '',
    bodai: ['火祭', '鞍馬祭', '靱大明', '神祭'],
    season: 'fall',
    id: 1641,
  },
  {
    name: '栗',
    yomigana: 'くり',
    kyukana: '',
    bodai: ['山栗', '柴栗', '毬栗', '笑栗', '落栗', '虚栗', '焼栗'],
    season: 'fall',
    id: 1642,
  },
  {
    name: '栗虫',
    yomigana: 'くりむし',
    kyukana: '',
    bodai: ['栗の虫'],
    season: 'fall',
    id: 1643,
  },
  {
    name: '栗飯',
    yomigana: 'くりめし',
    kyukana: '',
    bodai: ['栗おこは'],
    season: 'fall',
    id: 1644,
  },
  {
    name: '胡桃',
    yomigana: 'くるみ',
    kyukana: '',
    bodai: ['姫胡桃', '鬼胡桃', '胡桃割る'],
    season: 'fall',
    id: 1645,
  },
  {
    name: '暮の秋',
    yomigana: 'くれのあき',
    kyukana: '',
    bodai: ['秋暮るる', '暮秋', '秋の末'],
    season: 'fall',
    id: 1646,
  },
  {
    name: '茱萸',
    yomigana: 'ぐみ',
    kyukana: '',
    bodai: ['秋茱萸'],
    season: 'fall',
    id: 1647,
  },
  {
    name: '鶏頭',
    yomigana: 'けいとう',
    kyukana: '',
    bodai: ['鶏頭花'],
    season: 'fall',
    id: 1648,
  },
  {
    name: '敬老の日',
    yomigana: 'けいろうのひ',
    kyukana: 'けいらうのひ',
    bodai: ['老人の日', 'としよりの日'],
    season: 'fall',
    id: 1649,
  },
  {
    name: '螻蛄鳴く',
    yomigana: 'けらなく',
    kyukana: '',
    bodai: ['おけら鳴く', '地虫鳴く'],
    season: 'fall',
    id: 1650,
  },
  {
    name: '芸術祭',
    yomigana: 'げいじゅつさい',
    kyukana: '',
    season: 'fall',
    id: 1651,
    bodai: [],
  },
  {
    name: '解夏',
    yomigana: 'げげ',
    kyukana: '',
    bodai: ['夏明', '夏の果', '仏歓喜日', '送行', '夏書納'],
    season: 'fall',
    id: 1652,
  },
  {
    name: '源義忌',
    yomigana: 'げんよしき',
    kyukana: '',
    bodai: ['秋燕忌'],
    season: 'fall',
    id: 1653,
  },
  {
    name: '柑子',
    yomigana: 'こうじ',
    kyukana: 'かうじ',
    bodai: ['柑子蜜柑'],
    season: 'fall',
    id: 1654,
  },
  {
    name: '黄葉',
    yomigana: 'こうよう',
    kyukana: 'くわうえふ',
    bodai: ['黄葉'],
    season: 'fall',
    id: 1655,
  },
  {
    name: '黄落',
    yomigana: 'こうらく',
    kyukana: 'くわうらく',
    bodai: ['黄落期'],
    season: 'fall',
    id: 1656,
  },
  {
    name: '蟋蟀',
    yomigana: 'こおろぎ',
    kyukana: 'こほろぎ',
    bodai: ['蛬', 'こほろぎ', 'ちちろ', 'ちちろ虫', 'つづれさせ'],
    season: 'fall',
    id: 1657,
  },
  {
    name: '古酒',
    yomigana: 'こしゅ',
    kyukana: '',
    bodai: ['古酒'],
    season: 'fall',
    id: 1658,
  },
  {
    name: 'コスモス',
    yomigana: 'こすもす',
    kyukana: '',
    bodai: ['秋桜', 'おほはるしやぎく'],
    season: 'fall',
    id: 1659,
  },
  {
    name: '小鳥狩',
    yomigana: 'ことりがり',
    kyukana: '',
    bodai: ['小鳥網', '霞網', '鳥屋師', 'ひるてん', '高はご'],
    season: 'fall',
    id: 1660,
  },
  {
    name: '木の実',
    yomigana: 'このみ',
    kyukana: '',
    bodai: ['木の実落つ', '木の実降る', '木の実雨', '木の実独楽'],
    season: 'fall',
    id: 1661,
  },
  {
    name: '細杷',
    yomigana: 'こまざらい',
    kyukana: '',
    season: 'fall',
    id: 1662,
    bodai: [],
  },
  {
    name: '牛蒡引く',
    yomigana: 'ごぼうひく',
    kyukana: 'ごばうひく',
    bodai: ['牛蒡掘る'],
    season: 'fall',
    id: 1663,
  },
  {
    name: '胡麻',
    yomigana: 'ごま',
    kyukana: '',
    season: 'fall',
    id: 1664,
    bodai: [],
  },
  {
    name: '西鶴忌',
    yomigana: 'さいかくき',
    kyukana: '',
    season: 'fall',
    id: 1665,
    bodai: [],
  },
  {
    name: '皀角子',
    yomigana: 'さいかち',
    kyukana: '',
    bodai: ['さいかちの実', '皀莢'],
    season: 'fall',
    id: 1666,
  },
  {
    name: '桜紅葉',
    yomigana: 'さくらもみじ',
    kyukana: 'さくらもみぢ',
    season: 'fall',
    id: 1667,
    bodai: [],
  },
  {
    name: '鮭',
    yomigana: 'さけ',
    kyukana: '',
    bodai: ['初鮭', '鮭漁', '鮭打ち', '鮭小屋'],
    season: 'fall',
    id: 1668,
  },
  {
    name: 'ささげ',
    yomigana: 'ささげ',
    kyukana: '',
    bodai: ['十六ささげ', '十八ささげ'],
    season: 'fall',
    id: 1669,
  },
  {
    name: '甘藷',
    yomigana: 'さつまいも',
    kyukana: '',
    bodai: ['薩摩薯', '琉球藷', '甘藷（かんしょ）'],
    season: 'fall',
    id: 1670,
  },
  {
    name: 'サフラン',
    yomigana: 'さふらん',
    kyukana: '',
    bodai: ['泪夫藍（さふらん）'],
    season: 'fall',
    id: 1671,
  },
  {
    name: '猿酒',
    yomigana: 'さるざけ',
    kyukana: '',
    bodai: ['ましら酒'],
    season: 'fall',
    id: 1672,
  },
  {
    name: '爽やか',
    yomigana: 'さわやか',
    kyukana: 'さはやか',
    bodai: ['爽気', '秋爽', '爽涼', 'さやけし', 'さやか'],
    season: 'fall',
    id: 1673,
  },
  {
    name: '珊瑚樹の実',
    yomigana: 'さんごじゅのみ',
    kyukana: '',
    bodai: ['珊瑚の実'],
    season: 'fall',
    id: 1674,
  },
  {
    name: '山椒売',
    yomigana: 'さんしょううり',
    kyukana: '',
    season: 'fall',
    id: 1675,
    bodai: [],
  },
  {
    name: '山椒の実',
    yomigana: 'さんしょうのみ',
    kyukana: '',
    bodai: ['実山椒'],
    season: 'fall',
    id: 1676,
  },
  {
    name: '秋刀魚',
    yomigana: 'さんま',
    kyukana: '',
    bodai: ['さいら', '初さんま'],
    season: 'fall',
    id: 1677,
  },
  {
    name: '石榴',
    yomigana: 'ざくろ',
    kyukana: '',
    bodai: ['柘榴', '実石榴'],
    season: 'fall',
    id: 1678,
  },
  {
    name: '残菊',
    yomigana: 'ざんぎく',
    kyukana: '',
    bodai: ['残り菊', '十日の菊'],
    season: 'fall',
    id: 1679,
  },
  {
    name: '残暑',
    yomigana: 'ざんしょ',
    kyukana: '',
    bodai: ['残る暑さ', '秋暑し', '秋の暑さ', '秋署'],
    season: 'fall',
    id: 1680,
  },
  {
    name: '椎茸',
    yomigana: 'しいたけ',
    kyukana: '',
    season: 'fall',
    id: 1681,
    bodai: [],
  },
  {
    name: '椎の実',
    yomigana: 'しいのみ',
    kyukana: 'しひのみ',
    bodai: ['落椎'],
    season: 'fall',
    id: 1682,
  },
  {
    name: '紫苑',
    yomigana: 'しおん',
    kyukana: 'しをん',
    bodai: ['紫苑の菊', 'しをに'],
    season: 'fall',
    id: 1683,
  },
  {
    name: '鹿',
    yomigana: 'しか',
    kyukana: '',
    bodai: ['牡鹿', '牝鹿', '小牡鹿', '鹿の声', '鹿笛'],
    season: 'fall',
    id: 1684,
  },
  {
    name: '鹿の角伐',
    yomigana: 'しかのつのきり',
    kyukana: '',
    bodai: ['角切', '春日の角伐', '鹿寄せ'],
    season: 'fall',
    id: 1685,
  },
  {
    name: '子規忌',
    yomigana: 'しきき',
    kyukana: '',
    bodai: ['糸瓜忌', '獺祭忌'],
    season: 'fall',
    id: 1686,
  },
  {
    name: '鴫',
    yomigana: 'しぎ',
    kyukana: '',
    bodai: ['田鴫', '磯鴫'],
    season: 'fall',
    id: 1687,
  },
  {
    name: '鹿垣',
    yomigana: 'ししがき',
    kyukana: '',
    bodai: ['鹿小屋', '犬垣', '猪垣'],
    season: 'fall',
    id: 1688,
  },
  {
    name: '紫蘇の実',
    yomigana: 'しそのみ',
    kyukana: '',
    season: 'fall',
    id: 1689,
    bodai: [],
  },
  {
    name: '樝子の実',
    yomigana: 'しどみのみ',
    kyukana: '',
    bodai: ['草木瓜の実'],
    season: 'fall',
    id: 1690,
  },
  {
    name: '芝神明祭',
    yomigana: 'しばしんめいまつり',
    kyukana: '',
    bodai: ['生姜市', 'だらだら祭'],
    season: 'fall',
    id: 1691,
  },
  {
    name: '渋取',
    yomigana: 'しぶとり',
    kyukana: '',
    bodai: ['柿渋取る', '渋搗く', '新渋', '生渋', '一番渋', '二番渋'],
    season: 'fall',
    id: 1692,
  },
  {
    name: '占地',
    yomigana: 'しめじ',
    kyukana: 'しめぢ',
    bodai: ['湿地', 'しめぢ茸'],
    season: 'fall',
    id: 1693,
  },
  {
    name: '秋海棠',
    yomigana: 'しゅうかいどう',
    kyukana: 'しうかいだう',
    bodai: ['断腸花'],
    season: 'fall',
    id: 1694,
  },
  {
    name: '秋気',
    yomigana: 'しゅうき',
    kyukana: '',
    season: 'fall',
    id: 1695,
    bodai: [],
  },
  {
    name: '秋耕',
    yomigana: 'しゅうこう',
    kyukana: 'しうかう',
    season: 'fall',
    id: 1696,
    bodai: [],
  },
  {
    name: '秋思',
    yomigana: 'しゅうし',
    kyukana: 'しうし',
    bodai: ['秋あはれ', '秋さびし', '傷秋', '秋意'],
    season: 'fall',
    id: 1697,
  },
  {
    name: '秋雪',
    yomigana: 'しゅうせつ',
    kyukana: '',
    bodai: ['秋の雪（あきのゆき）、秋の初雪（あきのはつゆき）'],
    season: 'fall',
    id: 1698,
  },
  {
    name: '終戦記念日',
    yomigana: 'しゅうせんきねんび',
    kyukana: 'しうせんきねんび',
    bodai: ['終戦日', '敗戦日', '敗戦忌', '八月十五日'],
    season: 'fall',
    id: 1699,
  },
  {
    name: '秋分の日',
    yomigana: 'しゅうぶんのひ',
    kyukana: '',
    season: 'fall',
    id: 1700,
    bodai: [],
  },
  {
    name: '秋冷',
    yomigana: 'しゅうれい',
    kyukana: 'しうれい',
    season: 'fall',
    id: 1701,
    bodai: [],
  },
  {
    name: '生姜',
    yomigana: 'しょうが',
    kyukana: 'しやうが',
    bodai: ['新生姜', '葉生姜', '薑'],
    season: 'fall',
    id: 1702,
  },
  {
    name: '生姜市',
    yomigana: 'しょうがいち',
    kyukana: 'しやうがいち',
    bodai: ['だらだらまつり'],
    season: 'fall',
    id: 1703,
  },
  {
    name: '障子洗う',
    yomigana: 'しょうじあらう',
    kyukana: 'しやうじあらふ',
    bodai: ['障子貼る', '障子の貼替'],
    season: 'fall',
    id: 1704,
  },
  {
    name: '処暑',
    yomigana: 'しょしょ',
    kyukana: '',
    season: 'fall',
    id: 1705,
    bodai: [],
  },
  {
    name: '不知火',
    yomigana: 'しらぬい',
    kyukana: 'しらぬひ',
    bodai: ['竜燈'],
    season: 'fall',
    id: 1706,
  },
  {
    name: '震災記念日',
    yomigana: 'しんさいきねんび',
    kyukana: '',
    bodai: ['震災忌', '防災の日'],
    season: 'fall',
    id: 1707,
  },
  {
    name: '新酒',
    yomigana: 'しんしゅ',
    kyukana: '',
    bodai: ['今年酒', '早稲酒', '新走', '利酒', '聞酒'],
    season: 'fall',
    id: 1708,
  },
  {
    name: '新蕎麦',
    yomigana: 'しんそば',
    kyukana: '',
    bodai: ['走り蕎麦'],
    season: 'fall',
    id: 1709,
  },
  {
    name: '新松子',
    yomigana: 'しんちぢり',
    kyukana: '',
    bodai: ['青松毬'],
    season: 'fall',
    id: 1710,
  },
  {
    name: '新豆腐',
    yomigana: 'しんどうふ',
    kyukana: '',
    season: 'fall',
    id: 1711,
    bodai: [],
  },
  {
    name: '新米',
    yomigana: 'しんまい',
    kyukana: '',
    bodai: ['今年米', '早稲の飯'],
    season: 'fall',
    id: 1712,
  },
  {
    name: '新涼',
    yomigana: 'しんりょう',
    kyukana: 'しんりやう',
    bodai: ['初涼', '涼新た', '秋涼し', '秋涼'],
    season: 'fall',
    id: 1713,
  },
  {
    name: '新藁',
    yomigana: 'しんわら',
    kyukana: '',
    bodai: ['今年藁'],
    season: 'fall',
    id: 1714,
  },
  {
    name: '地芝居',
    yomigana: 'じしばい',
    kyukana: 'ぢしばゐ',
    bodai: ['地狂言', '村芝居'],
    season: 'fall',
    id: 1715,
  },
  {
    name: '地蔵盆',
    yomigana: 'じぞうぼん',
    kyukana: 'じざうぼん',
    bodai: ['地蔵会', '地蔵詣', '六地蔵詣', '地蔵幡'],
    season: 'fall',
    id: 1716,
  },
  {
    name: '時代祭',
    yomigana: 'じだいまつり',
    kyukana: '',
    bodai: ['平安祭'],
    season: 'fall',
    id: 1717,
  },
  {
    name: '自然薯',
    yomigana: 'じねんじょ',
    kyukana: '',
    bodai: ['山の芋', '山芋'],
    season: 'fall',
    id: 1718,
  },
  {
    name: '馬鈴薯',
    yomigana: 'じゃがいも',
    kyukana: '',
    bodai: ['ばれいしょ'],
    season: 'fall',
    id: 1719,
  },
  {
    name: '十月',
    yomigana: 'じゅうがつ',
    kyukana: 'じふぐわつ',
    season: 'fall',
    id: 1720,
    bodai: [],
  },
  {
    name: '熟柿',
    yomigana: 'じゅくし',
    kyukana: '',
    season: 'fall',
    id: 1721,
    bodai: [],
  },
  {
    name: '数珠玉',
    yomigana: 'じゅずだま',
    kyukana: '',
    bodai: ['ずずこ'],
    season: 'fall',
    id: 1722,
  },
  {
    name: '水巴忌',
    yomigana: 'すいはき',
    kyukana: '',
    bodai: ['白日忌'],
    season: 'fall',
    id: 1723,
  },
  {
    name: '杉の実',
    yomigana: 'すぎのみ',
    kyukana: '',
    bodai: ['杉鉄砲'],
    season: 'fall',
    id: 1724,
  },
  {
    name: '冷まじ',
    yomigana: 'すさまじ',
    kyukana: '',
    season: 'fall',
    id: 1725,
    bodai: [],
  },
  {
    name: '素十忌',
    yomigana: 'すじゅうき',
    kyukana: 'すじふき',
    bodai: ['金風忌'],
    season: 'fall',
    id: 1726,
  },
  {
    name: '芒',
    yomigana: 'すすき',
    kyukana: '',
    bodai: ['薄', '尾花', '花芒', '鬼芒', '糸芒', '十寸穂の芒'],
    season: 'fall',
    id: 1727,
  },
  {
    name: '鱸',
    yomigana: 'すずき',
    kyukana: '',
    bodai: ['すずき網'],
    season: 'fall',
    id: 1728,
  },
  {
    name: '鈴虫',
    yomigana: 'すずむし',
    kyukana: '',
    bodai: ['月鈴子'],
    season: 'fall',
    id: 1729,
  },
  {
    name: '硯洗',
    yomigana: 'すずりあらい',
    kyukana: 'すずりあらひ',
    bodai: ['机洗'],
    season: 'fall',
    id: 1730,
  },
  {
    name: '酸橘',
    yomigana: 'すだち',
    kyukana: '',
    bodai: ['木酢'],
    season: 'fall',
    id: 1731,
  },
  {
    name: '相撲',
    yomigana: 'すもう',
    kyukana: 'すまふ',
    bodai: ['角力', '宮相撲', '草相撲', '秋場所', '九月場所'],
    season: 'fall',
    id: 1732,
  },
  {
    name: '芋茎',
    yomigana: 'ずいき',
    kyukana: '',
    bodai: ['いもがら'],
    season: 'fall',
    id: 1733,
  },
  {
    name: '背高泡立草',
    yomigana: 'せいたかあわだちそう',
    kyukana: '',
    bodai: ['大泡立草', '泡立草', '秋の麒麟草'],
    season: 'fall',
    id: 1734,
  },
  {
    name: '施餓鬼',
    yomigana: 'せがき',
    kyukana: '',
    bodai: ['施餓鬼会', '施餓鬼寺', '施餓鬼幡', '川施餓鬼', '船施餓鬼'],
    season: 'fall',
    id: 1735,
  },
  {
    name: '鶺鴒',
    yomigana: 'せきれい',
    kyukana: '',
    bodai: ['石たたき', '庭たたき', '黄鶺鴒', '背黒鶺鴒'],
    season: 'fall',
    id: 1736,
  },
  {
    name: '宗祇忌',
    yomigana: 'そうぎき',
    kyukana: '',
    season: 'fall',
    id: 1737,
    bodai: [],
  },
  {
    name: '霜降',
    yomigana: 'そうこう',
    kyukana: 'さうこう',
    season: 'fall',
    id: 1738,
    bodai: [],
  },
  {
    name: '添水',
    yomigana: 'そうづ',
    kyukana: '',
    bodai: ['僧都', 'ばつたんこ', '鹿威し'],
    season: 'fall',
    id: 1739,
  },
  {
    name: 'そぞろ寒',
    yomigana: 'そぞろさむ',
    kyukana: '',
    season: 'fall',
    id: 1740,
    bodai: [],
  },
  {
    name: '藁麦刈',
    yomigana: 'そばかり',
    kyukana: '',
    bodai: ['刈藁麦', '藁麦干す'],
    season: 'fall',
    id: 1741,
  },
  {
    name: '蕎麦の花',
    yomigana: 'そばのはな',
    kyukana: '',
    bodai: ['花蕎麦'],
    season: 'fall',
    id: 1742,
  },
  {
    name: '雑木紅葉',
    yomigana: 'ぞうきもみじ',
    kyukana: 'ざふきもみぢ',
    season: 'fall',
    id: 1743,
    bodai: [],
  },
  {
    name: '体育の日',
    yomigana: 'たいいくのひ',
    kyukana: '',
    season: 'fall',
    id: 1744,
    bodai: [],
  },
  {
    name: '台風',
    yomigana: 'たいふう',
    kyukana: '',
    bodai: ['颱風', '颱風圏', '颱風裡', '颱風禍', '颱風の眼'],
    season: 'fall',
    id: 1745,
  },
  {
    name: '高きに登る',
    yomigana: 'たかきにのぼる',
    kyukana: '',
    bodai: ['登高'],
    season: 'fall',
    id: 1746,
  },
  {
    name: '鷹渡る',
    yomigana: 'たかわたる',
    kyukana: '',
    bodai: ['落鷹', '鷹柱', 'はぐれ鷹'],
    season: 'fall',
    id: 1747,
  },
  {
    name: '茸狩',
    yomigana: 'たけがり',
    kyukana: '',
    bodai: ['茸狩', '茸とり', '菌狩', '茸篭', '茸筵', '茸山'],
    season: 'fall',
    id: 1748,
  },
  {
    name: '竹伐',
    yomigana: 'たけきる',
    kyukana: '',
    season: 'fall',
    id: 1749,
    bodai: [],
  },
  {
    name: '竹の春',
    yomigana: 'たけのはる',
    kyukana: '',
    season: 'fall',
    id: 1750,
    bodai: [],
  },
  {
    name: '橘',
    yomigana: 'たちばな',
    kyukana: '',
    season: 'fall',
    id: 1751,
    bodai: [],
  },
  {
    name: '立待月',
    yomigana: 'たちまちづき',
    kyukana: '',
    bodai: ['立待', '十七夜'],
    season: 'fall',
    id: 1752,
  },
  {
    name: '龍田姫',
    yomigana: 'たつたひめ',
    kyukana: '',
    season: 'fall',
    id: 1753,
    bodai: [],
  },
  {
    name: '蓼の花',
    yomigana: 'たでのはな',
    kyukana: '',
    bodai: ['蓼の穂', '穂蓼', '大毛蓼'],
    season: 'fall',
    id: 1754,
  },
  {
    name: '七夕',
    yomigana: 'たなばた',
    kyukana: '',
    bodai: [
      '七夕祭',
      '星祭',
      '星合',
      '星迎',
      '星今宵',
      '二星',
      '牽牛',
      '織女',
      '七夕竹',
      '七夕流し',
      '願ひの糸',
      '七夕雨･洗車雨',
    ],
    season: 'fall',
    id: 1755,
  },
  {
    name: '種採',
    yomigana: 'たねとり',
    kyukana: '',
    season: 'fall',
    id: 1756,
    bodai: [],
  },
  {
    name: '種茄子',
    yomigana: 'たねなす',
    kyukana: '',
    bodai: ['種茄子'],
    season: 'fall',
    id: 1757,
  },
  {
    name: '煙草の花',
    yomigana: 'たばこのはな',
    kyukana: '',
    bodai: ['花煙草'],
    season: 'fall',
    id: 1758,
  },
  {
    name: '魂祭',
    yomigana: 'たままつり',
    kyukana: '',
    season: 'fall',
    id: 1759,
    bodai: [],
  },
  {
    name: '大豆',
    yomigana: 'だいず',
    kyukana: 'だいづ',
    bodai: ['新大豆', 'みそ豆'],
    season: 'fall',
    id: 1760,
  },
  {
    name: '橙',
    yomigana: 'だいだい',
    kyukana: '',
    bodai: ['回青燈', 'かぶす'],
    season: 'fall',
    id: 1761,
  },
  {
    name: '大文字',
    yomigana: 'だいもんじ',
    kyukana: '',
    bodai: ['大文字の火', '精霊送火', '妙法の火', '船形の火', '鳥居形の火'],
    season: 'fall',
    id: 1762,
  },
  {
    name: '蛇笏忌',
    yomigana: 'だこつき',
    kyukana: '',
    bodai: ['山廬忌'],
    season: 'fall',
    id: 1763,
  },
  {
    name: '茶立虫',
    yomigana: 'ちゃたてむし',
    kyukana: '',
    bodai: ['あづきあらひ'],
    season: 'fall',
    id: 1764,
  },
  {
    name: '中元',
    yomigana: 'ちゅうげん',
    kyukana: '',
    bodai: ['お中元', '中元贈答', '盆礼', '盆見舞'],
    season: 'fall',
    id: 1765,
  },
  {
    name: '仲秋',
    yomigana: 'ちゅうしゅう',
    kyukana: 'ちゆうしう',
    bodai: ['中秋', '秋半ば', '仲の秋'],
    season: 'fall',
    id: 1766,
  },
  {
    name: '重陽',
    yomigana: 'ちょうよう',
    kyukana: 'ちようやう',
    bodai: [
      '重九',
      '菊の節句',
      '菊の日',
      '今日の菊',
      '菊酒',
      '重陽の宴',
      '菊の宴',
    ],
    season: 'fall',
    id: 1767,
  },
  {
    name: '月',
    yomigana: 'つき',
    kyukana: '',
    bodai: [
      '初月',
      '二日月',
      '三日月',
      '新月',
      '弦月',
      '夕月',
      '宵月',
      '夕月夜',
      '有明月',
      '昼の月',
      '遅月',
      '月白',
      '月夜',
      '月の出',
      '月光',
      '月明り',
      '月影',
    ],
    season: 'fall',
    id: 1768,
  },
  {
    name: '月見',
    yomigana: 'つきみ',
    kyukana: '',
    bodai: ['観月', '月祭', '月の宴', '月を待つ', '月見酒', '月見団子'],
    season: 'fall',
    id: 1769,
  },
  {
    name: '鶫',
    yomigana: 'つぐみ',
    kyukana: '',
    season: 'fall',
    id: 1770,
    bodai: [],
  },
  {
    name: '蔦',
    yomigana: 'つた',
    kyukana: '',
    bodai: ['蔦かづら', '蔦紅葉', '錦蔦'],
    season: 'fall',
    id: 1771,
  },
  {
    name: '椿の実',
    yomigana: 'つばきのみ',
    kyukana: '',
    season: 'fall',
    id: 1772,
    bodai: [],
  },
  {
    name: '燕帰る',
    yomigana: 'つばめかえる',
    kyukana: 'つばめかへる',
    bodai: ['帰燕', '去ぬ燕', '秋燕', '秋燕'],
    season: 'fall',
    id: 1773,
  },
  {
    name: '露',
    yomigana: 'つゆ',
    kyukana: '',
    bodai: [
      '白露',
      '朝露',
      '夜露',
      '露の玉',
      '露けし',
      '露時雨',
      '露葎',
      '芋の露',
    ],
    season: 'fall',
    id: 1774,
  },
  {
    name: '露草',
    yomigana: 'つゆくさ',
    kyukana: '',
    bodai: ['月草', '蛍草'],
    season: 'fall',
    id: 1775,
  },
  {
    name: '露寒',
    yomigana: 'つゆさむ',
    kyukana: '',
    bodai: ['露寒し'],
    season: 'fall',
    id: 1776,
  },
  {
    name: '蔓梅擬',
    yomigana: 'つるうめもどき',
    kyukana: '',
    bodai: ['つるもどき'],
    season: 'fall',
    id: 1777,
  },
  {
    name: '鶴来る',
    yomigana: 'つるきたる',
    kyukana: '',
    bodai: ['鶴渡る', '田鶴渡る'],
    season: 'fall',
    id: 1778,
  },
  {
    name: '釣瓶落し',
    yomigana: 'つるべおとし',
    kyukana: '',
    bodai: ['秋の落日'],
    season: 'fall',
    id: 1779,
  },
  {
    name: '汀女忌',
    yomigana: 'ていじょき',
    kyukana: 'ていぢよき',
    season: 'fall',
    id: 1780,
    bodai: [],
  },
  {
    name: '照葉',
    yomigana: 'てりは',
    kyukana: 'てりは',
    bodai: ['照紅葉'],
    season: 'fall',
    id: 1781,
  },
  {
    name: '燈火親しむ',
    yomigana: 'とうかしたしむ',
    kyukana: '',
    bodai: ['燈火親し', '燈下親し'],
    season: 'fall',
    id: 1782,
  },
  {
    name: '冬瓜',
    yomigana: 'とうが',
    kyukana: 'とうぐわ',
    bodai: ['冬瓜（とうがん）', 'かもうり', '冬瓜汁'],
    season: 'fall',
    id: 1783,
  },
  {
    name: '唐辛子',
    yomigana: 'とうがらし',
    kyukana: 'たうがらし',
    bodai: ['蕃椒', '鷹の爪'],
    season: 'fall',
    id: 1784,
  },
  {
    name: '玉蜀黍',
    yomigana: 'とうもろこし',
    kyukana: 'たうもろこし',
    bodai: ['もろこし', '南蛮黍'],
    season: 'fall',
    id: 1785,
  },
  {
    name: '灯籠',
    yomigana: 'とうろう',
    kyukana: '',
    bodai: ['盆灯籠', '切子灯籠', '絵灯籠', '高灯籠', '花灯籠'],
    season: 'fall',
    id: 1786,
  },
  {
    name: '灯籠流し',
    yomigana: 'とうろうながし',
    kyukana: '',
    bodai: ['流燈', '流燈会', '精霊流し', '精霊舟'],
    season: 'fall',
    id: 1787,
  },
  {
    name: '十日夜',
    yomigana: 'とおかんや',
    kyukana: 'とほかんや',
    bodai: ['とおかや'],
    season: 'fall',
    id: 1788,
  },
  {
    name: '木賊刈る',
    yomigana: 'とくさかる',
    kyukana: '',
    bodai: ['砥草刈る'],
    season: 'fall',
    id: 1789,
  },
  {
    name: '年尾忌',
    yomigana: 'としおき',
    kyukana: 'としをき',
    season: 'fall',
    id: 1790,
    bodai: [],
  },
  {
    name: '橡の実',
    yomigana: 'とちのみ',
    kyukana: '',
    bodai: ['栃の実'],
    season: 'fall',
    id: 1791,
  },
  {
    name: '鳥威し',
    yomigana: 'とりおどし',
    kyukana: '',
    bodai: ['威銃'],
    season: 'fall',
    id: 1792,
  },
  {
    name: '鳥兜',
    yomigana: 'とりかぶと',
    kyukana: '',
    bodai: ['鳥頭', '兜花'],
    season: 'fall',
    id: 1793,
  },
  {
    name: 'とろろ汁',
    yomigana: 'とろろじる',
    kyukana: '',
    bodai: ['とろろ', 'いも汁', '麦とろ'],
    season: 'fall',
    id: 1794,
  },
  {
    name: '道元忌',
    yomigana: 'どうげんき',
    kyukana: 'どうげんき',
    season: 'fall',
    id: 1795,
    bodai: [],
  },
  {
    name: '毒茸',
    yomigana: 'どくたけ',
    kyukana: '',
    bodai: ['笑い茸', 'けむり茸', '月夜茸'],
    season: 'fall',
    id: 1796,
  },
  {
    name: '団栗',
    yomigana: 'どんぐり',
    kyukana: '',
    bodai: ['櫟の実'],
    season: 'fall',
    id: 1797,
  },
  {
    name: '中稲',
    yomigana: 'なかて',
    kyukana: '',
    season: 'fall',
    id: 1798,
    bodai: [],
  },
  {
    name: '薯蕷',
    yomigana: 'ながいも',
    kyukana: '',
    bodai: ['長薯'],
    season: 'fall',
    id: 1799,
  },
  {
    name: '長月',
    yomigana: 'ながつき',
    kyukana: '',
    bodai: ['菊月'],
    season: 'fall',
    id: 1800,
  },
  {
    name: '梨',
    yomigana: 'なし',
    kyukana: '',
    bodai: ['有の実', '水梨', '洋梨　ラ', 'フランス'],
    season: 'fall',
    id: 1801,
  },
  {
    name: '刀豆',
    yomigana: 'なたまめ',
    kyukana: '',
    bodai: ['鉈豆'],
    season: 'fall',
    id: 1802,
  },
  {
    name: '棗の実',
    yomigana: 'なつめのみ',
    kyukana: '',
    bodai: ['棗'],
    season: 'fall',
    id: 1803,
  },
  {
    name: '撫子',
    yomigana: 'なでしこ',
    kyukana: '',
    bodai: ['川原撫子', '大和撫子'],
    season: 'fall',
    id: 1804,
  },
  {
    name: 'ななかまど',
    yomigana: 'ななかまど',
    kyukana: '',
    bodai: ['七竃'],
    season: 'fall',
    id: 1805,
  },
  {
    name: '鳴子',
    yomigana: 'なるこ',
    kyukana: '',
    bodai: ['引板', 'ひきいた', '鳴竿', '鳴子縄', '鳴子綱'],
    season: 'fall',
    id: 1806,
  },
  {
    name: '南天の実',
    yomigana: 'なんてんのみ',
    kyukana: '',
    bodai: ['実南天'],
    season: 'fall',
    id: 1807,
  },
  {
    name: '南蛮煙管',
    yomigana: 'なんばんぎせる',
    kyukana: '',
    season: 'fall',
    id: 1808,
    bodai: [],
  },
  {
    name: '苦瓜',
    yomigana: 'にがうり',
    kyukana: '',
    bodai: ['茘枝', '蔓茘枝', '錦茘枝'],
    season: 'fall',
    id: 1809,
  },
  {
    name: '濁り酒',
    yomigana: 'にごりざけ',
    kyukana: '',
    bodai: ['どぶろく', '濁酒'],
    season: 'fall',
    id: 1810,
  },
  {
    name: '錦木',
    yomigana: 'にしきぎ',
    kyukana: '',
    bodai: ['錦木紅葉'],
    season: 'fall',
    id: 1811,
  },
  {
    name: '二百十日',
    yomigana: 'にひゃくとおか',
    kyukana: 'にひやくとをか',
    bodai: ['厄日', '二百二十日'],
    season: 'fall',
    id: 1812,
  },
  {
    name: '白膠木紅葉',
    yomigana: 'ぬるでもみじ',
    kyukana: 'ぬるでもみぢ',
    season: 'fall',
    id: 1813,
    bodai: [],
  },
  {
    name: '根釣',
    yomigana: 'ねづり',
    kyukana: '',
    bodai: ['岸釣'],
    season: 'fall',
    id: 1814,
  },
  {
    name: '佞武多',
    yomigana: 'ねぶた',
    kyukana: '',
    bodai: ['ねぷた', 'ねぶた祭', '跳人'],
    season: 'fall',
    id: 1815,
  },
  {
    name: '野菊',
    yomigana: 'のぎく',
    kyukana: '',
    bodai: ['紺菊'],
    season: 'fall',
    id: 1816,
  },
  {
    name: '後の月',
    yomigana: 'のちのつき',
    kyukana: '',
    bodai: ['十三夜', '名残の月', '後の今宵', '後の名月', '豆名月', '栗名月'],
    season: 'fall',
    id: 1817,
  },
  {
    name: '野分',
    yomigana: 'のわき',
    kyukana: '',
    bodai: [
      '野分',
      '野分立つ',
      '野分中',
      '野分後',
      '夕野分',
      '野分雲',
      '野分晴',
    ],
    season: 'fall',
    id: 1818,
  },
  {
    name: '墓参',
    yomigana: 'はかまいり',
    kyukana: 'はかまゐり',
    bodai: ['墓詣', '墓参', '展墓', '掃苔', '墓洗ふ'],
    season: 'fall',
    id: 1819,
  },
  {
    name: '萩',
    yomigana: 'はぎ',
    kyukana: '',
    bodai: [
      '萩の花',
      '白萩',
      '小萩',
      '山萩',
      '野萩',
      'こぼれ萩',
      '乱れ萩',
      '萩原',
      '萩叢',
    ],
    season: 'fall',
    id: 1820,
  },
  {
    name: '萩刈る',
    yomigana: 'はぎかる',
    kyukana: '',
    season: 'fall',
    id: 1821,
    bodai: [],
  },
  {
    name: '白露',
    yomigana: 'はくろ',
    kyukana: '',
    season: 'fall',
    id: 1822,
    bodai: [],
  },
  {
    name: '葉鶏頭',
    yomigana: 'はげいとう',
    kyukana: '',
    bodai: ['雁来紅', 'かまつか'],
    season: 'fall',
    id: 1823,
  },
  {
    name: '稲架',
    yomigana: 'はざ',
    kyukana: '',
    bodai: [
      'はさ',
      '稲掛',
      '掛稲',
      '稲架',
      '稲木',
      '稲城',
      '田母木',
      '稲棒',
      '稲干す',
    ],
    season: 'fall',
    id: 1824,
  },
  {
    name: '蓮の実',
    yomigana: 'はすのみ',
    kyukana: '',
    bodai: ['蓮の実飛ぶ'],
    season: 'fall',
    id: 1825,
  },
  {
    name: '鯊',
    yomigana: 'はぜ',
    kyukana: '',
    bodai: ['沙魚', 'ふるせ', '今年鯊', '鯊の秋', '鯊の潮', '鯊日和'],
    season: 'fall',
    id: 1826,
  },
  {
    name: '櫨ちぎり',
    yomigana: 'はぜちぎり',
    kyukana: '',
    bodai: ['櫨採', '櫨買'],
    season: 'fall',
    id: 1827,
  },
  {
    name: '鯊釣',
    yomigana: 'はぜつり',
    kyukana: '',
    bodai: ['鯊舟'],
    season: 'fall',
    id: 1828,
  },
  {
    name: '櫨の実',
    yomigana: 'はぜのみ',
    kyukana: '',
    season: 'fall',
    id: 1829,
    bodai: [],
  },
  {
    name: '櫨紅葉',
    yomigana: 'はぜもみじ',
    kyukana: 'はぜもみぢ',
    season: 'fall',
    id: 1830,
    bodai: [],
  },
  {
    name: '肌寒',
    yomigana: 'はださむ',
    kyukana: '',
    bodai: ['肌寒し'],
    season: 'fall',
    id: 1831,
  },
  {
    name: '八月',
    yomigana: 'はちがつ',
    kyukana: 'はちぐわつ',
    season: 'fall',
    id: 1832,
    bodai: [],
  },
  {
    name: '八朔',
    yomigana: 'はっさく',
    kyukana: 'はつさく',
    season: 'fall',
    id: 1833,
    bodai: [],
  },
  {
    name: '八朔の祝',
    yomigana: 'はっさくのいわい',
    kyukana: '',
    bodai: ['田面（たのも）の節（せち）'],
    season: 'fall',
    id: 1834,
  },
  {
    name: '初秋',
    yomigana: 'はつあき',
    kyukana: '',
    bodai: ['新秋', '孟秋', '秋初め', '秋口'],
    season: 'fall',
    id: 1835,
  },
  {
    name: '初嵐',
    yomigana: 'はつあらし',
    kyukana: '',
    bodai: ['秋の初風'],
    season: 'fall',
    id: 1836,
  },
  {
    name: '初鴨',
    yomigana: 'はつがも',
    kyukana: '',
    bodai: ['鴨渡る', '鴨来る'],
    season: 'fall',
    id: 1837,
  },
  {
    name: '初潮',
    yomigana: 'はつしお',
    kyukana: 'はつしほ',
    bodai: ['葉月潮', '望の潮'],
    season: 'fall',
    id: 1838,
  },
  {
    name: '初茸',
    yomigana: 'はつたけ',
    kyukana: '',
    season: 'fall',
    id: 1839,
    bodai: [],
  },
  {
    name: '初紅葉',
    yomigana: 'はつもみじ',
    kyukana: 'はつもみぢ',
    season: 'fall',
    id: 1840,
    bodai: [],
  },
  {
    name: '葉月',
    yomigana: 'はづき',
    kyukana: '',
    bodai: ['月見月', '萩月'],
    season: 'fall',
    id: 1841,
  },
  {
    name: '鳩吹',
    yomigana: 'はとふき',
    kyukana: '',
    bodai: ['鳩吹く', '鳩笛'],
    season: 'fall',
    id: 1842,
  },
  {
    name: '花野',
    yomigana: 'はなの',
    kyukana: '',
    bodai: ['花野原', '花野道'],
    season: 'fall',
    id: 1843,
  },
  {
    name: '柞',
    yomigana: 'ははそ',
    kyukana: '',
    bodai: ['柞紅葉', '楢', '小楢'],
    season: 'fall',
    id: 1844,
  },
  {
    name: '隼人瓜',
    yomigana: 'はやとうり',
    kyukana: '',
    season: 'fall',
    id: 1845,
    bodai: [],
  },
  {
    name: '海蠃廻し',
    yomigana: 'ばいまわし',
    kyukana: 'ばいまはし',
    bodai: ['海打ち（ばいうち）', 'ばい独楽', 'べいごま'],
    season: 'fall',
    id: 1846,
  },
  {
    name: '芭蕉',
    yomigana: 'ばしょう',
    kyukana: 'ばせう',
    bodai: ['芭蕉葉'],
    season: 'fall',
    id: 1847,
  },
  {
    name: '螇蚚',
    yomigana: 'ばった',
    kyukana: '',
    bodai: [
      '飛蝗',
      '蟿螽',
      'はたはた',
      'きちきち',
      'きちきちばつた',
      'とのさまばった',
      '精霊ばった',
    ],
    season: 'fall',
    id: 1848,
  },
  {
    name: '晩秋',
    yomigana: 'ばんしゅう',
    kyukana: 'ばんしう',
    bodai: ['晩秋'],
    season: 'fall',
    id: 1849,
  },
  {
    name: '稗',
    yomigana: 'ひえ',
    kyukana: '',
    season: 'fall',
    id: 1850,
    bodai: [],
  },
  {
    name: '蜩',
    yomigana: 'ひぐらし',
    kyukana: '',
    bodai: ['日暮', '茅蜩', 'かなかな'],
    season: 'fall',
    id: 1851,
  },
  {
    name: '菱の実',
    yomigana: 'ひしのみ',
    kyukana: '',
    bodai: ['菱採る', '茹菱'],
    season: 'fall',
    id: 1852,
  },
  {
    name: '鶲',
    yomigana: 'ひたき',
    kyukana: '',
    bodai: ['尉鶲', '火焚鳥'],
    season: 'fall',
    id: 1853,
  },
  {
    name: '穭',
    yomigana: 'ひつじ',
    kyukana: 'ひつぢ',
    bodai: ['稲孫', '穭穂'],
    season: 'fall',
    id: 1854,
  },
  {
    name: '穭田',
    yomigana: 'ひつじだ',
    kyukana: '',
    bodai: ['稲孫田'],
    season: 'fall',
    id: 1855,
  },
  {
    name: '百八燈',
    yomigana: 'ひゃくはちとう',
    kyukana: '',
    bodai: ['百八たい', '南部の火祭', '投松明'],
    season: 'fall',
    id: 1856,
  },
  {
    name: '冷やか',
    yomigana: 'ひややか',
    kyukana: '',
    bodai: ['冷ゆ', '下冷え', '朝冷え', '夕冷え', '雨冷え'],
    season: 'fall',
    id: 1857,
  },
  {
    name: '瓢の実',
    yomigana: 'ひょんのみ',
    kyukana: '',
    bodai: ['ひよん'],
    season: 'fall',
    id: 1858,
  },
  {
    name: '鵯',
    yomigana: 'ひよどり',
    kyukana: '',
    bodai: ['ひよ'],
    season: 'fall',
    id: 1859,
  },
  {
    name: '鶸',
    yomigana: 'ひわ',
    kyukana: 'ひは',
    bodai: ['金雀'],
    season: 'fall',
    id: 1860,
  },
  {
    name: '美男葛',
    yomigana: 'びなんかづら',
    kyukana: '',
    bodai: ['南五味子', '実葛'],
    season: 'fall',
    id: 1861,
  },
  {
    name: 'ピラカンサの実',
    yomigana: 'ぴらかんさのみ',
    kyukana: '',
    season: 'fall',
    id: 1862,
    bodai: [],
  },
  {
    name: '瓢',
    yomigana: 'ふくべ',
    kyukana: '',
    bodai: ['ひさご', '瓢箪', '青瓠', '種瓢'],
    season: 'fall',
    id: 1863,
  },
  {
    name: '更待月',
    yomigana: 'ふけまちづき',
    kyukana: '',
    bodai: ['更待', '二十日月'],
    season: 'fall',
    id: 1864,
  },
  {
    name: '五倍子',
    yomigana: 'ふし',
    kyukana: '',
    bodai: ['ごばいし', 'ふし干す'],
    season: 'fall',
    id: 1865,
  },
  {
    name: '五倍子',
    yomigana: 'ふし',
    kyukana: '',
    bodai: ['五倍子（ごばいし）', 'ふし干す'],
    season: 'fall',
    id: 1866,
  },
  {
    name: '臥待月',
    yomigana: 'ふしまちづき',
    kyukana: '',
    bodai: ['臥待', '寝待月', '寝待'],
    season: 'fall',
    id: 1867,
  },
  {
    name: '富士の初雪',
    yomigana: 'ふじのはつゆき',
    kyukana: '',
    season: 'fall',
    id: 1868,
    bodai: [],
  },
  {
    name: '藤の実',
    yomigana: 'ふじのみ',
    kyukana: 'ふぢのみ',
    season: 'fall',
    id: 1869,
    bodai: [],
  },
  {
    name: '藤袴',
    yomigana: 'ふじばかま',
    kyukana: 'ふぢばかま',
    season: 'fall',
    id: 1870,
    bodai: [],
  },
  {
    name: '文月',
    yomigana: 'ふみづき',
    kyukana: '',
    bodai: ['文月', '七夕月'],
    season: 'fall',
    id: 1871,
  },
  {
    name: '冬支度',
    yomigana: 'ふゆじたく',
    kyukana: '',
    bodai: ['冬用意'],
    season: 'fall',
    id: 1872,
  },
  {
    name: '冬近し',
    yomigana: 'ふゆちかし',
    kyukana: '',
    bodai: ['冬隣', '冬を待つ'],
    season: 'fall',
    id: 1873,
  },
  {
    name: '冬の磯',
    yomigana: 'ふゆのいそ',
    kyukana: '',
    season: 'fall',
    id: 1874,
    bodai: [],
  },
  {
    name: '芙蓉',
    yomigana: 'ふよう',
    kyukana: '',
    bodai: ['花芙蓉', '白芙蓉', '紅芙蓉', '酔芙蓉'],
    season: 'fall',
    id: 1875,
  },
  {
    name: '普羅忌',
    yomigana: 'ふらき',
    kyukana: '',
    bodai: ['立秋忌'],
    season: 'fall',
    id: 1876,
  },
  {
    name: '風炉の名残',
    yomigana: 'ふろのなごり',
    kyukana: '',
    bodai: ['風炉名残', '名残の茶'],
    season: 'fall',
    id: 1877,
  },
  {
    name: '葡萄',
    yomigana: 'ぶどう',
    kyukana: 'ぶだう',
    bodai: ['葡萄園', '葡萄棚'],
    season: 'fall',
    id: 1878,
  },
  {
    name: '文化の日',
    yomigana: 'ぶんかのひ',
    kyukana: 'ぶんくわのひ',
    bodai: ['明治節', '文化祭'],
    season: 'fall',
    id: 1879,
  },
  {
    name: '糸瓜',
    yomigana: 'へちま',
    kyukana: '',
    bodai: ['いとうり', 'ながうり', '糸瓜棚'],
    season: 'fall',
    id: 1880,
  },
  {
    name: '放屁虫',
    yomigana: 'へひりむし',
    kyukana: '',
    bodai: ['へつぴりむし', 'へこきむし', '椿象', '亀虫'],
    season: 'fall',
    id: 1881,
  },
  {
    name: '蛇穴に入る',
    yomigana: 'へびあなにいる',
    kyukana: '',
    bodai: ['秋の蛇', '穴まどひ'],
    season: 'fall',
    id: 1882,
  },
  {
    name: 'べつたら市',
    yomigana: 'べったらいち',
    kyukana: '',
    bodai: ['べつたら漬', '浅漬市'],
    season: 'fall',
    id: 1883,
  },
  {
    name: '弁慶草',
    yomigana: 'べんけいそう',
    kyukana: '',
    bodai: ['血止草'],
    season: 'fall',
    id: 1884,
  },
  {
    name: '箒草',
    yomigana: 'ほうきくさ',
    kyukana: '',
    bodai: ['箒木'],
    season: 'fall',
    id: 1885,
  },
  {
    name: '法師蟬',
    yomigana: 'ほうしぜみ',
    kyukana: 'ほふしぜみ',
    bodai: ['つくつく法師', 'つくつくし', '寒蟬'],
    season: 'fall',
    id: 1886,
  },
  {
    name: '鳳仙花',
    yomigana: 'ほうせんか',
    kyukana: 'ほうせんくわ',
    bodai: ['つまくれない', 'つまべに'],
    season: 'fall',
    id: 1887,
  },
  {
    name: '豊年',
    yomigana: 'ほうねん',
    kyukana: '',
    bodai: ['出来秋', '豊作', '豊の秋'],
    season: 'fall',
    id: 1888,
  },
  {
    name: '鬼灯',
    yomigana: 'ほおずき',
    kyukana: 'ほほづき',
    bodai: ['酸漿', '鬼燈'],
    season: 'fall',
    id: 1889,
  },
  {
    name: '干柿',
    yomigana: 'ほしがき',
    kyukana: '',
    bodai: ['吊し柿', '串柿', '烏柿', '甘干', '枯露柿', '柿干す', '柿簾'],
    season: 'fall',
    id: 1890,
  },
  {
    name: '星月夜',
    yomigana: 'ほしづきよ',
    kyukana: '',
    bodai: ['星月夜', '星明り', '秋の星'],
    season: 'fall',
    id: 1891,
  },
  {
    name: '杜鵑草',
    yomigana: 'ほととぎす',
    kyukana: '',
    bodai: ['ほととぎす草'],
    season: 'fall',
    id: 1892,
  },
  {
    name: '木瓜の実',
    yomigana: 'ぼけのみ',
    kyukana: '',
    season: 'fall',
    id: 1893,
    bodai: [],
  },
  {
    name: '牡丹根分',
    yomigana: 'ぼたんねわけ',
    kyukana: '',
    bodai: ['牡丹接木', '牡丹植う'],
    season: 'fall',
    id: 1894,
  },
  {
    name: '菩提子',
    yomigana: 'ぼだいし',
    kyukana: '',
    bodai: ['菩提の実', '菩提樹の実'],
    season: 'fall',
    id: 1895,
  },
  {
    name: '鰡',
    yomigana: 'ぼら',
    kyukana: '',
    season: 'fall',
    id: 1896,
    bodai: [],
  },
  {
    name: '盆狂言',
    yomigana: 'ぼんきょうげん',
    kyukana: 'ぼんきやうげん',
    bodai: ['盆芝居', '秋狂言', '盆替り'],
    season: 'fall',
    id: 1897,
  },
  {
    name: '盆の月',
    yomigana: 'ぼんのつき',
    kyukana: '',
    season: 'fall',
    id: 1898,
    bodai: [],
  },
  {
    name: '盆休み',
    yomigana: 'ぼんやすみ',
    kyukana: '',
    bodai: ['盆の薮入り'],
    season: 'fall',
    id: 1899,
  },
  {
    name: '盆用意',
    yomigana: 'ぼんようい',
    kyukana: '',
    bodai: ['盆支度'],
    season: 'fall',
    id: 1900,
  },
  {
    name: '真菰の馬',
    yomigana: 'まこものうま',
    kyukana: '',
    bodai: ['七夕馬', '迎馬'],
    season: 'fall',
    id: 1901,
  },
  {
    name: '真菰の花',
    yomigana: 'まこものはな',
    kyukana: '',
    season: 'fall',
    id: 1902,
    bodai: [],
  },
  {
    name: '木天蓼の実',
    yomigana: 'またたびのみ',
    kyukana: '',
    bodai: ['猿梨'],
    season: 'fall',
    id: 1903,
  },
  {
    name: '松茸',
    yomigana: 'まつたけ',
    kyukana: '',
    season: 'fall',
    id: 1904,
    bodai: [],
  },
  {
    name: '松茸飯',
    yomigana: 'まつたけめし',
    kyukana: '',
    season: 'fall',
    id: 1905,
    bodai: [],
  },
  {
    name: '松手入',
    yomigana: 'まつていれ',
    kyukana: '',
    season: 'fall',
    id: 1906,
    bodai: [],
  },
  {
    name: '松虫',
    yomigana: 'まつむし',
    kyukana: '',
    bodai: ['ちんちろ', 'ちんちろりん'],
    season: 'fall',
    id: 1907,
  },
  {
    name: '松虫草',
    yomigana: 'まつむしそう',
    kyukana: 'まつむしさう',
    bodai: ['輪鋒菊'],
    season: 'fall',
    id: 1908,
  },
  {
    name: '待宵',
    yomigana: 'まつよい',
    kyukana: 'まつよひ',
    bodai: ['小望月'],
    season: 'fall',
    id: 1909,
  },
  {
    name: '間引菜',
    yomigana: 'まびきな',
    kyukana: '',
    bodai: ['摘まみ奈', '小菜', '抜菜', '虚抜菜'],
    season: 'fall',
    id: 1910,
  },
  {
    name: '檀の実',
    yomigana: 'まゆみのみ',
    kyukana: '',
    season: 'fall',
    id: 1911,
    bodai: [],
  },
  {
    name: '曼珠沙華',
    yomigana: 'まんじゅしゃげ',
    kyukana: '',
    bodai: ['彼岸花', '死人花', '天涯花', '幽霊花', '捨子花'],
    season: 'fall',
    id: 1912,
  },
  {
    name: '水草紅葉',
    yomigana: 'みずくさもみじ',
    kyukana: 'みづくさもみぢ',
    bodai: ['萍紅葉', '菱紅葉'],
    season: 'fall',
    id: 1913,
  },
  {
    name: '水澄む',
    yomigana: 'みずすむ',
    kyukana: 'みづすむ',
    season: 'fall',
    id: 1914,
    bodai: [],
  },
  {
    name: '水引の花',
    yomigana: 'みずひきのはな',
    kyukana: 'みづひきのはな',
    bodai: ['水引草', '金線草'],
    season: 'fall',
    id: 1915,
  },
  {
    name: 'みせばや',
    yomigana: 'みせばや',
    kyukana: '',
    bodai: ['たまのを'],
    season: 'fall',
    id: 1916,
  },
  {
    name: '千屈菜',
    yomigana: 'みそはぎ',
    kyukana: '',
    bodai: ['鼠尾草', '聖霊花', '溝萩'],
    season: 'fall',
    id: 1917,
  },
  {
    name: '溝蕎麦',
    yomigana: 'みぞそば',
    kyukana: '',
    season: 'fall',
    id: 1918,
    bodai: [],
  },
  {
    name: '身に入む',
    yomigana: 'みにしむ',
    kyukana: '',
    bodai: ['身に沁む'],
    season: 'fall',
    id: 1919,
  },
  {
    name: '蓑虫',
    yomigana: 'みのむし',
    kyukana: '',
    bodai: ['鬼の子', '蓑虫鳴く'],
    season: 'fall',
    id: 1920,
  },
  {
    name: '稔り田',
    yomigana: 'みのりだ',
    kyukana: '',
    season: 'fall',
    id: 1921,
    bodai: [],
  },
  {
    name: '蚯蚓鳴く',
    yomigana: 'みみずなく',
    kyukana: '',
    season: 'fall',
    id: 1922,
    bodai: [],
  },
  {
    name: '茗荷の花',
    yomigana: 'みょうがのはな',
    kyukana: 'めうがのはな',
    bodai: ['秋茗荷'],
    season: 'fall',
    id: 1923,
  },
  {
    name: '零余子',
    yomigana: 'むかご',
    kyukana: '',
    bodai: ['ぬかご', 'いもご'],
    season: 'fall',
    id: 1924,
  },
  {
    name: '零余子飯',
    yomigana: 'むかごめし',
    kyukana: '',
    bodai: ['ぬかご飯'],
    season: 'fall',
    id: 1925,
  },
  {
    name: '木槿',
    yomigana: 'むくげ',
    kyukana: '',
    bodai: ['きはちす', '花木槿', '白木槿', '紅木槿', '底紅', '木槿垣'],
    season: 'fall',
    id: 1926,
  },
  {
    name: '椋鳥',
    yomigana: 'むくどり',
    kyukana: '',
    bodai: ['むく', '白頭扇'],
    season: 'fall',
    id: 1927,
  },
  {
    name: '椋の実',
    yomigana: 'むくのみ',
    kyukana: '',
    season: 'fall',
    id: 1928,
    bodai: [],
  },
  {
    name: '無患子',
    yomigana: 'むくろじ',
    kyukana: '',
    bodai: ['無患子の実'],
    season: 'fall',
    id: 1929,
  },
  {
    name: '無月',
    yomigana: 'むげつ',
    kyukana: '',
    season: 'fall',
    id: 1930,
    bodai: [],
  },
  {
    name: '虫',
    yomigana: 'むし',
    kyukana: '',
    bodai: [
      '虫の声',
      '虫の音',
      '虫時雨',
      '虫の秋',
      '昼の虫',
      '残る虫',
      'すがれ虫',
    ],
    season: 'fall',
    id: 1931,
  },
  {
    name: '虫売',
    yomigana: 'むしうり',
    kyukana: '',
    bodai: ['虫屋'],
    season: 'fall',
    id: 1932,
  },
  {
    name: '郁子',
    yomigana: 'むべ',
    kyukana: '',
    bodai: ['うべ', '郁子の実'],
    season: 'fall',
    id: 1933,
  },
  {
    name: '紫式部',
    yomigana: 'むらさきしきぶ',
    kyukana: '',
    bodai: ['実紫', '小式部', '白式部'],
    season: 'fall',
    id: 1934,
  },
  {
    name: '名月',
    yomigana: 'めいげつ',
    kyukana: '',
    bodai: [
      '明月',
      '望月',
      '満月',
      '今日の月',
      '月今宵',
      '三五の月',
      '十五夜',
      '芋名月',
    ],
    season: 'fall',
    id: 1935,
  },
  {
    name: 'めはじき',
    yomigana: 'めはじき',
    kyukana: '',
    bodai: ['益母草'],
    season: 'fall',
    id: 1936,
  },
  {
    name: '木犀',
    yomigana: 'もくせい',
    kyukana: '',
    bodai: ['金木犀', '銀木犀', '薄黄木犀', '桂の花'],
    season: 'fall',
    id: 1937,
  },
  {
    name: '鵙',
    yomigana: 'もず',
    kyukana: '',
    bodai: ['百舌鳥', '鵙猛る', '鵙の贄', '鵙の声', '鵙日和'],
    season: 'fall',
    id: 1938,
  },
  {
    name: '籾',
    yomigana: 'もみ',
    kyukana: '',
    bodai: ['籾干', '籾摺', '籾筵', '籾臼', '籾摺歌', '籾殻焼く'],
    season: 'fall',
    id: 1939,
  },
  {
    name: '紅葉',
    yomigana: 'もみじ',
    kyukana: 'もみぢ',
    bodai: [
      '紅葉',
      'もみづる',
      '色葉',
      '夕紅葉',
      '村紅葉',
      '谷紅葉',
      '紅葉山',
      '紅葉川',
    ],
    season: 'fall',
    id: 1940,
  },
  {
    name: '紅葉かつ散る',
    yomigana: 'もみじかつちる',
    kyukana: 'もみじかつちる',
    bodai: ['色葉散る', '色ながら散る'],
    season: 'fall',
    id: 1941,
  },
  {
    name: '紅葉狩',
    yomigana: 'もみじがり',
    kyukana: 'もみぢがり',
    bodai: ['紅葉見', '観楓', '紅葉酒', '紅葉茶屋'],
    season: 'fall',
    id: 1942,
  },
  {
    name: '紅葉鮒',
    yomigana: 'もみじぶな',
    kyukana: 'もみぢぶな',
    season: 'fall',
    id: 1943,
    bodai: [],
  },
  {
    name: '桃',
    yomigana: 'もものみ',
    kyukana: '',
    bodai: ['桃の実', '白桃', '水密桃'],
    season: 'fall',
    id: 1944,
  },
  {
    name: '守武忌',
    yomigana: 'もりたけき',
    kyukana: '',
    season: 'fall',
    id: 1945,
    bodai: [],
  },
  {
    name: '夜学',
    yomigana: 'やがく',
    kyukana: '',
    bodai: ['夜学生', '夜学子', '夜学校'],
    season: 'fall',
    id: 1946,
  },
  {
    name: '夜食',
    yomigana: 'やしょく',
    kyukana: '',
    season: 'fall',
    id: 1947,
    bodai: [],
  },
  {
    name: '柳散る',
    yomigana: 'やなぎちる',
    kyukana: '',
    bodai: ['黄柳', '秋の柳'],
    season: 'fall',
    id: 1948,
  },
  {
    name: '八幡放生会',
    yomigana: 'やはたほうじょうえ',
    kyukana: '',
    bodai: ['石清水祭', '男山祭', '南祭', '放生会'],
    season: 'fall',
    id: 1949,
  },
  {
    name: '夜半忌',
    yomigana: 'やはんき',
    kyukana: '',
    bodai: ['底紅忌'],
    season: 'fall',
    id: 1950,
  },
  {
    name: '薮枯らし',
    yomigana: 'やぶからし',
    kyukana: '',
    bodai: ['貧乏かづら'],
    season: 'fall',
    id: 1951,
  },
  {
    name: '藪虱',
    yomigana: 'やぶじらみ',
    kyukana: '',
    bodai: ['草虱'],
    season: 'fall',
    id: 1952,
  },
  {
    name: '山梨の実',
    yomigana: 'やまなしのみ',
    kyukana: '',
    season: 'fall',
    id: 1953,
    bodai: [],
  },
  {
    name: '山葡萄',
    yomigana: 'やまぶどう',
    kyukana: 'やまぶだう',
    bodai: ['野葡萄'],
    season: 'fall',
    id: 1954,
  },
  {
    name: 'やや寒',
    yomigana: 'ややさむ',
    kyukana: '',
    bodai: ['やや寒し', 'うそ寒'],
    season: 'fall',
    id: 1955,
  },
  {
    name: '敗荷',
    yomigana: 'やれはす',
    kyukana: '',
    bodai: ['破れ蓮'],
    season: 'fall',
    id: 1956,
  },
  {
    name: '破れ芭蕉',
    yomigana: 'やればしょう',
    kyukana: 'やればせう',
    season: 'fall',
    id: 1957,
    bodai: [],
  },
  {
    name: '夕顔の実',
    yomigana: 'ゆうがおのみ',
    kyukana: 'ゆうがほのみ',
    season: 'fall',
    id: 1958,
    bodai: [],
  },
  {
    name: '行く秋',
    yomigana: 'ゆくあき',
    kyukana: '',
    bodai: ['去る秋', '秋の別れ', '秋の名残', '秋の行方', '秋去る', '秋過ぐ'],
    season: 'fall',
    id: 1959,
  },
  {
    name: '柚子',
    yomigana: 'ゆず',
    kyukana: '',
    bodai: ['柚子の実'],
    season: 'fall',
    id: 1960,
  },
  {
    name: '柚味噌',
    yomigana: 'ゆみそ',
    kyukana: '',
    bodai: ['柚子味噌', '柚子釜'],
    season: 'fall',
    id: 1961,
  },
  {
    name: '宵闇',
    yomigana: 'よいやみ',
    kyukana: 'よひやみ',
    season: 'fall',
    id: 1962,
    bodai: [],
  },
  {
    name: '夜寒',
    yomigana: 'よさむ',
    kyukana: '',
    bodai: ['宵寒', '夜寒し'],
    season: 'fall',
    id: 1963,
  },
  {
    name: '吉田火祭',
    yomigana: 'よしだひまつり',
    kyukana: '',
    bodai: ['吉田浅間祭', '芒祭', '火伏祭'],
    season: 'fall',
    id: 1964,
  },
  {
    name: '夜長',
    yomigana: 'よなが',
    kyukana: '',
    bodai: ['長き夜', '夜長し'],
    season: 'fall',
    id: 1965,
  },
  {
    name: '夜なべ',
    yomigana: 'よなべ',
    kyukana: '',
    bodai: ['夜仕事', '夜業'],
    season: 'fall',
    id: 1966,
  },
  {
    name: '落花生',
    yomigana: 'らっかせい',
    kyukana: 'らくくわせい',
    bodai: ['南京豆', 'ピーナツ'],
    season: 'fall',
    id: 1967,
  },
  {
    name: '立秋',
    yomigana: 'りっしゅう',
    kyukana: 'りつしう',
    bodai: ['秋立つ', '秋来る', '秋に入る', '今朝の秋', '今日の秋'],
    season: 'fall',
    id: 1968,
  },
  {
    name: '流星',
    yomigana: 'りゅうせい',
    kyukana: 'りうせい',
    bodai: ['流れ星', '走り星', '夜這星', '星流る', '星飛ぶ'],
    season: 'fall',
    id: 1969,
  },
  {
    name: '良夜',
    yomigana: 'りょうや',
    kyukana: 'りやうや',
    bodai: ['良宵', '佳宵'],
    season: 'fall',
    id: 1970,
  },
  {
    name: '林火忌',
    yomigana: 'りんかき',
    kyukana: 'りんくわき',
    season: 'fall',
    id: 1971,
    bodai: [],
  },
  {
    name: '林檎',
    yomigana: 'りんご',
    kyukana: '',
    bodai: ['紅玉', '国光', '林檎園'],
    season: 'fall',
    id: 1972,
  },
  {
    name: '竜胆',
    yomigana: 'りんどう',
    kyukana: 'りんだう',
    bodai: ['笹竜胆', '深山竜胆', '蔓竜胆'],
    season: 'fall',
    id: 1973,
  },
  {
    name: '檸檬',
    yomigana: 'れもん',
    kyukana: '',
    bodai: ['レモン'],
    season: 'fall',
    id: 1974,
  },
  {
    name: '六斎念仏',
    yomigana: 'ろくさいねんぶつ',
    kyukana: '',
    bodai: ['六斎', '六斎踊', '六斎太鼓'],
    season: 'fall',
    id: 1975,
  },
  {
    name: '六道参',
    yomigana: 'ろくどうまいり',
    kyukana: 'ろくだうまゐり',
    bodai: ['精霊迎', '迎鐘'],
    season: 'fall',
    id: 1976,
  },
  {
    name: '若煙草',
    yomigana: 'わかたばこ',
    kyukana: '',
    bodai: ['新煙草', '懸煙草', '煙草刈る', '煙草干す'],
    season: 'fall',
    id: 1977,
  },
  {
    name: '早稲',
    yomigana: 'わせ',
    kyukana: '',
    bodai: ['早稲の香', '早稲田', '早稲刈る'],
    season: 'fall',
    id: 1978,
  },
  {
    name: '棉',
    yomigana: 'わた',
    kyukana: '',
    bodai: ['棉の実', '棉実る', '棉吹く', '桃吹く'],
    season: 'fall',
    id: 1979,
  },
  {
    name: '綿取',
    yomigana: 'わたとり',
    kyukana: '',
    bodai: ['綿摘', '綿取る', '綿干す'],
    season: 'fall',
    id: 1980,
  },
  {
    name: '渡り鳥',
    yomigana: 'わたりどり',
    kyukana: '',
    bodai: ['鳥渡る', '小鳥来る', '鳥雲'],
    season: 'fall',
    id: 1981,
  },
  {
    name: '藁塚',
    yomigana: 'わらづか',
    kyukana: '',
    bodai: ['にほ'],
    season: 'fall',
    id: 1982,
  },
  {
    name: '吾亦紅',
    yomigana: 'われもこう',
    kyukana: 'われもかう',
    bodai: ['吾木香'],
    season: 'fall',
    id: 1983,
  },
]

export default fall
