import { Kigo } from '../types/kigo'

const newYear: Kigo[] = [
  {
    name: '小豆粥',
    yomigana: 'あづきがゆ',
    kyukana: '',
    bodai: ['十五日粥', '望の粥'],
    season: 'newYear',
    id: 2538,
  },
  {
    name: '伊勢海老',
    yomigana: 'いせえび',
    kyukana: '',
    bodai: ['鎌倉海老'],
    season: 'newYear',
    id: 2539,
  },
  {
    name: '五日',
    yomigana: 'いつか',
    kyukana: '',
    season: 'newYear',
    id: 2540,
    bodai: [],
  },
  {
    name: '寝積む',
    yomigana: 'いねつむ',
    kyukana: '',
    bodai: ['稲積む', '寝挙る'],
    season: 'newYear',
    id: 2541,
  },
  {
    name: '鷽替',
    yomigana: 'うそかえ',
    kyukana: 'うそかへ',
    bodai: ['鬼燻', '鬼すべ'],
    season: 'newYear',
    id: 2542,
  },
  {
    name: '謡初',
    yomigana: 'うたいぞめ',
    kyukana: 'うたひぞめ',
    bodai: ['初謡'],
    season: 'newYear',
    id: 2543,
  },
  {
    name: '歌会始',
    yomigana: 'うたかいはじめ',
    kyukana: '',
    bodai: ['歌御会始'],
    season: 'newYear',
    id: 2544,
  },
  {
    name: '馬騎初',
    yomigana: 'うまのりぞめ',
    kyukana: '',
    bodai: ['騎馬始', '馬場始', '初騎'],
    season: 'newYear',
    id: 2545,
  },
  {
    name: '恵方詣',
    yomigana: 'えほうまいり',
    kyukana: 'ゑはうまゐり',
    bodai: ['恵方', '吉方', '明きの方', '恵方道'],
    season: 'newYear',
    id: 2546,
  },
  {
    name: '会陽',
    yomigana: 'えよう',
    kyukana: 'ゑやう',
    bodai: ['西大寺参', '神木', '裸押し', '修正会'],
    season: 'newYear',
    id: 2547,
  },
  {
    name: 'えんぶり',
    yomigana: 'えんぶり',
    kyukana: '',
    bodai: ['えぶり', 'ながえんぶり', '御前えんぶり'],
    season: 'newYear',
    id: 2548,
  },
  {
    name: '大服',
    yomigana: 'おおぶく',
    kyukana: 'おほぶく',
    bodai: ['大福', '福茶', '大福茶'],
    season: 'newYear',
    id: 2549,
  },
  {
    name: '御行',
    yomigana: 'おぎょう',
    kyukana: 'おぎやう',
    bodai: ['御形', '五形'],
    season: 'newYear',
    id: 2550,
  },
  {
    name: '白朮詣',
    yomigana: 'おけらまいり',
    kyukana: 'をけらまゐり',
    bodai: ['白朮祭', '白朮火', '白朮縄', '火縄売', '祇園削掛の神事'],
    season: 'newYear',
    id: 2551,
  },
  {
    name: '御降り',
    yomigana: 'おさがり',
    kyukana: '',
    bodai: ['富正月'],
    season: 'newYear',
    id: 2552,
  },
  {
    name: '鬼打木',
    yomigana: 'おにうちぎ',
    kyukana: '',
    bodai: ['鬼木'],
    season: 'newYear',
    id: 2553,
  },
  {
    name: '女正月',
    yomigana: 'おんなしょがつ',
    kyukana: 'をんなしやうぐあつ',
    bodai: ['女正月'],
    season: 'newYear',
    id: 2554,
  },
  {
    name: '買初',
    yomigana: 'かいぞめ',
    kyukana: 'かひぞめ',
    bodai: ['初買'],
    season: 'newYear',
    id: 2555,
  },
  {
    name: '傀儡師',
    yomigana: 'かいらいし',
    kyukana: 'くわいらいし',
    bodai: ['傀儡', '夷廻し', '木傀廻し'],
    season: 'newYear',
    id: 2556,
  },
  {
    name: '鏡開',
    yomigana: 'かがみびらき',
    kyukana: '',
    bodai: ['鏡割'],
    season: 'newYear',
    id: 2557,
  },
  {
    name: '鏡餅',
    yomigana: 'かがみもち',
    kyukana: '',
    bodai: ['御鏡', '飾餅', '具足餅', '鎧餅'],
    season: 'newYear',
    id: 2558,
  },
  {
    name: '書初',
    yomigana: 'かきぞめ',
    kyukana: '',
    bodai: ['筆始', '試筆', '吉書'],
    season: 'newYear',
    id: 2559,
  },
  {
    name: '飾',
    yomigana: 'かざり',
    kyukana: '',
    bodai: ['お飾', '輪飾'],
    season: 'newYear',
    id: 2560,
  },
  {
    name: '飾臼',
    yomigana: 'かざりうす',
    kyukana: '',
    bodai: ['臼飾る'],
    season: 'newYear',
    id: 2561,
  },
  {
    name: '飾海老',
    yomigana: 'かざりえび',
    kyukana: '',
    bodai: ['海老飾る'],
    season: 'newYear',
    id: 2562,
  },
  {
    name: '飾納',
    yomigana: 'かざりおさめ',
    kyukana: 'かざりをさめ',
    bodai: ['飾取る', '注連取る'],
    season: 'newYear',
    id: 2563,
  },
  {
    name: '飾米',
    yomigana: 'かざりこめ',
    kyukana: '',
    bodai: ['米飾る'],
    season: 'newYear',
    id: 2564,
  },
  {
    name: '数の子',
    yomigana: 'かずのこ',
    kyukana: '',
    bodai: ['かどのこ'],
    season: 'newYear',
    id: 2565,
  },
  {
    name: '門松',
    yomigana: 'かどまつ',
    kyukana: '',
    bodai: ['松飾', '飾松', '竹飾', '飾竹'],
    season: 'newYear',
    id: 2566,
  },
  {
    name: 'かまくら',
    yomigana: 'かまくら',
    kyukana: '',
    season: 'newYear',
    id: 2567,
    bodai: [],
  },
  {
    name: '粥杖',
    yomigana: 'かゆづえ',
    kyukana: '',
    bodai: ['粥の木', '祝棒', '粥柱'],
    season: 'newYear',
    id: 2568,
  },
  {
    name: '歌留多',
    yomigana: 'かるた',
    kyukana: '',
    bodai: ['骨牌', '歌がるた', '花がるた', 'いろは歌留多', '歌留多会'],
    season: 'newYear',
    id: 2569,
  },
  {
    name: '賀状',
    yomigana: 'がじょう',
    kyukana: 'がじやう',
    bodai: ['年賀状', '年始状'],
    season: 'newYear',
    id: 2570,
  },
  {
    name: '元日',
    yomigana: 'がんじつ',
    kyukana: 'ぐわんじつ',
    bodai: ['お元日', '日の始め', '鶏日'],
    season: 'newYear',
    id: 2571,
  },
  {
    name: '元朝',
    yomigana: 'がんちょう',
    kyukana: 'ぐわんてう',
    bodai: ['元旦', '大旦', '鶏旦', '歳旦'],
    season: 'newYear',
    id: 2572,
  },
  {
    name: '着衣始',
    yomigana: 'きそはじめ',
    kyukana: '',
    season: 'newYear',
    id: 2573,
    bodai: [],
  },
  {
    name: '切山椒',
    yomigana: 'きりざんしょう',
    kyukana: 'きりざんせう',
    season: 'newYear',
    id: 2574,
    bodai: [],
  },
  {
    name: '御慶',
    yomigana: 'ぎょけい',
    kyukana: '',
    season: 'newYear',
    id: 2575,
    bodai: [],
  },
  {
    name: '喰積',
    yomigana: 'くいつみ',
    kyukana: 'くひつみ',
    bodai: ['重詰', '重詰料理', '組重', 'お節料理'],
    season: 'newYear',
    id: 2576,
  },
  {
    name: '国栖奏',
    yomigana: 'くずそう',
    kyukana: '',
    bodai: ['国栖舞', '国栖笛', '国栖歌', '国栖人', '国栖翁'],
    season: 'newYear',
    id: 2577,
  },
  {
    name: '蔵開',
    yomigana: 'くらびらき',
    kyukana: '',
    bodai: ['御蔵開'],
    season: 'newYear',
    id: 2578,
  },
  {
    name: '鍬始',
    yomigana: 'くわはじめ',
    kyukana: 'くははじめ',
    bodai: ['鋤始', '一鍬', '鍬入れ', '初田打'],
    season: 'newYear',
    id: 2579,
  },
  {
    name: '稽古始',
    yomigana: 'けいこはじめ',
    kyukana: '',
    bodai: ['初稽古'],
    season: 'newYear',
    id: 2580,
  },
  {
    name: '講書始',
    yomigana: 'こうしょはじめ',
    kyukana: 'かうしょはじめ',
    season: 'newYear',
    id: 2581,
    bodai: [],
  },
  {
    name: '小正月',
    yomigana: 'こしょうがつ',
    kyukana: 'こしやうぐわつ',
    bodai: ['十五日正月', '花正月', '望正月'],
    season: 'newYear',
    id: 2582,
  },
  {
    name: '去年',
    yomigana: 'こぞ',
    kyukana: '',
    bodai: ['去年', '古年', '旧年', '初昔', '宵の年'],
    season: 'newYear',
    id: 2583,
  },
  {
    name: '去年今年',
    yomigana: 'こぞことし',
    kyukana: '',
    season: 'newYear',
    id: 2584,
    bodai: [],
  },
  {
    name: '今年',
    yomigana: 'ことし',
    kyukana: '',
    bodai: ['今年', '当年', '若き年'],
    season: 'newYear',
    id: 2585,
  },
  {
    name: '独楽',
    yomigana: 'こま',
    kyukana: '',
    bodai: ['独楽廻し', '独楽遊び', '独楽打つ'],
    season: 'newYear',
    id: 2586,
  },
  {
    name: '小松引',
    yomigana: 'こまつひき',
    kyukana: '',
    bodai: ['初子の日', '子の日の遊び'],
    season: 'newYear',
    id: 2587,
  },
  {
    name: '御用始',
    yomigana: 'ごようはじめ',
    kyukana: '',
    season: 'newYear',
    id: 2588,
    bodai: [],
  },
  {
    name: '幸木',
    yomigana: 'さいわいぎ',
    kyukana: 'さいはひぎ',
    bodai: ['幸木'],
    season: 'newYear',
    id: 2589,
  },
  {
    name: '左義長',
    yomigana: 'さぎちょう',
    kyukana: 'さぎちやう',
    bodai: [
      '三毬杖',
      'どんど',
      'とんど',
      'どんど焚く',
      '飾焚く',
      '注連焚く',
      '吉書揚',
    ],
    season: 'newYear',
    id: 2590,
  },
  {
    name: '猿廻し',
    yomigana: 'さるまわし',
    kyukana: 'さるまはし',
    bodai: ['猿曳', '猿使ひ'],
    season: 'newYear',
    id: 2591,
  },
  {
    name: '三が日',
    yomigana: 'さんがにち',
    kyukana: '',
    season: 'newYear',
    id: 2592,
    bodai: [],
  },
  {
    name: '仕事始',
    yomigana: 'しごとはじめ',
    kyukana: '',
    bodai: ['事務始', '初仕事'],
    season: 'newYear',
    id: 2593,
  },
  {
    name: '獅子舞',
    yomigana: 'ししまい',
    kyukana: 'ししまひ',
    bodai: ['太神楽', '竃祓ひ', '獅子頭'],
    season: 'newYear',
    id: 2594,
  },
  {
    name: '歯朶',
    yomigana: 'しだ',
    kyukana: '',
    bodai: ['裏白', '山草'],
    season: 'newYear',
    id: 2595,
  },
  {
    name: '七福神詣',
    yomigana: 'しちふくじんまいり',
    kyukana: '',
    bodai: ['七福詣', '福神詣', '福神巡り', '福詣'],
    season: 'newYear',
    id: 2596,
  },
  {
    name: '四方拝',
    yomigana: 'しほうはい',
    kyukana: 'しはうはい',
    season: 'newYear',
    id: 2597,
    bodai: [],
  },
  {
    name: '注連飾',
    yomigana: 'しめかざり',
    kyukana: '',
    bodai: ['注連縄', '七五三縄', '年縄', '牛蒡注連'],
    season: 'newYear',
    id: 2598,
  },
  {
    name: '注連貰',
    yomigana: 'しめもらい',
    kyukana: 'しめもらひ',
    season: 'newYear',
    id: 2599,
    bodai: [],
  },
  {
    name: '淑気',
    yomigana: 'しゅくき',
    kyukana: '',
    season: 'newYear',
    id: 2600,
    bodai: [],
  },
  {
    name: '正月',
    yomigana: 'しょうがつ',
    kyukana: 'しやうぐわつ',
    bodai: ['お正月', '祝月', '元月'],
    season: 'newYear',
    id: 2601,
  },
  {
    name: '正月の凧',
    yomigana: 'しょうがつのたこ',
    kyukana: 'しやうぐあつのたこ',
    bodai: ['凧揚', '紙鳶'],
    season: 'newYear',
    id: 2602,
  },
  {
    name: '新年',
    yomigana: 'しんねん',
    kyukana: '',
    bodai: [
      '年新た',
      '新玉',
      '年始',
      '年立つ',
      '年明く',
      '年改まる',
      '年来る',
      '年迎ふ',
    ],
    season: 'newYear',
    id: 2603,
  },
  {
    name: '新年会',
    yomigana: 'しんねんかい',
    kyukana: 'しんねんくわい',
    bodai: ['新年宴会'],
    season: 'newYear',
    id: 2604,
  },
  {
    name: '十六むさし',
    yomigana: 'じゅうろくむさし',
    kyukana: '',
    season: 'newYear',
    id: 2605,
    bodai: [],
  },
  {
    name: '上元の日',
    yomigana: 'じょうげんのひ',
    kyukana: 'じやうげんのひ',
    bodai: ['上元', '上元会', '上元祭', '元宵節'],
    season: 'newYear',
    id: 2606,
  },
  {
    name: '人日',
    yomigana: 'じんじつ',
    kyukana: '',
    bodai: ['人の日', '霊辰', '人勝節', '元七'],
    season: 'newYear',
    id: 2607,
  },
  {
    name: '双六',
    yomigana: 'すごろく',
    kyukana: '',
    bodai: ['盤双六', '絵双六'],
    season: 'newYear',
    id: 2608,
  },
  {
    name: '成人の日',
    yomigana: 'せいじんのひ',
    kyukana: '',
    season: 'newYear',
    id: 2609,
    bodai: [],
  },
  {
    name: '雑煮',
    yomigana: 'ぞうに',
    kyukana: 'ざふに',
    bodai: ['雑煮祝ふ', '雑煮餅', '雑煮椀'],
    season: 'newYear',
    id: 2610,
  },
  {
    name: '田遊び',
    yomigana: 'たあそび',
    kyukana: '',
    season: 'newYear',
    id: 2611,
    bodai: [],
  },
  {
    name: '宝船',
    yomigana: 'たからぶね',
    kyukana: '',
    bodai: ['宝船敷く'],
    season: 'newYear',
    id: 2612,
  },
  {
    name: '田作',
    yomigana: 'たづくり',
    kyukana: '',
    bodai: ['ごまめ', '小殿原'],
    season: 'newYear',
    id: 2613,
  },
  {
    name: '玉せせり',
    yomigana: 'たませせり',
    kyukana: '',
    bodai: ['玉せり', '玉取祭', '玉競祭'],
    season: 'newYear',
    id: 2614,
  },
  {
    name: '橙飾る',
    yomigana: 'だいだいかざる',
    kyukana: '',
    season: 'newYear',
    id: 2615,
    bodai: [],
  },
  {
    name: 'ちやつきらこ',
    yomigana: 'ちやつきらこ',
    kyukana: '',
    bodai: ['左義長', '後祭'],
    season: 'newYear',
    id: 2616,
  },
  {
    name: '朝賀',
    yomigana: 'ちょうが',
    kyukana: 'てうが',
    bodai: ['朝賀', '参賀', '拝賀'],
    season: 'newYear',
    id: 2617,
  },
  {
    name: '帳綴',
    yomigana: 'ちょうとじ',
    kyukana: 'ちやうとぢ',
    bodai: ['帳書', '帳始', '帳祝'],
    season: 'newYear',
    id: 2618,
  },
  {
    name: '草石蚕',
    yomigana: 'ちよろぎ',
    kyukana: '',
    bodai: ['ちょうろぎ', 'ちょうろく'],
    season: 'newYear',
    id: 2619,
  },
  {
    name: '綱引',
    yomigana: 'つなひき',
    kyukana: '',
    bodai: ['綱曳'],
    season: 'newYear',
    id: 2620,
  },
  {
    name: '手毬',
    yomigana: 'てまり',
    kyukana: '',
    bodai: ['手鞠', '手毬つく', '手毬唄', '手毬子'],
    season: 'newYear',
    id: 2621,
  },
  {
    name: '出初',
    yomigana: 'でぞめ',
    kyukana: '',
    bodai: ['出初式', '消防出初式'],
    season: 'newYear',
    id: 2622,
  },
  {
    name: '投扇興',
    yomigana: 'とうせんきょう',
    kyukana: '',
    bodai: ['投扇'],
    season: 'newYear',
    id: 2623,
  },
  {
    name: '十日戎',
    yomigana: 'とおかえびす',
    kyukana: 'とをかえびす',
    bodai: ['初戎', '初恵比須', '宵戎', '戎祭', '戎笹', '福笹', '残り福'],
    season: 'newYear',
    id: 2624,
  },
  {
    name: '野老飾る',
    yomigana: 'ところかざる',
    kyukana: '',
    season: 'newYear',
    id: 2625,
    bodai: [],
  },
  {
    name: '年男',
    yomigana: 'としおとこ',
    kyukana: 'としをとこ',
    bodai: ['若男', '節男'],
    season: 'newYear',
    id: 2626,
  },
  {
    name: '年木',
    yomigana: 'としぎ',
    kyukana: '',
    bodai: ['若木', '節木', '祝木'],
    season: 'newYear',
    id: 2627,
  },
  {
    name: '年玉',
    yomigana: 'としだま',
    kyukana: '',
    bodai: ['お年玉'],
    season: 'newYear',
    id: 2628,
  },
  {
    name: '歳徳神',
    yomigana: 'としとくじん',
    kyukana: '',
    bodai: ['年神', '若年様', '正月様'],
    season: 'newYear',
    id: 2629,
  },
  {
    name: '屠蘇',
    yomigana: 'とそ',
    kyukana: '',
    bodai: ['屠蘇祝ふ', '屠蘇酒', '屠蘇袋'],
    season: 'newYear',
    id: 2630,
  },
  {
    name: '鳥総松',
    yomigana: 'とぶさまつ',
    kyukana: '',
    season: 'newYear',
    id: 2631,
    bodai: [],
  },
  {
    name: '鳥追',
    yomigana: 'とりおい',
    kyukana: 'とりおひ',
    season: 'newYear',
    id: 2632,
    bodai: [],
  },
  {
    name: '泣初',
    yomigana: 'なきぞめ',
    kyukana: '',
    bodai: ['初泣'],
    season: 'newYear',
    id: 2633,
  },
  {
    name: '薺',
    yomigana: 'なづな',
    kyukana: '',
    bodai: ['薺摘'],
    season: 'newYear',
    id: 2634,
  },
  {
    name: '薺打',
    yomigana: 'なづなうつ',
    kyukana: '',
    bodai: ['七種打つ', '七種はやす'],
    season: 'newYear',
    id: 2635,
  },
  {
    name: '七種',
    yomigana: 'ななくさ',
    kyukana: '',
    bodai: ['七草'],
    season: 'newYear',
    id: 2636,
  },
  {
    name: '七種粥',
    yomigana: 'ななくさがゆ',
    kyukana: '',
    bodai: ['七日粥', '薺粥'],
    season: 'newYear',
    id: 2637,
  },
  {
    name: '七草爪',
    yomigana: 'ななくさづめ',
    kyukana: '',
    bodai: ['薺爪', '七日爪'],
    season: 'newYear',
    id: 2638,
  },
  {
    name: '七日',
    yomigana: 'なぬか',
    kyukana: '',
    bodai: ['七日'],
    season: 'newYear',
    id: 2639,
  },
  {
    name: '七日正月',
    yomigana: 'なぬかしょうがつ',
    kyukana: 'なぬかしやうぐわつ',
    season: 'newYear',
    id: 2640,
    bodai: [],
  },
  {
    name: 'なまはげ',
    yomigana: 'なまはげ',
    kyukana: '',
    bodai: ['なもみ剥ぎ', 'あまみはぎ'],
    season: 'newYear',
    id: 2641,
  },
  {
    name: '成木責',
    yomigana: 'なりきぜめ',
    kyukana: '',
    bodai: ['木責', '果樹責', '木を囃す'],
    season: 'newYear',
    id: 2642,
  },
  {
    name: '新野の雪祭',
    yomigana: 'にいののゆきまつり',
    kyukana: '',
    bodai: ['雪祭', '田楽祭'],
    season: 'newYear',
    id: 2643,
  },
  {
    name: '繞道祭',
    yomigana: 'にょうどうさい',
    kyukana: 'ねうだうさい',
    season: 'newYear',
    id: 2644,
    bodai: [],
  },
  {
    name: '縫初',
    yomigana: 'ぬひぞめ',
    kyukana: 'ぬいぞめ',
    bodai: ['縫始', '初針', '針起し'],
    season: 'newYear',
    id: 2645,
  },
  {
    name: '寝正月',
    yomigana: 'ねしょうがつ',
    kyukana: 'ねしやうぐわつ',
    season: 'newYear',
    id: 2646,
    bodai: [],
  },
  {
    name: '子日草',
    yomigana: 'ねのひぐさ',
    kyukana: '',
    bodai: ['姫小松', '茶筅松', '子の日の松'],
    season: 'newYear',
    id: 2647,
  },
  {
    name: '年賀',
    yomigana: 'ねんが',
    kyukana: '',
    bodai: ['年始', '年礼', '廻礼', '年始廻り', '賀詞'],
    season: 'newYear',
    id: 2648,
  },
  {
    name: '年酒',
    yomigana: 'ねんしゅ',
    kyukana: '',
    bodai: ['年酒', '年始酒'],
    season: 'newYear',
    id: 2649,
  },
  {
    name: '能始',
    yomigana: 'のうはじめ',
    kyukana: '',
    bodai: ['初能'],
    season: 'newYear',
    id: 2650,
  },
  {
    name: '乗初',
    yomigana: 'のりぞめ',
    kyukana: '',
    bodai: ['初乗', '初電車', '初車', '船乗初', '初飛行'],
    season: 'newYear',
    id: 2651,
  },
  {
    name: '歯固',
    yomigana: 'はがため',
    kyukana: '',
    season: 'newYear',
    id: 2652,
    bodai: [],
  },
  {
    name: '掃初',
    yomigana: 'はきぞめ',
    kyukana: '',
    bodai: ['初帚', '初掃除'],
    season: 'newYear',
    id: 2653,
  },
  {
    name: '箱根駅伝',
    yomigana: 'はこねえきでん',
    kyukana: '',
    season: 'newYear',
    id: 2654,
    bodai: [],
  },
  {
    name: '羽子板',
    yomigana: 'はごいた',
    kyukana: '',
    bodai: ['胡鬼板', 'はご'],
    season: 'newYear',
    id: 2655,
  },
  {
    name: '機始',
    yomigana: 'はたはじめ',
    kyukana: '',
    bodai: ['織初', '初機'],
    season: 'newYear',
    id: 2656,
  },
  {
    name: '初茜',
    yomigana: 'はつあかね',
    kyukana: '',
    season: 'newYear',
    id: 2657,
    bodai: [],
  },
  {
    name: '初明り',
    yomigana: 'はつあかり',
    kyukana: '',
    bodai: ['初夜明'],
    season: 'newYear',
    id: 2658,
  },
  {
    name: '初商',
    yomigana: 'はつあきない',
    kyukana: 'はつあきなひ',
    bodai: ['商始', '売初'],
    season: 'newYear',
    id: 2659,
  },
  {
    name: '初浅間',
    yomigana: 'はつあさま',
    kyukana: '',
    season: 'newYear',
    id: 2660,
    bodai: [],
  },
  {
    name: '初伊勢',
    yomigana: 'はついせ',
    kyukana: '',
    bodai: ['初参宮'],
    season: 'newYear',
    id: 2661,
  },
  {
    name: '初市',
    yomigana: 'はついち',
    kyukana: '',
    bodai: ['市始', '初市場', '初立会', '初相場', '初糶'],
    season: 'newYear',
    id: 2662,
  },
  {
    name: '初卯',
    yomigana: 'はつう',
    kyukana: '',
    bodai: ['初卯詣', '卯の札', '卯杖', '卯槌'],
    season: 'newYear',
    id: 2663,
  },
  {
    name: '初鴬',
    yomigana: 'はつうぐいす',
    kyukana: 'はつうぐひす',
    season: 'newYear',
    id: 2664,
    bodai: [],
  },
  {
    name: '初閻魔',
    yomigana: 'はつえんま',
    kyukana: '',
    bodai: ['閻魔詣'],
    season: 'newYear',
    id: 2665,
  },
  {
    name: '初鏡',
    yomigana: 'はつかがみ',
    kyukana: '',
    bodai: ['初化粧'],
    season: 'newYear',
    id: 2666,
  },
  {
    name: '初篝',
    yomigana: 'はつかがり',
    kyukana: '',
    season: 'newYear',
    id: 2667,
    bodai: [],
  },
  {
    name: '初神楽',
    yomigana: 'はつかぐら',
    kyukana: '',
    bodai: ['神楽始'],
    season: 'newYear',
    id: 2668,
  },
  {
    name: '二十日正月',
    yomigana: 'はつかしょうがつ',
    kyukana: 'はつかしやうがつ',
    bodai: ['団子正月', '二十日団子', '骨正月', '頭正月'],
    season: 'newYear',
    id: 2669,
  },
  {
    name: '初風',
    yomigana: 'はつかぜ',
    kyukana: '',
    bodai: ['春の初風', '初松籟'],
    season: 'newYear',
    id: 2670,
  },
  {
    name: '初竃',
    yomigana: 'はつかまど',
    kyukana: '',
    bodai: ['焚初'],
    season: 'newYear',
    id: 2671,
  },
  {
    name: '初観音',
    yomigana: 'はつかんのん',
    kyukana: 'はつくわんおん',
    season: 'newYear',
    id: 2672,
    bodai: [],
  },
  {
    name: '初霞',
    yomigana: 'はつがすみ',
    kyukana: '',
    bodai: ['新霞'],
    season: 'newYear',
    id: 2673,
  },
  {
    name: '初釜',
    yomigana: 'はつがま',
    kyukana: '',
    bodai: ['初茶湯', '初点前'],
    season: 'newYear',
    id: 2674,
  },
  {
    name: '初髪',
    yomigana: 'はつがみ',
    kyukana: '',
    bodai: ['初結', '結ひ初', '梳初'],
    season: 'newYear',
    id: 2675,
  },
  {
    name: '初鴉',
    yomigana: 'はつがらす',
    kyukana: '',
    season: 'newYear',
    id: 2676,
    bodai: [],
  },
  {
    name: '初句会',
    yomigana: 'はつくかい',
    kyukana: 'はつくくわい',
    bodai: ['新年句会'],
    season: 'newYear',
    id: 2677,
  },
  {
    name: '初景色',
    yomigana: 'はつげしき',
    kyukana: '',
    season: 'newYear',
    id: 2678,
    bodai: [],
  },
  {
    name: '初声',
    yomigana: 'はつこえ',
    kyukana: 'はつこゑ',
    season: 'newYear',
    id: 2679,
    bodai: [],
  },
  {
    name: '初金毘羅',
    yomigana: 'はつこんぴら',
    kyukana: '',
    bodai: ['初金刀比羅', '初十日'],
    season: 'newYear',
    id: 2680,
  },
  {
    name: '初東風',
    yomigana: 'はつごち',
    kyukana: '',
    bodai: ['節東風'],
    season: 'newYear',
    id: 2681,
  },
  {
    name: '初暦',
    yomigana: 'はつごよみ',
    kyukana: '',
    bodai: ['新暦'],
    season: 'newYear',
    id: 2682,
  },
  {
    name: '初勤行',
    yomigana: 'はつごんぎょう',
    kyukana: 'はつごんぎゃう',
    bodai: ['初鐘', '初読経', '初燈明', '初燈'],
    season: 'newYear',
    id: 2683,
  },
  {
    name: '初東雲',
    yomigana: 'はつしののめ',
    kyukana: '',
    bodai: ['初曙'],
    season: 'newYear',
    id: 2684,
  },
  {
    name: '初芝居',
    yomigana: 'はつしばい',
    kyukana: 'はつしばゐ',
    bodai: ['初春狂言', '春芝居', '初曽我', '二の替'],
    season: 'newYear',
    id: 2685,
  },
  {
    name: '初写真',
    yomigana: 'はつしゃしん',
    kyukana: '',
    bodai: ['初写し'],
    season: 'newYear',
    id: 2686,
  },
  {
    name: '初雀',
    yomigana: 'はつすずめ',
    kyukana: '',
    season: 'newYear',
    id: 2687,
    bodai: [],
  },
  {
    name: '初硯',
    yomigana: 'はつすずり',
    kyukana: '',
    season: 'newYear',
    id: 2688,
    bodai: [],
  },
  {
    name: '初刷',
    yomigana: 'はつずり',
    kyukana: '',
    bodai: ['刷初', '初新聞'],
    season: 'newYear',
    id: 2689,
  },
  {
    name: '初染',
    yomigana: 'はつぞめ',
    kyukana: '',
    bodai: ['染始'],
    season: 'newYear',
    id: 2690,
  },
  {
    name: '初空',
    yomigana: 'はつぞら',
    kyukana: '',
    bodai: ['初御空'],
    season: 'newYear',
    id: 2691,
  },
  {
    name: '初旅',
    yomigana: 'はつたび',
    kyukana: '',
    bodai: ['旅始', '旅行始'],
    season: 'newYear',
    id: 2692,
  },
  {
    name: '初大師',
    yomigana: 'はつだいし',
    kyukana: '',
    bodai: ['初弘法'],
    season: 'newYear',
    id: 2693,
  },
  {
    name: '初便り',
    yomigana: 'はつだより',
    kyukana: '',
    bodai: ['初郵便'],
    season: 'newYear',
    id: 2694,
  },
  {
    name: '初筑波',
    yomigana: 'はつつくば',
    kyukana: '',
    season: 'newYear',
    id: 2695,
    bodai: [],
  },
  {
    name: '初鼓',
    yomigana: 'はつつづみ',
    kyukana: '',
    bodai: ['鼓始'],
    season: 'newYear',
    id: 2696,
  },
  {
    name: '初手水',
    yomigana: 'はつてうづ',
    kyukana: '',
    season: 'newYear',
    id: 2697,
    bodai: [],
  },
  {
    name: '初天神',
    yomigana: 'はつてんじん',
    kyukana: '',
    bodai: ['宵天神', '残り天神', '天神花', '天神旗'],
    season: 'newYear',
    id: 2698,
  },
  {
    name: '初電話',
    yomigana: 'はつでんわ',
    kyukana: '',
    season: 'newYear',
    id: 2699,
    bodai: [],
  },
  {
    name: '初寅',
    yomigana: 'はつとら',
    kyukana: '',
    season: 'newYear',
    id: 2700,
    bodai: [],
  },
  {
    name: '初鶏',
    yomigana: 'はつどり',
    kyukana: '',
    season: 'newYear',
    id: 2701,
    bodai: [],
  },
  {
    name: '初凪',
    yomigana: 'はつなぎ',
    kyukana: '',
    season: 'newYear',
    id: 2702,
    bodai: [],
  },
  {
    name: '初荷',
    yomigana: 'はつに',
    kyukana: '',
    bodai: ['初荷舟', '初荷馬', '飾馬'],
    season: 'newYear',
    id: 2703,
  },
  {
    name: '初日記',
    yomigana: 'はつにっき',
    kyukana: '',
    bodai: ['日記始'],
    season: 'newYear',
    id: 2704,
  },
  {
    name: '初音売',
    yomigana: 'はつねうり',
    kyukana: '',
    bodai: ['初音笛'],
    season: 'newYear',
    id: 2705,
  },
  {
    name: '初鳩',
    yomigana: 'はつはと',
    kyukana: '',
    season: 'newYear',
    id: 2706,
    bodai: [],
  },
  {
    name: '初春',
    yomigana: 'はつはる',
    kyukana: '',
    bodai: ['新春', '明の春', '今朝の春', '千代の春'],
    season: 'newYear',
    id: 2707,
  },
  {
    name: '初場所',
    yomigana: 'はつばしょ',
    kyukana: '',
    bodai: ['一月場所', '正月場所'],
    season: 'newYear',
    id: 2708,
  },
  {
    name: '初晴',
    yomigana: 'はつばれ',
    kyukana: '',
    season: 'newYear',
    id: 2709,
    bodai: [],
  },
  {
    name: '初日',
    yomigana: 'はつひ',
    kyukana: '',
    bodai: ['初陽', '初旭', '初日の出', '初日影'],
    season: 'newYear',
    id: 2710,
  },
  {
    name: '初比叡',
    yomigana: 'はつひえい',
    kyukana: '',
    season: 'newYear',
    id: 2711,
    bodai: [],
  },
  {
    name: '初富士',
    yomigana: 'はつふじ',
    kyukana: '',
    season: 'newYear',
    id: 2712,
    bodai: [],
  },
  {
    name: '初不動',
    yomigana: 'はつふどう',
    kyukana: '',
    season: 'newYear',
    id: 2713,
    bodai: [],
  },
  {
    name: '初弁天',
    yomigana: 'はつべんてん',
    kyukana: '',
    bodai: ['初巳'],
    season: 'newYear',
    id: 2714,
  },
  {
    name: '初弥撒',
    yomigana: 'はつみさ',
    kyukana: '',
    bodai: ['初ミサ'],
    season: 'newYear',
    id: 2715,
  },
  {
    name: '初詣',
    yomigana: 'はつもうで',
    kyukana: 'はつまうで',
    bodai: ['初参', '初社', '初御籤'],
    season: 'newYear',
    id: 2716,
  },
  {
    name: '初薬師',
    yomigana: 'はつやくし',
    kyukana: '',
    season: 'newYear',
    id: 2717,
    bodai: [],
  },
  {
    name: '初湯',
    yomigana: 'はつゆ',
    kyukana: '',
    bodai: ['初風呂', '湯殿始'],
    season: 'newYear',
    id: 2718,
  },
  {
    name: '初夢',
    yomigana: 'はつゆめ',
    kyukana: '',
    bodai: ['貘枕', '初寝覚'],
    season: 'newYear',
    id: 2719,
  },
  {
    name: '初漁',
    yomigana: 'はつりょう',
    kyukana: 'はつれふ',
    bodai: ['漁始', '初網'],
    season: 'newYear',
    id: 2720,
  },
  {
    name: '花びら餅',
    yomigana: 'はなびらもち',
    kyukana: '',
    bodai: ['菱葩餅、菱はなびら'],
    season: 'newYear',
    id: 2721,
  },
  {
    name: '羽子つき',
    yomigana: 'はねつき',
    kyukana: '',
    bodai: ['羽子', '追羽子', '揚羽子', '遣羽子'],
    season: 'newYear',
    id: 2722,
  },
  {
    name: '破魔弓',
    yomigana: 'はまゆみ',
    kyukana: '',
    bodai: ['破魔矢'],
    season: 'newYear',
    id: 2723,
  },
  {
    name: '春着',
    yomigana: 'はるぎ',
    kyukana: '',
    bodai: ['正月小袖', '春襲'],
    season: 'newYear',
    id: 2724,
  },
  {
    name: '春駒',
    yomigana: 'はるこま',
    kyukana: '',
    bodai: ['春駒舞', '春駒万歳'],
    season: 'newYear',
    id: 2725,
  },
  {
    name: '弾初',
    yomigana: 'ひきぞめ',
    kyukana: '',
    bodai: ['初弾', '琴始'],
    season: 'newYear',
    id: 2726,
  },
  {
    name: 'ひめ始',
    yomigana: 'ひめはじめ',
    kyukana: '',
    bodai: ['姫始', '密事始（ひめはじめ）'],
    season: 'newYear',
    id: 2727,
  },
  {
    name: '吹初',
    yomigana: 'ふきぞめ',
    kyukana: '',
    bodai: ['籟初', '吹始'],
    season: 'newYear',
    id: 2728,
  },
  {
    name: '福寿草',
    yomigana: 'ふくじゅそう',
    kyukana: 'ふくじゅさう',
    bodai: ['元日草'],
    season: 'newYear',
    id: 2729,
  },
  {
    name: '福達磨',
    yomigana: 'ふくだるま',
    kyukana: '',
    bodai: ['達磨市'],
    season: 'newYear',
    id: 2730,
  },
  {
    name: '福引',
    yomigana: 'ふくびき',
    kyukana: '',
    bodai: ['宝引'],
    season: 'newYear',
    id: 2731,
  },
  {
    name: '福袋',
    yomigana: 'ふくぶくろ',
    kyukana: '',
    season: 'newYear',
    id: 2732,
    bodai: [],
  },
  {
    name: '福沸',
    yomigana: 'ふくわかし',
    kyukana: '',
    bodai: ['福鍋'],
    season: 'newYear',
    id: 2733,
  },
  {
    name: '福藁',
    yomigana: 'ふくわら',
    kyukana: '',
    bodai: ['福藁敷く', 'ふくさ藁'],
    season: 'newYear',
    id: 2734,
  },
  {
    name: '福笑ひ',
    yomigana: 'ふくわらい',
    kyukana: 'ふくわらひ',
    season: 'newYear',
    id: 2735,
    bodai: [],
  },
  {
    name: '二日',
    yomigana: 'ふつか',
    kyukana: '',
    season: 'newYear',
    id: 2736,
    bodai: [],
  },
  {
    name: '太箸',
    yomigana: 'ふとばし',
    kyukana: '',
    bodai: ['祝箸', '柳箸', '箸紙', '雑煮箸'],
    season: 'newYear',
    id: 2737,
  },
  {
    name: '蓬莱',
    yomigana: 'ほうらい',
    kyukana: '',
    bodai: ['掛蓬莱', '蓬莱飾'],
    season: 'newYear',
    id: 2738,
  },
  {
    name: '宝恵篭',
    yomigana: 'ほえかご',
    kyukana: 'ほゑかご',
    bodai: ['宝恵駕', '戎篭'],
    season: 'newYear',
    id: 2739,
  },
  {
    name: '仏の座',
    yomigana: 'ほとけのざ',
    kyukana: '',
    bodai: ['田平子'],
    season: 'newYear',
    id: 2740,
  },
  {
    name: '穂俵飾る',
    yomigana: 'ほんだはらかざる',
    kyukana: '',
    season: 'newYear',
    id: 2741,
    bodai: [],
  },
  {
    name: 'ぼんでん',
    yomigana: 'ぼんでん',
    kyukana: '',
    bodai: ['梵天'],
    season: 'newYear',
    id: 2742,
  },
  {
    name: 'ぽっぺん',
    yomigana: 'ぽっぺん',
    kyukana: '',
    bodai: ['ぽこんぽこん'],
    season: 'newYear',
    id: 2743,
  },
  {
    name: '舞初',
    yomigana: 'まいぞめ',
    kyukana: 'まひぞめ',
    bodai: ['仕舞始'],
    season: 'newYear',
    id: 2744,
  },
  {
    name: '松納',
    yomigana: 'まつおさめ',
    kyukana: 'まつをさめ',
    bodai: ['松取る', '門松取る'],
    season: 'newYear',
    id: 2745,
  },
  {
    name: '松過ぎ',
    yomigana: 'まつすぎ',
    kyukana: '',
    bodai: ['松明け', '注連明'],
    season: 'newYear',
    id: 2746,
  },
  {
    name: '松の内',
    yomigana: 'まつのうち',
    kyukana: '',
    bodai: ['松七日', '注連の内'],
    season: 'newYear',
    id: 2747,
  },
  {
    name: '俎始',
    yomigana: 'まないたはじめ',
    kyukana: '',
    bodai: ['包丁始'],
    season: 'newYear',
    id: 2748,
  },
  {
    name: '鞠始',
    yomigana: 'まりはじめ',
    kyukana: '',
    bodai: ['蹴鞠始'],
    season: 'newYear',
    id: 2749,
  },
  {
    name: '万歳',
    yomigana: 'まんざい',
    kyukana: '',
    bodai: ['三河万歳', '大和万歳'],
    season: 'newYear',
    id: 2750,
  },
  {
    name: '三日',
    yomigana: 'みっか',
    kyukana: '',
    season: 'newYear',
    id: 2751,
    bodai: [],
  },
  {
    name: '睦月',
    yomigana: 'むつき',
    kyukana: '',
    bodai: ['むつみ月', 'むつび月'],
    season: 'newYear',
    id: 2752,
  },
  {
    name: '土竜打',
    yomigana: 'もぐらうち',
    kyukana: '',
    bodai: ['土竜追', '海鼠曳'],
    season: 'newYear',
    id: 2753,
  },
  {
    name: '餅花',
    yomigana: 'もちばな',
    kyukana: '',
    bodai: ['繭玉', '稲穂', '団子花'],
    season: 'newYear',
    id: 2754,
  },
  {
    name: '薮入',
    yomigana: 'やぶいり',
    kyukana: '',
    bodai: ['里下り', '宿下り'],
    season: 'newYear',
    id: 2755,
  },
  {
    name: '山始',
    yomigana: 'やまはじめ',
    kyukana: '',
    bodai: [
      '初山',
      '初山入り',
      '山入り',
      '斧始',
      '手斧始',
      '若山踏み',
      '木伐り初',
    ],
    season: 'newYear',
    id: 2756,
  },
  {
    name: '楪',
    yomigana: 'ゆづりは',
    kyukana: '',
    bodai: ['弓弦葉', '親子草'],
    season: 'newYear',
    id: 2757,
  },
  {
    name: '弓始',
    yomigana: 'ゆみはじめ',
    kyukana: '',
    bodai: ['初弓', '的始', '弓矢始', '射初'],
    season: 'newYear',
    id: 2758,
  },
  {
    name: '四日',
    yomigana: 'よっか',
    kyukana: '',
    season: 'newYear',
    id: 2759,
    bodai: [],
  },
  {
    name: '読初',
    yomigana: 'よみぞめ',
    kyukana: '',
    bodai: ['読書始'],
    season: 'newYear',
    id: 2760,
  },
  {
    name: '嫁が君',
    yomigana: 'よめがきみ',
    kyukana: '',
    season: 'newYear',
    id: 2761,
    bodai: [],
  },
  {
    name: '礼受',
    yomigana: 'れいうけ',
    kyukana: '',
    bodai: ['礼者受', '名刺受'],
    season: 'newYear',
    id: 2762,
  },
  {
    name: '礼者',
    yomigana: 'れいじゃ',
    kyukana: '',
    bodai: ['門礼', '門礼者', '賀客', '年賀客', '女礼者'],
    season: 'newYear',
    id: 2763,
  },
  {
    name: '若菜',
    yomigana: 'わかな',
    kyukana: '',
    bodai: ['若菜摘', '粥草', '七草粥'],
    season: 'newYear',
    id: 2764,
  },
  {
    name: '若菜野',
    yomigana: 'わかなの',
    kyukana: '',
    season: 'newYear',
    id: 2765,
    bodai: [],
  },
  {
    name: '若水',
    yomigana: 'わかみず',
    kyukana: 'わかみづ',
    bodai: ['初水', '福水', '若井', '井華水', '若潮', '若潮迎へ'],
    season: 'newYear',
    id: 2766,
  },
  {
    name: '笑初',
    yomigana: 'わらいぞめ',
    kyukana: 'わらひぞめ',
    bodai: ['初笑'],
    season: 'newYear',
    id: 2767,
  },
  {
    name: '藁盒子',
    yomigana: 'わらごうし',
    kyukana: 'わらがふし',
    bodai: ['幸篭', 'ヤス'],
    season: 'newYear',
    id: 2768,
  },
]

export default newYear
