import { Kigo } from '../types/kigo'

const winter: Kigo[] = [
  {
    name: 'アイスホッケー',
    yomigana: 'あいすほっけー',
    kyukana: '',
    season: 'winter',
    id: 1984,
    bodai: [],
  },
  {
    name: '青木の実',
    yomigana: 'あおきのみ',
    kyukana: 'あをきのみ',
    season: 'winter',
    id: 1985,
    bodai: [],
  },
  {
    name: '皸',
    yomigana: 'あかぎれ',
    kyukana: '',
    bodai: ['あかがり'],
    season: 'winter',
    id: 1986,
  },
  {
    name: '網代',
    yomigana: 'あじろ',
    kyukana: '',
    bodai: ['網代木', '網代床', '網代守'],
    season: 'winter',
    id: 1987,
  },
  {
    name: '熱燗',
    yomigana: 'あつかん',
    kyukana: '',
    bodai: ['燗酒'],
    season: 'winter',
    id: 1988,
  },
  {
    name: '厚司',
    yomigana: 'あつし',
    kyukana: '',
    season: 'winter',
    id: 1989,
    bodai: [],
  },
  {
    name: '神在祭',
    yomigana: 'あみありまつり',
    kyukana: '',
    bodai: ['神在', '神集ひ'],
    season: 'winter',
    id: 1990,
  },
  {
    name: '霰',
    yomigana: 'あられ',
    kyukana: '',
    bodai: ['玉霰', '夕霰', '初霰'],
    season: 'winter',
    id: 1991,
  },
  {
    name: '亜浪忌',
    yomigana: 'あろうき',
    kyukana: 'あらうき',
    season: 'winter',
    id: 1992,
    bodai: [],
  },
  {
    name: 'アロエの花',
    yomigana: 'あろえのはな',
    kyukana: '',
    season: 'winter',
    id: 1993,
    bodai: [],
  },
  {
    name: '行火',
    yomigana: 'あんか',
    kyukana: 'あんくわ',
    season: 'winter',
    id: 1994,
    bodai: [],
  },
  {
    name: '鮟鱇',
    yomigana: 'あんこう',
    kyukana: 'あんかう',
    season: 'winter',
    id: 1995,
    bodai: [],
  },
  {
    name: '鮟鱇鍋',
    yomigana: 'あんこうなべ',
    kyukana: 'あんかうなべ',
    season: 'winter',
    id: 1996,
    bodai: [],
  },
  {
    name: '藺植う',
    yomigana: 'いうう',
    kyukana: 'ゐうう',
    season: 'winter',
    id: 1997,
    bodai: [],
  },
  {
    name: '息白し',
    yomigana: 'いきしろし',
    kyukana: '',
    bodai: ['白息'],
    season: 'winter',
    id: 1998,
  },
  {
    name: '池普請',
    yomigana: 'いけぶしん',
    kyukana: '',
    bodai: ['川普請'],
    season: 'winter',
    id: 1999,
  },
  {
    name: '魦',
    yomigana: 'いさぎ',
    kyukana: '',
    bodai: ['いさぎ舟', 'いさぎ漁'],
    season: 'winter',
    id: 2000,
  },
  {
    name: '鼬',
    yomigana: 'いたち',
    kyukana: '',
    season: 'winter',
    id: 2001,
    bodai: [],
  },
  {
    name: '鼬罠',
    yomigana: 'いたちわな',
    kyukana: '',
    season: 'winter',
    id: 2002,
    bodai: [],
  },
  {
    name: '一月',
    yomigana: 'いちがつ',
    kyukana: 'いちぐわつ',
    season: 'winter',
    id: 2003,
    bodai: [],
  },
  {
    name: '銀杏落葉',
    yomigana: 'いちょうおちば',
    kyukana: 'いてふおちば',
    season: 'winter',
    id: 2004,
    bodai: [],
  },
  {
    name: '一葉忌',
    yomigana: 'いちようき',
    kyukana: 'いちえふき',
    season: 'winter',
    id: 2005,
    bodai: [],
  },
  {
    name: '一茶忌',
    yomigana: 'いっさき',
    kyukana: '',
    season: 'winter',
    id: 2006,
    bodai: [],
  },
  {
    name: '一碧楼忌',
    yomigana: 'いっぺきろうき',
    kyukana: '',
    season: 'winter',
    id: 2007,
    bodai: [],
  },
  {
    name: '凍滝',
    yomigana: 'いてたき',
    kyukana: '',
    bodai: ['冬滝', '滝氷る'],
    season: 'winter',
    id: 2008,
  },
  {
    name: '凍土',
    yomigana: 'いてつち',
    kyukana: '',
    bodai: ['凍上', '大地凍つ'],
    season: 'winter',
    id: 2009,
  },
  {
    name: '亥の子',
    yomigana: 'いのこ',
    kyukana: 'ゐのこ',
    bodai: ['玄猪', '亥の子餅'],
    season: 'winter',
    id: 2010,
  },
  {
    name: '囲炉裏',
    yomigana: 'いろり',
    kyukana: '',
    bodai: ['炉', '炉火', '炉明り', '炉話'],
    season: 'winter',
    id: 2011,
  },
  {
    name: '兎',
    yomigana: 'うさぎ',
    kyukana: '',
    bodai: ['兎汁'],
    season: 'winter',
    id: 2012,
  },
  {
    name: '兎狩',
    yomigana: 'うさぎがり',
    kyukana: '',
    bodai: ['兎罠', '兎網'],
    season: 'winter',
    id: 2013,
  },
  {
    name: '潤目鰯',
    yomigana: 'うるめいわし',
    kyukana: '',
    bodai: ['うるめ'],
    season: 'winter',
    id: 2014,
  },
  {
    name: '恵比寿講',
    yomigana: 'えびすこう',
    kyukana: '',
    bodai: ['夷講', '蛭子市', '夷切'],
    season: 'winter',
    id: 2015,
  },
  {
    name: '襟巻',
    yomigana: 'えりまき',
    kyukana: '',
    bodai: ['首巻', 'マフラー'],
    season: 'winter',
    id: 2016,
  },
  {
    name: '狼',
    yomigana: 'おおかみ',
    kyukana: 'おほかみ',
    season: 'winter',
    id: 2017,
    bodai: [],
  },
  {
    name: '御火焚',
    yomigana: 'おおたき',
    kyukana: 'おほたき',
    bodai: ['御火焼'],
    season: 'winter',
    id: 2018,
  },
  {
    name: '大晦日',
    yomigana: 'おおみそか',
    kyukana: 'おほみそか',
    bodai: ['大年', '大つごもり', '大三十日'],
    season: 'winter',
    id: 2019,
  },
  {
    name: '奥三河花祭',
    yomigana: 'おくみかわはなまつり',
    kyukana: '',
    bodai: ['花祭', '花神楽', '榊鬼'],
    season: 'winter',
    id: 2020,
  },
  {
    name: 'おくんち',
    yomigana: 'おくんち',
    kyukana: '',
    bodai: ['竜踊', 'くんち', 'おくにち'],
    season: 'winter',
    id: 2021,
  },
  {
    name: '鴛鴦',
    yomigana: 'おしどり',
    kyukana: 'をしどり',
    bodai: ['をし'],
    season: 'winter',
    id: 2022,
  },
  {
    name: '落葉',
    yomigana: 'おちば',
    kyukana: '',
    bodai: ['落葉', '落葉焚', '落葉掻', '落葉篭', '落葉期'],
    season: 'winter',
    id: 2023,
  },
  {
    name: '乙字忌',
    yomigana: 'おつじき',
    kyukana: '',
    bodai: ['寒雷忌　二十日忌'],
    season: 'winter',
    id: 2024,
  },
  {
    name: 'おでん',
    yomigana: 'おでん',
    kyukana: '',
    bodai: ['関東煮（かんとうだき）'],
    season: 'winter',
    id: 2025,
  },
  {
    name: '御取越',
    yomigana: 'おとりこし',
    kyukana: '',
    bodai: ['引上会'],
    season: 'winter',
    id: 2026,
  },
  {
    name: '鬼柚子',
    yomigana: 'おにゆず',
    kyukana: '',
    season: 'winter',
    id: 2027,
    bodai: [],
  },
  {
    name: '帯解',
    yomigana: 'おびとき',
    kyukana: '',
    bodai: ['紐解'],
    season: 'winter',
    id: 2028,
  },
  {
    name: '御神渡',
    yomigana: 'おみわたり',
    kyukana: '',
    bodai: ['御渡り'],
    season: 'winter',
    id: 2029,
  },
  {
    name: '御命講',
    yomigana: 'おめいこう',
    kyukana: '',
    bodai: ['御会式', '日蓮忌', '万燈', '御命講花'],
    season: 'winter',
    id: 2030,
  },
  {
    name: '温室',
    yomigana: 'おんしつ',
    kyukana: '',
    bodai: ['フレーム', '温床', 'ビニールハウス'],
    season: 'winter',
    id: 2031,
  },
  {
    name: '開戦日',
    yomigana: 'かいせんび',
    kyukana: '',
    bodai: ['十二月八日'],
    season: 'winter',
    id: 2032,
  },
  {
    name: '鳰',
    yomigana: 'かいつぶり',
    kyukana: '',
    bodai: ['にほ', 'にほどり'],
    season: 'winter',
    id: 2033,
  },
  {
    name: '懐炉',
    yomigana: 'かいろ',
    kyukana: 'くわいろ',
    bodai: ['温石'],
    season: 'winter',
    id: 2034,
  },
  {
    name: '帰り花',
    yomigana: 'かえりばな',
    kyukana: 'かへりばな',
    bodai: ['返り花', '忘れ花', '狂ひ花', '狂ひ咲き'],
    season: 'winter',
    id: 2035,
  },
  {
    name: '顔見世',
    yomigana: 'かおみせ',
    kyukana: 'かほみせ',
    bodai: ['顔見勢'],
    season: 'winter',
    id: 2036,
  },
  {
    name: '牡蠣',
    yomigana: 'かき',
    kyukana: '',
    bodai: ['真牡蠣', '酢牡蠣', '牡蠣飯'],
    season: 'winter',
    id: 2037,
  },
  {
    name: '柿落葉',
    yomigana: 'かきおちば',
    kyukana: '',
    season: 'winter',
    id: 2038,
    bodai: [],
  },
  {
    name: '牡蛎船',
    yomigana: 'かきぶね',
    kyukana: '',
    bodai: ['牡蛎料理', '牡蛎鍋'],
    season: 'winter',
    id: 2039,
  },
  {
    name: '牡蠣剥く',
    yomigana: 'かきむく',
    kyukana: '',
    bodai: ['牡蠣割る', '牡蠣割女'],
    season: 'winter',
    id: 2040,
  },
  {
    name: '杜父魚',
    yomigana: 'かくぶつ',
    kyukana: '',
    bodai: ['杜夫魚', '霰魚', '杜父魚', 'あられがこ'],
    season: 'winter',
    id: 2041,
  },
  {
    name: '角巻',
    yomigana: 'かくまき',
    kyukana: '',
    season: 'winter',
    id: 2042,
    bodai: [],
  },
  {
    name: '神楽',
    yomigana: 'かぐら',
    kyukana: '',
    bodai: ['御神楽', '神楽歌', '夜神楽', '神遊び', '庭燎'],
    season: 'winter',
    id: 2043,
  },
  {
    name: '重ね着',
    yomigana: 'かさねぎ',
    kyukana: '',
    bodai: ['厚着'],
    season: 'winter',
    id: 2044,
  },
  {
    name: '風花',
    yomigana: 'かざはな',
    kyukana: '',
    bodai: ['かぜはな', 'かざばな'],
    season: 'winter',
    id: 2045,
  },
  {
    name: '風除',
    yomigana: 'かざよけ',
    kyukana: '',
    bodai: ['風垣', '風囲'],
    season: 'winter',
    id: 2046,
  },
  {
    name: '飾売',
    yomigana: 'かざりうり',
    kyukana: '',
    season: 'winter',
    id: 2047,
    bodai: [],
  },
  {
    name: '火事',
    yomigana: 'かじ',
    kyukana: 'くわじ',
    bodai: ['大火', '小火', '類焼', '半焼', '近火', '遠火事', '火事見舞'],
    season: 'winter',
    id: 2048,
  },
  {
    name: '悴む',
    yomigana: 'かじかむ',
    kyukana: '',
    season: 'winter',
    id: 2049,
    bodai: [],
  },
  {
    name: '春日万燈篭',
    yomigana: 'かすがまんとうろう',
    kyukana: '',
    bodai: ['春日の万燈'],
    season: 'winter',
    id: 2050,
  },
  {
    name: '粕汁',
    yomigana: 'かすじる',
    kyukana: '',
    bodai: ['酒の粕'],
    season: 'winter',
    id: 2051,
  },
  {
    name: '春日若宮おん祭',
    yomigana: 'かずがわかみやおんまつり',
    kyukana: '',
    season: 'winter',
    id: 2052,
    bodai: [],
  },
  {
    name: '風邪',
    yomigana: 'かぜ',
    kyukana: '',
    bodai: [
      '感冒',
      '流行風邪',
      '流感',
      '風邪声',
      '鼻風邪',
      '風邪心地',
      '風邪薬',
      '風邪の神',
    ],
    season: 'winter',
    id: 2053,
  },
  {
    name: '数え日',
    yomigana: 'かぞえび',
    kyukana: 'かぞへび',
    bodai: ['数へ日'],
    season: 'winter',
    id: 2054,
  },
  {
    name: '門松立つ',
    yomigana: 'かどまつたつ',
    kyukana: '',
    bodai: ['松飾る'],
    season: 'winter',
    id: 2055,
  },
  {
    name: '蕪',
    yomigana: 'かぶら',
    kyukana: '',
    bodai: ['蕪', 'かぶらな', 'すずな', '赤蕪'],
    season: 'winter',
    id: 2056,
  },
  {
    name: '蕪汁',
    yomigana: 'かぶらじる',
    kyukana: '',
    season: 'winter',
    id: 2057,
    bodai: [],
  },
  {
    name: '鎌鼬',
    yomigana: 'かまいたち',
    kyukana: '',
    bodai: ['鎌風'],
    season: 'winter',
    id: 2058,
  },
  {
    name: '竃猫',
    yomigana: 'かまどねこ',
    kyukana: '',
    bodai: ['へつつひ猫', 'かじけ猫', ''],
    season: 'winter',
    id: 2059,
  },
  {
    name: '髪置',
    yomigana: 'かみおき',
    kyukana: '',
    season: 'winter',
    id: 2060,
    bodai: [],
  },
  {
    name: '神送り',
    yomigana: 'かみおくり',
    kyukana: '',
    season: 'winter',
    id: 2061,
    bodai: [],
  },
  {
    name: '紙子',
    yomigana: 'かみこ',
    kyukana: '',
    bodai: ['紙衣'],
    season: 'winter',
    id: 2062,
  },
  {
    name: '紙漉',
    yomigana: 'かみすき',
    kyukana: '',
    bodai: ['紙漉場', '紙漉女', '楮蒸す'],
    season: 'winter',
    id: 2063,
  },
  {
    name: '神の旅',
    yomigana: 'かみのたび',
    kyukana: '',
    bodai: ['神の旅立'],
    season: 'winter',
    id: 2064,
  },
  {
    name: '神の留守',
    yomigana: 'かみのるす',
    kyukana: '',
    bodai: ['留守の宮', '留守詣'],
    season: 'winter',
    id: 2065,
  },
  {
    name: '神迎',
    yomigana: 'かみむかえ',
    kyukana: 'かみむかへ',
    season: 'winter',
    id: 2066,
    bodai: [],
  },
  {
    name: '鴨',
    yomigana: 'かも',
    kyukana: '',
    bodai: ['真鴨', '子鴨', '鴨の声', '鴨の陣'],
    season: 'winter',
    id: 2067,
  },
  {
    name: '空風',
    yomigana: 'からかぜ',
    kyukana: '',
    bodai: ['空つ風', '北颪', '北下し'],
    season: 'winter',
    id: 2068,
  },
  {
    name: '神等去出の神事',
    yomigana: 'からさでのしんじ',
    kyukana: '',
    bodai: ['神羅佐手', 'からさで祭'],
    season: 'winter',
    id: 2069,
  },
  {
    name: '乾鮭',
    yomigana: 'からざけ',
    kyukana: '',
    bodai: ['干鮭'],
    season: 'winter',
    id: 2070,
  },
  {
    name: '狩',
    yomigana: 'かり',
    kyukana: '',
    bodai: ['猟解禁', '狩猟', '猟犬', '猪狩', '鹿狩', '狩人', '猟夫', '狩の宿'],
    season: 'winter',
    id: 2071,
  },
  {
    name: '枯蘆',
    yomigana: 'かれあし',
    kyukana: '',
    bodai: ['枯芦', '枯葦', '枯蘆原'],
    season: 'winter',
    id: 2072,
  },
  {
    name: '枯木',
    yomigana: 'かれき',
    kyukana: '',
    bodai: ['裸木', '枯枝', '枯木立', '枯木道', '枯木山', '枯木宿', '枯木星'],
    season: 'winter',
    id: 2073,
  },
  {
    name: '枯菊',
    yomigana: 'かれぎく',
    kyukana: '',
    bodai: ['菊枯る', '菊焚く'],
    season: 'winter',
    id: 2074,
  },
  {
    name: '枯草',
    yomigana: 'かれくさ',
    kyukana: '',
    bodai: ['草枯る'],
    season: 'winter',
    id: 2075,
  },
  {
    name: '枯桑',
    yomigana: 'かれくわ',
    kyukana: 'かれくは',
    bodai: ['桑枯る'],
    season: 'winter',
    id: 2076,
  },
  {
    name: '枯芝',
    yomigana: 'かれしば',
    kyukana: '',
    season: 'winter',
    id: 2077,
    bodai: [],
  },
  {
    name: '枯芒',
    yomigana: 'かれすすき',
    kyukana: '',
    bodai: ['枯薄', '冬芒', '枯尾花'],
    season: 'winter',
    id: 2078,
  },
  {
    name: '枯園',
    yomigana: 'かれその',
    kyukana: '',
    bodai: ['枯庭', '冬の園', '冬の庭'],
    season: 'winter',
    id: 2079,
  },
  {
    name: '枯蔓',
    yomigana: 'かれづる',
    kyukana: '',
    bodai: ['枯かづら'],
    season: 'winter',
    id: 2080,
  },
  {
    name: '枯蟷螂',
    yomigana: 'かれとうろう',
    kyukana: '',
    bodai: ['蟷螂枯る'],
    season: 'winter',
    id: 2081,
  },
  {
    name: '枯野',
    yomigana: 'かれの',
    kyukana: '',
    bodai: ['大枯野', '朽野', '枯野道', '枯野人', '枯野宿', '枯原'],
    season: 'winter',
    id: 2082,
  },
  {
    name: '枯葉',
    yomigana: 'かれは',
    kyukana: '',
    season: 'winter',
    id: 2083,
    bodai: [],
  },
  {
    name: '枯萩',
    yomigana: 'かれはぎ',
    kyukana: '',
    bodai: ['萩枯る'],
    season: 'winter',
    id: 2084,
  },
  {
    name: '枯蓮',
    yomigana: 'かれはす',
    kyukana: '',
    bodai: ['枯蓮', '蓮枯る', '蓮の骨'],
    season: 'winter',
    id: 2085,
  },
  {
    name: '枯芭蕉',
    yomigana: 'かればしょう',
    kyukana: 'かればせう',
    bodai: ['芭蕉枯る'],
    season: 'winter',
    id: 2086,
  },
  {
    name: '枯芙蓉',
    yomigana: 'かれふよう',
    kyukana: '',
    bodai: ['芙蓉の実'],
    season: 'winter',
    id: 2087,
  },
  {
    name: '枯葎',
    yomigana: 'かれむぐら',
    kyukana: '',
    season: 'winter',
    id: 2088,
    bodai: [],
  },
  {
    name: '枯柳',
    yomigana: 'かれやなぎ',
    kyukana: '',
    bodai: ['冬柳'],
    season: 'winter',
    id: 2089,
  },
  {
    name: 'カレンダー',
    yomigana: 'かれんだー',
    kyukana: '',
    season: 'winter',
    id: 2090,
    bodai: [],
  },
  {
    name: '革衣',
    yomigana: 'かわごろも',
    kyukana: 'かはごろも',
    bodai: ['革ジャンパー', '革ジャン', '裘（かわごろも）'],
    season: 'winter',
    id: 2091,
  },
  {
    name: '河郎忌',
    yomigana: 'かわろうき',
    kyukana: '',
    season: 'winter',
    id: 2092,
    bodai: [],
  },
  {
    name: '寒',
    yomigana: 'かん',
    kyukana: '',
    bodai: ['寒中', '寒の内', '寒九', '寒四郎'],
    season: 'winter',
    id: 2093,
  },
  {
    name: '寒葵',
    yomigana: 'かんあおい',
    kyukana: 'かんあふひ',
    season: 'winter',
    id: 2094,
    bodai: [],
  },
  {
    name: '寒猿',
    yomigana: 'かんえん',
    kyukana: '',
    bodai: ['寒の猿', '冬の猿', 'かじけ猿'],
    season: 'winter',
    id: 2095,
  },
  {
    name: '寒鴉',
    yomigana: 'かんがらす',
    kyukana: '',
    bodai: ['寒鴉', '冬鴉'],
    season: 'winter',
    id: 2096,
  },
  {
    name: '寒灸',
    yomigana: 'かんきゅう',
    kyukana: 'かんきう',
    bodai: ['寒やいと'],
    season: 'winter',
    id: 2097,
  },
  {
    name: '寒菊',
    yomigana: 'かんぎく',
    kyukana: '',
    bodai: ['冬菊', '霜菊', 'しまかんぎく'],
    season: 'winter',
    id: 2098,
  },
  {
    name: '寒稽古',
    yomigana: 'かんげいこ',
    kyukana: '',
    bodai: ['寒中稽古', '寒復習'],
    season: 'winter',
    id: 2099,
  },
  {
    name: '寒鯉',
    yomigana: 'かんごい',
    kyukana: 'かんごひ',
    bodai: ['凍鯉', '寒鯉釣'],
    season: 'winter',
    id: 2100,
  },
  {
    name: '寒声',
    yomigana: 'かんごえ',
    kyukana: 'かんごゑ',
    season: 'winter',
    id: 2101,
    bodai: [],
  },
  {
    name: '寒肥',
    yomigana: 'かんごえ',
    kyukana: '',
    bodai: ['寒肥', '寒ごやし'],
    season: 'winter',
    id: 2102,
  },
  {
    name: '寒垢離',
    yomigana: 'かんごり',
    kyukana: '',
    bodai: ['寒行'],
    season: 'winter',
    id: 2103,
  },
  {
    name: '寒晒',
    yomigana: 'かんざらし',
    kyukana: '',
    bodai: ['寒曝'],
    season: 'winter',
    id: 2104,
  },
  {
    name: '寒蜆',
    yomigana: 'かんしじみ',
    kyukana: '',
    bodai: ['冬蜆'],
    season: 'winter',
    id: 2105,
  },
  {
    name: '甘蔗刈',
    yomigana: 'かんしょかり',
    kyukana: '',
    bodai: ['甘蔗刈'],
    season: 'winter',
    id: 2106,
  },
  {
    name: '樏',
    yomigana: 'かんじき',
    kyukana: '',
    bodai: ['アイゼン'],
    season: 'winter',
    id: 2107,
  },
  {
    name: '寒雀',
    yomigana: 'かんすずめ',
    kyukana: '',
    bodai: ['冬雀', '凍雀', 'ふくら雀'],
    season: 'winter',
    id: 2108,
  },
  {
    name: '寒施行',
    yomigana: 'かんせぎょう',
    kyukana: 'かんせぎやう',
    bodai: ['野施行', '穴施行'],
    season: 'winter',
    id: 2109,
  },
  {
    name: '寒卵',
    yomigana: 'かんたまご',
    kyukana: '',
    season: 'winter',
    id: 2110,
    bodai: [],
  },
  {
    name: '寒中水泳',
    yomigana: 'かんちゅうすいえい',
    kyukana: '',
    bodai: ['寒泳'],
    season: 'winter',
    id: 2111,
  },
  {
    name: '寒潮',
    yomigana: 'かんちょう',
    kyukana: 'かんてう',
    bodai: ['冬の潮', '冬潮'],
    season: 'winter',
    id: 2112,
  },
  {
    name: '寒椿',
    yomigana: 'かんつばき',
    kyukana: '',
    bodai: ['冬椿'],
    season: 'winter',
    id: 2113,
  },
  {
    name: '寒造',
    yomigana: 'かんづくり',
    kyukana: '',
    season: 'winter',
    id: 2114,
    bodai: [],
  },
  {
    name: '寒釣',
    yomigana: 'かんづり',
    kyukana: '',
    bodai: ['穴釣'],
    season: 'winter',
    id: 2115,
  },
  {
    name: '寒天製す',
    yomigana: 'かんてんせいす',
    kyukana: '',
    bodai: ['寒天造る'],
    season: 'winter',
    id: 2116,
  },
  {
    name: '神無月',
    yomigana: 'かんなづき',
    kyukana: '',
    bodai: ['かみなづき', '神去月', '神有月', '時雨月', '初霜月'],
    season: 'winter',
    id: 2117,
  },
  {
    name: '寒念仏',
    yomigana: 'かんねんぶつ',
    kyukana: '',
    season: 'winter',
    id: 2118,
    bodai: [],
  },
  {
    name: '寒の入',
    yomigana: 'かんのいり',
    kyukana: '',
    bodai: ['寒に入る'],
    season: 'winter',
    id: 2119,
  },
  {
    name: '寒の水',
    yomigana: 'かんのみず',
    kyukana: 'かんのみづ',
    bodai: ['寒水'],
    season: 'winter',
    id: 2120,
  },
  {
    name: '寒晴',
    yomigana: 'かんばれ',
    kyukana: '',
    bodai: ['寒日和'],
    season: 'winter',
    id: 2121,
  },
  {
    name: '寒波',
    yomigana: 'かんぱ',
    kyukana: '',
    bodai: ['寒波来る'],
    season: 'winter',
    id: 2122,
  },
  {
    name: '寒弾',
    yomigana: 'かんびき',
    kyukana: '',
    season: 'winter',
    id: 2123,
    bodai: [],
  },
  {
    name: '寒鮒',
    yomigana: 'かんぶな',
    kyukana: '',
    bodai: ['寒鮒釣'],
    season: 'winter',
    id: 2124,
  },
  {
    name: '寒紅',
    yomigana: 'かんべに',
    kyukana: '',
    season: 'winter',
    id: 2125,
    bodai: [],
  },
  {
    name: '寒木瓜',
    yomigana: 'かんぼけ',
    kyukana: '',
    season: 'winter',
    id: 2126,
    bodai: [],
  },
  {
    name: '寒牡丹',
    yomigana: 'かんぼたん',
    kyukana: '',
    bodai: ['冬牡丹'],
    season: 'winter',
    id: 2127,
  },
  {
    name: '寒参',
    yomigana: 'かんまいり',
    kyukana: 'かんまゐり',
    bodai: ['寒詣', '裸参'],
    season: 'winter',
    id: 2128,
  },
  {
    name: '寒見舞',
    yomigana: 'かんみまい',
    kyukana: 'かんみまひ',
    bodai: ['寒中見舞', '雪見舞'],
    season: 'winter',
    id: 2129,
  },
  {
    name: '寒餅',
    yomigana: 'かんもち',
    kyukana: '',
    season: 'winter',
    id: 2130,
    bodai: [],
  },
  {
    name: '寒林',
    yomigana: 'かんりん',
    kyukana: '',
    bodai: ['寒木'],
    season: 'winter',
    id: 2131,
  },
  {
    name: '外套',
    yomigana: 'がいとう',
    kyukana: 'ぐわいたう',
    bodai: ['オーバー', 'コート'],
    season: 'winter',
    id: 2132,
  },
  {
    name: '賀状書く',
    yomigana: 'がじょうかく',
    kyukana: 'がじやうかく',
    season: 'winter',
    id: 2133,
    bodai: [],
  },
  {
    name: '雁木',
    yomigana: 'がんぎ',
    kyukana: '',
    season: 'winter',
    id: 2134,
    bodai: [],
  },
  {
    name: '北風',
    yomigana: 'きたかぜ',
    kyukana: '',
    bodai: ['北風', '冬の風', '朔風', '寒風', '北吹く'],
    season: 'winter',
    id: 2135,
  },
  {
    name: '北窓塞ぐ',
    yomigana: 'きたまどふさぐ',
    kyukana: '',
    bodai: ['北塞ぐ'],
    season: 'winter',
    id: 2136,
  },
  {
    name: '狐',
    yomigana: 'きつね',
    kyukana: '',
    bodai: ['きつ'],
    season: 'winter',
    id: 2137,
  },
  {
    name: '狐火',
    yomigana: 'きつねび',
    kyukana: '',
    bodai: ['鬼火', '狐の提灯'],
    season: 'winter',
    id: 2138,
  },
  {
    name: '狐罠',
    yomigana: 'きつねわな',
    kyukana: '',
    season: 'winter',
    id: 2139,
    bodai: [],
  },
  {
    name: '着ぶくれ',
    yomigana: 'きぶくれ',
    kyukana: '',
    season: 'winter',
    id: 2140,
    bodai: [],
  },
  {
    name: '切干',
    yomigana: 'きりぼし',
    kyukana: '',
    season: 'winter',
    id: 2141,
    bodai: [],
  },
  {
    name: '勤労感謝の日',
    yomigana: 'きんろうかんしゃのひ',
    kyukana: '',
    season: 'winter',
    id: 2142,
    bodai: [],
  },
  {
    name: '義士会',
    yomigana: 'ぎしかい',
    kyukana: '',
    bodai: ['義士会（ぎしえ）', '義士討入の日'],
    season: 'winter',
    id: 2143,
  },
  {
    name: '空也忌',
    yomigana: 'くうやき',
    kyukana: '',
    bodai: ['空也念仏'],
    season: 'winter',
    id: 2144,
  },
  {
    name: '茎漬',
    yomigana: 'くきづけ',
    kyukana: '',
    bodai: ['菜漬'],
    season: 'winter',
    id: 2145,
  },
  {
    name: '嚔',
    yomigana: 'くさめ',
    kyukana: '',
    bodai: ['くしやみ', 'はなひる'],
    season: 'winter',
    id: 2146,
  },
  {
    name: '鯨',
    yomigana: 'くじら',
    kyukana: 'くぢら',
    bodai: ['勇魚'],
    season: 'winter',
    id: 2147,
  },
  {
    name: '鯨汁',
    yomigana: 'くじらじる',
    kyukana: '',
    bodai: ['鯨鍋'],
    season: 'winter',
    id: 2148,
  },
  {
    name: '薬喰',
    yomigana: 'くすりぐい',
    kyukana: 'くすりぐひ',
    bodai: ['紅葉鍋'],
    season: 'winter',
    id: 2149,
  },
  {
    name: '葛晒す',
    yomigana: 'くずさらす',
    kyukana: '',
    bodai: ['葛晒し'],
    season: 'winter',
    id: 2150,
  },
  {
    name: '葛湯',
    yomigana: 'くずゆ',
    kyukana: '',
    season: 'winter',
    id: 2151,
    bodai: [],
  },
  {
    name: '口切',
    yomigana: 'くちきり',
    kyukana: '',
    season: 'winter',
    id: 2152,
    bodai: [],
  },
  {
    name: '熊',
    yomigana: 'くま',
    kyukana: '',
    bodai: ['羆', '熊の子', '熊穴に入る'],
    season: 'winter',
    id: 2153,
  },
  {
    name: '熊突',
    yomigana: 'くまつき',
    kyukana: '',
    bodai: ['穴熊狩'],
    season: 'winter',
    id: 2154,
  },
  {
    name: '熊祭',
    yomigana: 'くままつり',
    kyukana: '',
    bodai: ['熊送り', '贄の熊', 'イオマンテ', 'カムイヨマンテ'],
    season: 'winter',
    id: 2155,
  },
  {
    name: 'クリオネ',
    yomigana: 'くりおね',
    kyukana: '',
    bodai: ['はだかかめがい'],
    season: 'winter',
    id: 2156,
  },
  {
    name: 'クリスマス',
    yomigana: 'くりすます',
    kyukana: '',
    bodai: [
      '降誕祭',
      '聖誕節',
      '聖夜',
      '聖歌',
      'クリスマスツリー',
      '聖樹',
      'クリスマスケーキ',
      'サンタクロース',
      '聖夜劇',
      'クリスマスイブ',
    ],
    season: 'winter',
    id: 2157,
  },
  {
    name: 'けあらし',
    yomigana: 'けあらし',
    kyukana: '',
    bodai: ['気嵐'],
    season: 'winter',
    id: 2158,
  },
  {
    name: '毛糸編む',
    yomigana: 'けいとあむ',
    kyukana: '',
    bodai: ['毛糸', '毛糸玉'],
    season: 'winter',
    id: 2159,
  },
  {
    name: '毛皮',
    yomigana: 'けがわ',
    kyukana: 'けがは',
    bodai: ['毛皮売', '毛皮店'],
    season: 'winter',
    id: 2160,
  },
  {
    name: '毛衣',
    yomigana: 'けごろも',
    kyukana: '',
    bodai: ['裘', '皮衣'],
    season: 'winter',
    id: 2161,
  },
  {
    name: '厳寒',
    yomigana: 'げんかん',
    kyukana: '',
    bodai: ['極寒', '酷寒', '厳冬'],
    season: 'winter',
    id: 2162,
  },
  {
    name: '降誕祭',
    yomigana: 'こうたんさい',
    kyukana: '',
    season: 'winter',
    id: 2163,
    bodai: [],
  },
  {
    name: '氷',
    yomigana: 'こおり',
    kyukana: 'こほり',
    bodai: ['厚氷', '氷面鏡', '氷点下', '結氷'],
    season: 'winter',
    id: 2164,
  },
  {
    name: '凍る',
    yomigana: 'こおる',
    kyukana: 'こほる',
    bodai: ['氷る', '凍つ', '冱つ', '凍む', '冰る'],
    season: 'winter',
    id: 2165,
  },
  {
    name: '木枯',
    yomigana: 'こがらし',
    kyukana: '',
    bodai: ['凩'],
    season: 'winter',
    id: 2166,
  },
  {
    name: '炬燵',
    yomigana: 'こたつ',
    kyukana: '',
    bodai: ['切炬燵', '置炬燵', '掘炬燵'],
    season: 'winter',
    id: 2167,
  },
  {
    name: '木の葉',
    yomigana: 'このは',
    kyukana: '',
    bodai: ['木の葉雨', '木の葉散る'],
    season: 'winter',
    id: 2168,
  },
  {
    name: '木の葉髪',
    yomigana: 'このはがみ',
    kyukana: '',
    season: 'winter',
    id: 2169,
    bodai: [],
  },
  {
    name: '海鼠腸',
    yomigana: 'このわた',
    kyukana: '',
    bodai: ['このわた'],
    season: 'winter',
    id: 2170,
  },
  {
    name: '小春',
    yomigana: 'こはる',
    kyukana: '',
    bodai: ['小春日', '小春日和', '小六月'],
    season: 'winter',
    id: 2171,
  },
  {
    name: '氷下魚',
    yomigana: 'こまい',
    kyukana: '',
    bodai: ['氷下魚釣', '氷下魚汁'],
    season: 'winter',
    id: 2172,
  },
  {
    name: '暦売',
    yomigana: 'こよみうり',
    kyukana: '',
    season: 'winter',
    id: 2173,
    bodai: [],
  },
  {
    name: '蒟蒻掘る',
    yomigana: 'こんにゃくほる',
    kyukana: '',
    bodai: ['蒟蒻干す'],
    season: 'winter',
    id: 2174,
  },
  {
    name: '御用納',
    yomigana: 'ごようおさめ',
    kyukana: 'ごようをさめ',
    bodai: ['仕事納'],
    season: 'winter',
    id: 2175,
  },
  {
    name: '笹鳴',
    yomigana: 'ささなき',
    kyukana: '',
    bodai: ['笹子鳴く'],
    season: 'winter',
    id: 2176,
  },
  {
    name: '山茶花',
    yomigana: 'さざんか',
    kyukana: 'さざんくわ',
    bodai: ['姫椿'],
    season: 'winter',
    id: 2177,
  },
  {
    name: '札幌雪祭',
    yomigana: 'さっぽろゆきまつり',
    kyukana: '',
    bodai: ['雪祭', '氷像', '雪像'],
    season: 'winter',
    id: 2178,
  },
  {
    name: '里神楽',
    yomigana: 'さとかぐら',
    kyukana: '',
    bodai: ['宮神楽', '夜神楽', '湯立神楽', '遠山祭'],
    season: 'winter',
    id: 2179,
  },
  {
    name: '寒し',
    yomigana: 'さむし',
    kyukana: '',
    bodai: ['寒さ', '寒気', '寒冷'],
    season: 'winter',
    id: 2180,
  },
  {
    name: '鮫',
    yomigana: 'さめ',
    kyukana: '',
    bodai: ['鱶'],
    season: 'winter',
    id: 2181,
  },
  {
    name: '冴ゆ',
    yomigana: 'さゆ',
    kyukana: '',
    season: 'winter',
    id: 2182,
    bodai: [],
  },
  {
    name: '三寒四温',
    yomigana: 'さんかんしおん',
    kyukana: 'さんかんしをん',
    bodai: ['三寒', '四温', '四温日和'],
    season: 'winter',
    id: 2183,
  },
  {
    name: '三平汁',
    yomigana: 'さんぺいじる',
    kyukana: '',
    season: 'winter',
    id: 2184,
    bodai: [],
  },
  {
    name: '朱欒',
    yomigana: 'ざぼん',
    kyukana: '',
    bodai: ['うちむらさき', '文旦', 'ぼんたん'],
    season: 'winter',
    id: 2185,
  },
  {
    name: '塩鮭',
    yomigana: 'しおざけ',
    kyukana: 'しほざけ',
    bodai: ['新巻'],
    season: 'winter',
    id: 2186,
  },
  {
    name: '敷松葉',
    yomigana: 'しきまつば',
    kyukana: '',
    season: 'winter',
    id: 2187,
    bodai: [],
  },
  {
    name: '時雨',
    yomigana: 'しぐれ',
    kyukana: '',
    bodai: ['時雨るる', '朝時雨', '夕時雨', '小夜時雨', '村時雨', '片時雨'],
    season: 'winter',
    id: 2188,
  },
  {
    name: '柳葉魚',
    yomigana: 'ししゃも',
    kyukana: '',
    season: 'winter',
    id: 2189,
    bodai: [],
  },
  {
    name: '歯朶刈',
    yomigana: 'しだかり',
    kyukana: '',
    season: 'winter',
    id: 2190,
    bodai: [],
  },
  {
    name: '七五三',
    yomigana: 'しちごさん',
    kyukana: '',
    bodai: ['七五三の祝', '七五三祝', '千歳飴'],
    season: 'winter',
    id: 2191,
  },
  {
    name: '凍豆腐',
    yomigana: 'しみどうふ',
    kyukana: '',
    bodai: ['氷豆腐', '寒豆腐', '高野豆腐', '凍豆腐造る'],
    season: 'winter',
    id: 2192,
  },
  {
    name: '注連飾る',
    yomigana: 'しめかざる',
    kyukana: '',
    season: 'winter',
    id: 2193,
    bodai: [],
  },
  {
    name: '注連作',
    yomigana: 'しめつくり',
    kyukana: '',
    season: 'winter',
    id: 2194,
    bodai: [],
  },
  {
    name: '霜',
    yomigana: 'しも',
    kyukana: '',
    bodai: [
      '霜の花',
      '大霜',
      '深霜',
      '強霜',
      '朝霜',
      '夜霜',
      '霜晴',
      '霜凪',
      '霜雫',
      '霜解',
      '霜の声',
    ],
    season: 'winter',
    id: 2195,
  },
  {
    name: '霜枯',
    yomigana: 'しもがれ',
    kyukana: '',
    season: 'winter',
    id: 2196,
    bodai: [],
  },
  {
    name: '霜月',
    yomigana: 'しもつき',
    kyukana: '',
    bodai: ['霜降月'],
    season: 'winter',
    id: 2197,
  },
  {
    name: '霜柱',
    yomigana: 'しもばしら',
    kyukana: '',
    season: 'winter',
    id: 2198,
    bodai: [],
  },
  {
    name: '霜焼',
    yomigana: 'しもやけ',
    kyukana: '',
    bodai: ['凍傷', '霜腫'],
    season: 'winter',
    id: 2199,
  },
  {
    name: '霜夜',
    yomigana: 'しもよ',
    kyukana: '',
    season: 'winter',
    id: 2200,
    bodai: [],
  },
  {
    name: '霜除',
    yomigana: 'しもよけ',
    kyukana: '',
    season: 'winter',
    id: 2201,
    bodai: [],
  },
  {
    name: '社会鍋',
    yomigana: 'しゃかいなべ',
    kyukana: 'しやくわいなべ',
    bodai: ['慈善鍋'],
    season: 'winter',
    id: 2202,
  },
  {
    name: '小寒',
    yomigana: 'しょうかん',
    kyukana: 'せうかん',
    season: 'winter',
    id: 2203,
    bodai: [],
  },
  {
    name: '正月事始',
    yomigana: 'しょうがつことはじめ',
    kyukana: 'しやうぐあつことはじめ',
    bodai: ['事始'],
    season: 'winter',
    id: 2204,
  },
  {
    name: '障子',
    yomigana: 'しょうじ',
    kyukana: 'しやうじ',
    bodai: ['冬障子', '腰障子', '明り障子'],
    season: 'winter',
    id: 2205,
  },
  {
    name: 'ショール',
    yomigana: 'しょーる',
    kyukana: '',
    bodai: ['肩掛'],
    season: 'winter',
    id: 2206,
  },
  {
    name: '師走',
    yomigana: 'しわす',
    kyukana: 'しはす',
    bodai: ['極月', '臘月', '春待月'],
    season: 'winter',
    id: 2207,
  },
  {
    name: '神農祭',
    yomigana: 'しんのうさい',
    kyukana: '',
    bodai: ['神農の虎'],
    season: 'winter',
    id: 2208,
  },
  {
    name: '新海苔',
    yomigana: 'しんのり',
    kyukana: '',
    bodai: ['寒海苔'],
    season: 'winter',
    id: 2209,
  },
  {
    name: 'ジャケツ',
    yomigana: 'じゃけつ',
    kyukana: '',
    season: 'winter',
    id: 2210,
    bodai: [],
  },
  {
    name: '十一月',
    yomigana: 'じゅういちがつ',
    kyukana: 'じふいちぐわつ',
    season: 'winter',
    id: 2211,
    bodai: [],
  },
  {
    name: '絨緞',
    yomigana: 'じゅうたん',
    kyukana: '',
    bodai: ['緞通', 'カーペット'],
    season: 'winter',
    id: 2212,
  },
  {
    name: '十二月',
    yomigana: 'じゅうにがつ',
    kyukana: 'じふにぐわつ',
    season: 'winter',
    id: 2213,
    bodai: [],
  },
  {
    name: '十夜',
    yomigana: 'じゅうや',
    kyukana: 'じふや',
    bodai: ['十夜法要', 'お十夜', '十夜粥', '十夜婆'],
    season: 'winter',
    id: 2214,
  },
  {
    name: '樹氷',
    yomigana: 'じゅひょう',
    kyukana: '',
    bodai: ['木華', '霧の花', '樹氷林'],
    season: 'winter',
    id: 2215,
  },
  {
    name: '除夜',
    yomigana: 'じょや',
    kyukana: 'ぢよや',
    bodai: ['除夕', '年の夜'],
    season: 'winter',
    id: 2216,
  },
  {
    name: '除夜の鐘',
    yomigana: 'じょやのかね',
    kyukana: 'ぢよやのかね',
    season: 'winter',
    id: 2217,
    bodai: [],
  },
  {
    name: '除夜詣',
    yomigana: 'じょやもうで',
    kyukana: 'ぢよやもうで',
    bodai: ['年越詣', '節分詣', '年越参'],
    season: 'winter',
    id: 2218,
  },
  {
    name: '水仙',
    yomigana: 'すいせん',
    kyukana: '',
    bodai: ['水仙花', '雪中花'],
    season: 'winter',
    id: 2219,
  },
  {
    name: 'すが漏り',
    yomigana: 'すがもり',
    kyukana: '',
    season: 'winter',
    id: 2220,
    bodai: [],
  },
  {
    name: '隙間風',
    yomigana: 'すきまかぜ',
    kyukana: '',
    season: 'winter',
    id: 2221,
    bodai: [],
  },
  {
    name: '鋤焼',
    yomigana: 'すきやき',
    kyukana: '',
    bodai: ['牛鍋', '馬肉鋤', '桜鍋'],
    season: 'winter',
    id: 2222,
  },
  {
    name: 'スキー',
    yomigana: 'すきー',
    kyukana: '',
    bodai: ['スキー場', 'スキーヤー', 'ゲレンデ', 'シャンツェ'],
    season: 'winter',
    id: 2223,
  },
  {
    name: '酢茎',
    yomigana: 'すぐき',
    kyukana: '',
    season: 'winter',
    id: 2224,
    bodai: [],
  },
  {
    name: 'スケート',
    yomigana: 'すけーと',
    kyukana: '',
    bodai: ['氷滑り', 'スケート場'],
    season: 'winter',
    id: 2225,
  },
  {
    name: '煤払',
    yomigana: 'すすはらい',
    kyukana: 'すすはらひ',
    bodai: ['煤掃', '煤竹', '煤篭', '煤湯'],
    season: 'winter',
    id: 2226,
  },
  {
    name: 'ストーブ',
    yomigana: 'すとーぶ',
    kyukana: '',
    bodai: ['暖炉', 'ペチカ'],
    season: 'winter',
    id: 2227,
  },
  {
    name: '炭',
    yomigana: 'すみ',
    kyukana: '',
    bodai: ['炭火', '埋火', '消炭', '炭斗', '炭篭', '炭売', '炭屋', '炭俵'],
    season: 'winter',
    id: 2228,
  },
  {
    name: '炭焼',
    yomigana: 'すみやき',
    kyukana: '',
    bodai: ['炭焼小屋', '炭焼竃', '炭竃'],
    season: 'winter',
    id: 2229,
  },
  {
    name: '頭巾',
    yomigana: 'ずきん',
    kyukana: 'づきん',
    season: 'winter',
    id: 2230,
    bodai: [],
  },
  {
    name: '青邨忌',
    yomigana: 'せいそんき',
    kyukana: '',
    season: 'winter',
    id: 2231,
    bodai: [],
  },
  {
    name: '青畝忌',
    yomigana: 'せいほき',
    kyukana: '',
    bodai: ['万両忌'],
    season: 'winter',
    id: 2232,
  },
  {
    name: '咳',
    yomigana: 'せき',
    kyukana: '',
    bodai: ['咳く', '咳く'],
    season: 'winter',
    id: 2233,
  },
  {
    name: '石炭',
    yomigana: 'せきたん',
    kyukana: '',
    season: 'winter',
    id: 2234,
    bodai: [],
  },
  {
    name: '節分',
    yomigana: 'せつぶん',
    kyukana: '',
    bodai: ['大原雑魚寝'],
    season: 'winter',
    id: 2235,
  },
  {
    name: '背蒲団',
    yomigana: 'せなぶとん',
    kyukana: '',
    bodai: ['肩蒲団', '腰蒲団', '負真綿'],
    season: 'winter',
    id: 2236,
  },
  {
    name: '千両',
    yomigana: 'せんりょう',
    kyukana: 'せんりやう',
    bodai: ['仙蓼', '実千両'],
    season: 'winter',
    id: 2237,
  },
  {
    name: 'セーター',
    yomigana: 'せーたー',
    kyukana: '',
    bodai: ['カーディガン'],
    season: 'winter',
    id: 2238,
  },
  {
    name: '草城忌',
    yomigana: 'そうじょうき',
    kyukana: 'さうじやうき',
    season: 'winter',
    id: 2239,
    bodai: [],
  },
  {
    name: '漱石忌',
    yomigana: 'そうせきき',
    kyukana: '',
    season: 'winter',
    id: 2240,
    bodai: [],
  },
  {
    name: '早梅',
    yomigana: 'そうばい',
    kyukana: 'さうばい',
    bodai: ['梅早し'],
    season: 'winter',
    id: 2241,
  },
  {
    name: '蘇鉄の実',
    yomigana: 'そてつのみ',
    kyukana: '',
    season: 'winter',
    id: 2242,
    bodai: [],
  },
  {
    name: '蕎麦掻',
    yomigana: 'そばがき',
    kyukana: '',
    bodai: ['蕎麦湯'],
    season: 'winter',
    id: 2243,
  },
  {
    name: '橇',
    yomigana: 'そり',
    kyukana: '',
    bodai: ['馬橇', '犬橇', '手橇', '雪車'],
    season: 'winter',
    id: 2244,
  },
  {
    name: '雑炊',
    yomigana: 'ぞうすい',
    kyukana: 'ざふすい',
    bodai: ['おじや'],
    season: 'winter',
    id: 2245,
  },
  {
    name: '鯛焼',
    yomigana: 'たいやき',
    kyukana: '',
    bodai: ['今川焼'],
    season: 'winter',
    id: 2246,
  },
  {
    name: '鷹',
    yomigana: 'たか',
    kyukana: '',
    bodai: ['大鷹', '小鷹', 'さしば', '隼'],
    season: 'winter',
    id: 2247,
  },
  {
    name: '鷹狩',
    yomigana: 'たかがり',
    kyukana: '',
    bodai: ['鷹匠', '鷹野'],
    season: 'winter',
    id: 2248,
  },
  {
    name: '焚火',
    yomigana: 'たきび',
    kyukana: '',
    season: 'winter',
    id: 2249,
    bodai: [],
  },
  {
    name: '沢庵',
    yomigana: 'たくあん',
    kyukana: '',
    bodai: ['沢庵漬', '沢庵漬製す', '大根漬く'],
    season: 'winter',
    id: 2250,
  },
  {
    name: '竹馬',
    yomigana: 'たけうま',
    kyukana: '',
    season: 'winter',
    id: 2251,
    bodai: [],
  },
  {
    name: '畳替',
    yomigana: 'たたみがえ',
    kyukana: 'たたみがへ',
    season: 'winter',
    id: 2252,
    bodai: [],
  },
  {
    name: '竹瓮',
    yomigana: 'たっぺ',
    kyukana: '',
    season: 'winter',
    id: 2253,
    bodai: [],
  },
  {
    name: '炭団',
    yomigana: 'たどん',
    kyukana: '',
    bodai: ['豆炭'],
    season: 'winter',
    id: 2254,
  },
  {
    name: '狸',
    yomigana: 'たぬき',
    kyukana: '',
    bodai: ['たのき', 'むじな'],
    season: 'winter',
    id: 2255,
  },
  {
    name: '狸汁',
    yomigana: 'たぬきじる',
    kyukana: '',
    season: 'winter',
    id: 2256,
    bodai: [],
  },
  {
    name: '狸罠',
    yomigana: 'たぬきわな',
    kyukana: '',
    season: 'winter',
    id: 2257,
    bodai: [],
  },
  {
    name: '足袋',
    yomigana: 'たび',
    kyukana: '',
    bodai: ['白足袋', '色足袋'],
    season: 'winter',
    id: 2258,
  },
  {
    name: '玉子酒',
    yomigana: 'たまござけ',
    kyukana: '',
    bodai: ['卵酒'],
    season: 'winter',
    id: 2259,
  },
  {
    name: '鱈',
    yomigana: 'たら',
    kyukana: '',
    bodai: ['雪魚', '真鱈', '助宗鱈', '鱈場', '鱈船', '子持鱈', '鱈汁'],
    season: 'winter',
    id: 2260,
  },
  {
    name: '短日',
    yomigana: 'たんじつ',
    kyukana: '',
    bodai: ['日短', '日短し', '暮早し', '暮易し'],
    season: 'winter',
    id: 2261,
  },
  {
    name: '探梅',
    yomigana: 'たんばい',
    kyukana: '',
    bodai: ['梅探る', '探梅行'],
    season: 'winter',
    id: 2262,
  },
  {
    name: '大寒',
    yomigana: 'だいかん',
    kyukana: '',
    bodai: ['寒土用'],
    season: 'winter',
    id: 2263,
  },
  {
    name: '大根焚',
    yomigana: 'だいこたき',
    kyukana: '',
    bodai: ['鳴滝の大根焚'],
    season: 'winter',
    id: 2264,
  },
  {
    name: '大根の葉',
    yomigana: 'だいこのは',
    kyukana: '',
    season: 'winter',
    id: 2265,
    bodai: [],
  },
  {
    name: '大根',
    yomigana: 'だいこん',
    kyukana: '',
    bodai: ['だいこ', 'おほね', 'すずしろ', '大根畑'],
    season: 'winter',
    id: 2266,
  },
  {
    name: '大根洗ふ',
    yomigana: 'だいこんあらう',
    kyukana: 'だいこんあらふ',
    season: 'winter',
    id: 2267,
    bodai: [],
  },
  {
    name: '大根引',
    yomigana: 'だいこんひき',
    kyukana: '',
    bodai: ['大根引'],
    season: 'winter',
    id: 2268,
  },
  {
    name: '大根干す',
    yomigana: 'だいこんほす',
    kyukana: '',
    bodai: ['懸大根', '干大根'],
    season: 'winter',
    id: 2269,
  },
  {
    name: '大師講',
    yomigana: 'だいしこう',
    kyukana: '',
    season: 'winter',
    id: 2270,
    bodai: [],
  },
  {
    name: 'ダイヤモンドダスト',
    yomigana: 'だいやもんどだすと',
    kyukana: '',
    bodai: ['細氷'],
    season: 'winter',
    id: 2271,
  },
  {
    name: '達磨忌',
    yomigana: 'だるまき',
    kyukana: '',
    bodai: ['初祖忌', '少林忌'],
    season: 'winter',
    id: 2272,
  },
  {
    name: '暖房',
    yomigana: 'だんぼう',
    kyukana: 'だんばう',
    bodai: ['スチーム', 'ヒーター', '暖房車'],
    season: 'winter',
    id: 2273,
  },
  {
    name: '近松忌',
    yomigana: 'ちかまつき',
    kyukana: '',
    bodai: ['巣林子忌'],
    season: 'winter',
    id: 2274,
  },
  {
    name: '秩父夜祭',
    yomigana: 'ちちぶよまつり',
    kyukana: '',
    season: 'winter',
    id: 2275,
    bodai: [],
  },
  {
    name: '千鳥',
    yomigana: 'ちどり',
    kyukana: '',
    bodai: [
      '鵆',
      '磯千鳥',
      '浜千鳥',
      '川千鳥',
      '夕千鳥',
      '小夜千鳥',
      '群千鳥',
      '友千鳥',
      '遠千鳥',
      '鳴く千鳥',
    ],
    season: 'winter',
    id: 2276,
  },
  {
    name: '茶の花',
    yomigana: 'ちゃのはな',
    kyukana: '',
    season: 'winter',
    id: 2277,
    bodai: [],
  },
  {
    name: 'ちやんちやんこ',
    yomigana: 'ちやんちやんこ',
    kyukana: '',
    bodai: ['袖無'],
    season: 'winter',
    id: 2278,
  },
  {
    name: '追儺',
    yomigana: 'ついな',
    kyukana: '',
    bodai: ['鬼やらひ', 'なやらひ'],
    season: 'winter',
    id: 2279,
  },
  {
    name: '石蕗の花',
    yomigana: 'つはのはな',
    kyukana: '',
    bodai: ['つ吾の花', '石蕗の花', '石蕗'],
    season: 'winter',
    id: 2280,
  },
  {
    name: '冷たし',
    yomigana: 'つめたし',
    kyukana: '',
    bodai: ['底冷え'],
    season: 'winter',
    id: 2281,
  },
  {
    name: '氷柱',
    yomigana: 'つらら',
    kyukana: '',
    bodai: ['垂氷', '草氷柱'],
    season: 'winter',
    id: 2282,
  },
  {
    name: '鶴',
    yomigana: 'つる',
    kyukana: '',
    bodai: ['凍鶴', '冬の鶴'],
    season: 'winter',
    id: 2283,
  },
  {
    name: '貞徳忌',
    yomigana: 'ていとくき',
    kyukana: '',
    season: 'winter',
    id: 2284,
    bodai: [],
  },
  {
    name: '手袋',
    yomigana: 'てぶくろ',
    kyukana: '',
    bodai: ['皮手袋', 'マフ'],
    season: 'winter',
    id: 2285,
  },
  {
    name: '天皇誕生日',
    yomigana: 'てんのうたんじょうび',
    kyukana: 'てんわうたんじやうび',
    season: 'winter',
    id: 2286,
    bodai: [],
  },
  {
    name: '電気毛布',
    yomigana: 'でんきもうふ',
    kyukana: '',
    season: 'winter',
    id: 2287,
    bodai: [],
  },
  {
    name: '冬耕',
    yomigana: 'とうこう',
    kyukana: 'とうかう',
    season: 'winter',
    id: 2288,
    bodai: [],
  },
  {
    name: '冬至',
    yomigana: 'とうじ',
    kyukana: '',
    bodai: ['冬至粥', '冬至南瓜'],
    season: 'winter',
    id: 2289,
  },
  {
    name: '冬眠',
    yomigana: 'とうみん',
    kyukana: '',
    season: 'winter',
    id: 2290,
    bodai: [],
  },
  {
    name: '年惜しむ',
    yomigana: 'としおしむ',
    kyukana: 'としをしむ',
    season: 'winter',
    id: 2291,
    bodai: [],
  },
  {
    name: '年木樵',
    yomigana: 'としきこり',
    kyukana: '',
    bodai: ['節木樵', '年木積む', '年木売'],
    season: 'winter',
    id: 2292,
  },
  {
    name: '年越',
    yomigana: 'としこし',
    kyukana: '',
    bodai: ['年を越す'],
    season: 'winter',
    id: 2293,
  },
  {
    name: '年篭',
    yomigana: 'としごもり',
    kyukana: '',
    bodai: ['年籠'],
    season: 'winter',
    id: 2294,
  },
  {
    name: '年の市',
    yomigana: 'としのいち',
    kyukana: '',
    season: 'winter',
    id: 2295,
    bodai: [],
  },
  {
    name: '年の内',
    yomigana: 'としのうち',
    kyukana: '',
    bodai: ['年内'],
    season: 'winter',
    id: 2296,
  },
  {
    name: '年の暮',
    yomigana: 'としのくれ',
    kyukana: '',
    bodai: [
      '歳暮',
      '歳晩',
      '歳末',
      '年末',
      '年歩む',
      '年の瀬',
      '年の果',
      '年暮るる',
    ],
    season: 'winter',
    id: 2297,
  },
  {
    name: '年守る',
    yomigana: 'としまもる',
    kyukana: '',
    season: 'winter',
    id: 2298,
    bodai: [],
  },
  {
    name: '年用意',
    yomigana: 'としようい',
    kyukana: '',
    bodai: ['春支度'],
    season: 'winter',
    id: 2299,
  },
  {
    name: '年忘',
    yomigana: 'としわすれ',
    kyukana: '',
    bodai: ['忘年会'],
    season: 'winter',
    id: 2300,
  },
  {
    name: '寅彦忌',
    yomigana: 'とらひこき',
    kyukana: '',
    season: 'winter',
    id: 2301,
    bodai: [],
  },
  {
    name: '酉の市',
    yomigana: 'とりのいち',
    kyukana: '',
    bodai: [
      'お酉さま',
      '酉の町',
      '一の酉',
      '二の酉',
      '三の酉',
      'おかめ市',
      '熊手',
    ],
    season: 'winter',
    id: 2302,
  },
  {
    name: '泥鰌掘る',
    yomigana: 'どじょうほる',
    kyukana: 'どぢやうほる',
    season: 'winter',
    id: 2303,
    bodai: [],
  },
  {
    name: '褞袍',
    yomigana: 'どてら',
    kyukana: '',
    bodai: ['丹前'],
    season: 'winter',
    id: 2304,
  },
  {
    name: '納豆汁',
    yomigana: 'なっとじる',
    kyukana: '',
    season: 'winter',
    id: 2305,
    bodai: [],
  },
  {
    name: '名の木枯る',
    yomigana: 'なのきかる',
    kyukana: '',
    bodai: ['蔦枯る', '銀杏枯る', '葡萄枯る', '欅枯る', '冬欅'],
    season: 'winter',
    id: 2306,
  },
  {
    name: '名の草枯る',
    yomigana: 'なのくさかる',
    kyukana: '',
    bodai: ['名草枯る'],
    season: 'winter',
    id: 2307,
  },
  {
    name: '鍋焼',
    yomigana: 'なべやき',
    kyukana: '',
    bodai: ['鍋焼饂飩'],
    season: 'winter',
    id: 2308,
  },
  {
    name: '海鼠',
    yomigana: 'なまこ',
    kyukana: '',
    bodai: ['酢海鼠'],
    season: 'winter',
    id: 2309,
  },
  {
    name: '波の花',
    yomigana: 'なみのはな',
    kyukana: '',
    bodai: ['浪の華', '潮花'],
    season: 'winter',
    id: 2310,
  },
  {
    name: '煮凝',
    yomigana: 'にこごり',
    kyukana: '',
    bodai: ['煮凍'],
    season: 'winter',
    id: 2311,
  },
  {
    name: '日記買う',
    yomigana: 'にっきかう',
    kyukana: 'につきかふ',
    bodai: ['古日記'],
    season: 'winter',
    id: 2312,
  },
  {
    name: '日記果つ',
    yomigana: 'にっきはつ',
    kyukana: '',
    season: 'winter',
    id: 2313,
    bodai: [],
  },
  {
    name: '人参',
    yomigana: 'にんじん',
    kyukana: '',
    bodai: ['胡蘿蔔'],
    season: 'winter',
    id: 2314,
  },
  {
    name: '葱',
    yomigana: 'ねぎ',
    kyukana: '',
    bodai: ['葱', '一文字', '根深', '葉葱', '葱畑'],
    season: 'winter',
    id: 2315,
  },
  {
    name: '根深汁',
    yomigana: 'ねぶかじる',
    kyukana: '',
    bodai: ['葱汁'],
    season: 'winter',
    id: 2316,
  },
  {
    name: 'ねんねこ',
    yomigana: 'ねんねこ',
    kyukana: '',
    bodai: ['ねんねこばんてん'],
    season: 'winter',
    id: 2317,
  },
  {
    name: '年末賞与',
    yomigana: 'ねんまつしょうよ',
    kyukana: '',
    bodai: ['年末手当', 'ボーナス'],
    season: 'winter',
    id: 2318,
  },
  {
    name: 'のっぺい汁',
    yomigana: 'のっぺいじる',
    kyukana: '',
    bodai: ['のつぺ　濃餅汁'],
    season: 'winter',
    id: 2319,
  },
  {
    name: '袴着',
    yomigana: 'はかまぎ',
    kyukana: '',
    season: 'winter',
    id: 2320,
    bodai: [],
  },
  {
    name: '掃納',
    yomigana: 'はきおさめ',
    kyukana: 'はきをさめ',
    season: 'winter',
    id: 2321,
    bodai: [],
  },
  {
    name: '波郷忌',
    yomigana: 'はきょうき',
    kyukana: 'はきやうき',
    season: 'winter',
    id: 2322,
    bodai: [],
  },
  {
    name: '白菜',
    yomigana: 'はくさい',
    kyukana: '',
    season: 'winter',
    id: 2323,
    bodai: [],
  },
  {
    name: '白鳥',
    yomigana: 'はくちょう',
    kyukana: 'はくてう',
    bodai: ['スワン', '鵠', '大白鳥', '黒鳥'],
    season: 'winter',
    id: 2324,
  },
  {
    name: '羽子板市',
    yomigana: 'はごいたいち',
    kyukana: '',
    season: 'winter',
    id: 2325,
    bodai: [],
  },
  {
    name: '蓮根掘る',
    yomigana: 'はすねほる',
    kyukana: '',
    bodai: ['蓮掘'],
    season: 'winter',
    id: 2326,
  },
  {
    name: '鰰',
    yomigana: 'はたはた',
    kyukana: '',
    bodai: ['雷魚', 'かみなりうを'],
    season: 'winter',
    id: 2327,
  },
  {
    name: '鉢叩',
    yomigana: 'はちたたき',
    kyukana: '',
    season: 'winter',
    id: 2328,
    bodai: [],
  },
  {
    name: '初氷',
    yomigana: 'はつごおり',
    kyukana: 'はつごほり',
    season: 'winter',
    id: 2329,
    bodai: [],
  },
  {
    name: '初時雨',
    yomigana: 'はつしぐれ',
    kyukana: '',
    season: 'winter',
    id: 2330,
    bodai: [],
  },
  {
    name: '初霜',
    yomigana: 'はつしも',
    kyukana: '',
    season: 'winter',
    id: 2331,
    bodai: [],
  },
  {
    name: '初冬',
    yomigana: 'はつふゆ',
    kyukana: '',
    bodai: ['初冬', '冬初め', '冬浅し'],
    season: 'winter',
    id: 2332,
  },
  {
    name: '初雪',
    yomigana: 'はつゆき',
    kyukana: '',
    bodai: ['新雪'],
    season: 'winter',
    id: 2333,
  },
  {
    name: '葉牡丹',
    yomigana: 'はぼたん',
    kyukana: '',
    season: 'winter',
    id: 2334,
    bodai: [],
  },
  {
    name: '針供養',
    yomigana: 'はりくよう',
    kyukana: 'はりくやう',
    bodai: ['針休み', '針納め'],
    season: 'winter',
    id: 2335,
  },
  {
    name: '春近し',
    yomigana: 'はるちかし',
    kyukana: '',
    bodai: ['春隣', '春信'],
    season: 'winter',
    id: 2336,
  },
  {
    name: '春待つ',
    yomigana: 'はるまつ',
    kyukana: '',
    bodai: ['春を待つ', '待春'],
    season: 'winter',
    id: 2337,
  },
  {
    name: '阪神大震災忌',
    yomigana: 'はんしんだいしんさいき',
    kyukana: '',
    season: 'winter',
    id: 2338,
    bodai: [],
  },
  {
    name: '芭蕉忌',
    yomigana: 'ばしょうき',
    kyukana: 'ばせうき',
    bodai: ['時雨忌', '桃青忌', '翁忌'],
    season: 'winter',
    id: 2339,
  },
  {
    name: '日脚伸ぶ',
    yomigana: 'ひあしのぶ',
    kyukana: '',
    season: 'winter',
    id: 2340,
    bodai: [],
  },
  {
    name: '避寒',
    yomigana: 'ひかん',
    kyukana: '',
    bodai: ['避寒宿'],
    season: 'winter',
    id: 2341,
  },
  {
    name: '久女忌',
    yomigana: 'ひさじょき',
    kyukana: 'ひさぢよき',
    season: 'winter',
    id: 2342,
    bodai: [],
  },
  {
    name: '膝掛',
    yomigana: 'ひざかけ',
    kyukana: '',
    season: 'winter',
    id: 2343,
    bodai: [],
  },
  {
    name: '日向ぼこ',
    yomigana: 'ひなたぼこ',
    kyukana: '',
    bodai: ['日向ぼつこ', '日向ぼこり'],
    season: 'winter',
    id: 2344,
  },
  {
    name: '火の番',
    yomigana: 'ひのばん',
    kyukana: '',
    bodai: ['夜番', '夜廻', '夜警', '寒柝'],
    season: 'winter',
    id: 2345,
  },
  {
    name: '火鉢',
    yomigana: 'ひばち',
    kyukana: '',
    bodai: ['火桶', '手焙', '手炉'],
    season: 'winter',
    id: 2346,
  },
  {
    name: '柊挿す',
    yomigana: 'ひひらぎさす',
    kyukana: '',
    bodai: ['焼嗅し'],
    season: 'winter',
    id: 2347,
  },
  {
    name: '柊の花',
    yomigana: 'ひひらぎのはな',
    kyukana: '',
    bodai: ['花柊'],
    season: 'winter',
    id: 2348,
  },
  {
    name: '胼',
    yomigana: 'ひび',
    kyukana: '',
    bodai: ['胼薬'],
    season: 'winter',
    id: 2349,
  },
  {
    name: '氷海',
    yomigana: 'ひょうかい',
    kyukana: '',
    bodai: ['海氷る', '凍港', '氷原', '氷江'],
    season: 'winter',
    id: 2350,
  },
  {
    name: '氷湖',
    yomigana: 'ひょうこ',
    kyukana: '',
    bodai: ['湖氷る', '冬の湖', '冬の沼'],
    season: 'winter',
    id: 2351,
  },
  {
    name: '鰭酒',
    yomigana: 'ひれざけ',
    kyukana: '',
    bodai: ['身酒'],
    season: 'winter',
    id: 2352,
  },
  {
    name: '枇杷の花',
    yomigana: 'びはのはな',
    kyukana: '',
    bodai: ['花枇杷'],
    season: 'winter',
    id: 2353,
  },
  {
    name: '屏風',
    yomigana: 'びょうぶ',
    kyukana: 'びやうぶ',
    bodai: ['枕屏風'],
    season: 'winter',
    id: 2354,
  },
  {
    name: '鞴祭',
    yomigana: 'ふいごまつり',
    kyukana: '',
    bodai: ['踏鞴祭', 'ほど祭', '鍛冶祭'],
    season: 'winter',
    id: 2355,
  },
  {
    name: '梟',
    yomigana: 'ふくろう',
    kyukana: 'ふくろふ',
    bodai: ['ふくろ'],
    season: 'winter',
    id: 2356,
  },
  {
    name: '河豚',
    yomigana: 'ふぐ',
    kyukana: '',
    bodai: ['ふぐと', 'ふく'],
    season: 'winter',
    id: 2357,
  },
  {
    name: '河豚汁',
    yomigana: 'ふぐじる',
    kyukana: '',
    bodai: ['ふぐと汁', 'ふぐ鍋', 'ちり鍋'],
    season: 'winter',
    id: 2358,
  },
  {
    name: '柴漬',
    yomigana: 'ふしづけ',
    kyukana: '',
    season: 'winter',
    id: 2359,
    bodai: [],
  },
  {
    name: '衾',
    yomigana: 'ふすま',
    kyukana: '',
    bodai: ['紙衾'],
    season: 'winter',
    id: 2360,
  },
  {
    name: '襖',
    yomigana: 'ふすま',
    kyukana: '',
    bodai: ['唐紙'],
    season: 'winter',
    id: 2361,
  },
  {
    name: '札納',
    yomigana: 'ふだおさめ',
    kyukana: 'ふだをさめ',
    bodai: ['納札'],
    season: 'winter',
    id: 2362,
  },
  {
    name: '懐手',
    yomigana: 'ふところで',
    kyukana: '',
    season: 'winter',
    id: 2363,
    bodai: [],
  },
  {
    name: '蒲団',
    yomigana: 'ふとん',
    kyukana: '',
    bodai: ['干蒲団'],
    season: 'winter',
    id: 2364,
  },
  {
    name: '吹雪',
    yomigana: 'ふぶき',
    kyukana: '',
    bodai: ['地吹雪', '雪煙', '雪浪'],
    season: 'winter',
    id: 2365,
  },
  {
    name: '冬',
    yomigana: 'ふゆ',
    kyukana: '',
    bodai: ['三冬', '九冬', '玄冬', '冬帝', '冬将軍'],
    season: 'winter',
    id: 2366,
  },
  {
    name: '冬暖か',
    yomigana: 'ふゆあたたか',
    kyukana: '',
    bodai: ['暖冬', '冬ぬくし'],
    season: 'winter',
    id: 2367,
  },
  {
    name: '冬安居',
    yomigana: 'ふゆあんご',
    kyukana: '',
    bodai: ['雪安居'],
    season: 'winter',
    id: 2368,
  },
  {
    name: '冬苺',
    yomigana: 'ふゆいちご',
    kyukana: '',
    bodai: ['寒苺'],
    season: 'winter',
    id: 2369,
  },
  {
    name: '冬鷗',
    yomigana: 'ふゆかもめ',
    kyukana: '',
    bodai: ['鷗', '鴎'],
    season: 'winter',
    id: 2370,
  },
  {
    name: '冬霞',
    yomigana: 'ふゆがすみ',
    kyukana: '',
    bodai: ['冬の霞', '寒霞'],
    season: 'winter',
    id: 2371,
  },
  {
    name: '冬構',
    yomigana: 'ふゆがまえ',
    kyukana: 'ふゆがまへ',
    bodai: ['冬囲'],
    season: 'winter',
    id: 2372,
  },
  {
    name: '冬枯',
    yomigana: 'ふゆがれ',
    kyukana: '',
    bodai: ['枯る'],
    season: 'winter',
    id: 2373,
  },
  {
    name: '冬木',
    yomigana: 'ふゆき',
    kyukana: '',
    bodai: ['冬木立', '冬木影', '冬木道', '冬木宿'],
    season: 'winter',
    id: 2374,
  },
  {
    name: '冬草',
    yomigana: 'ふゆくさ',
    kyukana: '',
    bodai: ['冬の草', '冬青草'],
    season: 'winter',
    id: 2375,
  },
  {
    name: '冬籠',
    yomigana: 'ふゆごもり',
    kyukana: '',
    bodai: ['雪篭', '冬篭'],
    season: 'winter',
    id: 2376,
  },
  {
    name: '冬桜',
    yomigana: 'ふゆざくら',
    kyukana: '',
    bodai: ['寒桜', '緋寒桜', '寒緋桜'],
    season: 'winter',
    id: 2377,
  },
  {
    name: '冬座敷',
    yomigana: 'ふゆざしき',
    kyukana: '',
    season: 'winter',
    id: 2378,
    bodai: [],
  },
  {
    name: '冬ざれ',
    yomigana: 'ふゆざれ',
    kyukana: '',
    bodai: ['冬ざるる'],
    season: 'winter',
    id: 2379,
  },
  {
    name: '冬菫',
    yomigana: 'ふゆすみれ',
    kyukana: '',
    bodai: ['寒菫'],
    season: 'winter',
    id: 2380,
  },
  {
    name: '冬薔薇',
    yomigana: 'ふゆそうび',
    kyukana: 'ふゆさうび',
    bodai: ['冬薔薇', '寒薔薇'],
    season: 'winter',
    id: 2381,
  },
  {
    name: '冬田',
    yomigana: 'ふゆた',
    kyukana: '',
    bodai: ['冬の田', '冬田道'],
    season: 'winter',
    id: 2382,
  },
  {
    name: '冬尽く',
    yomigana: 'ふゆつく',
    kyukana: '',
    bodai: ['冬終る', '冬の名残', '冬去る'],
    season: 'winter',
    id: 2383,
  },
  {
    name: '冬菜',
    yomigana: 'ふゆな',
    kyukana: '',
    bodai: ['冬菜畑', '冬菜売'],
    season: 'winter',
    id: 2384,
  },
  {
    name: '冬凪',
    yomigana: 'ふゆなぎ',
    kyukana: '',
    bodai: ['寒凪'],
    season: 'winter',
    id: 2385,
  },
  {
    name: '冬虹',
    yomigana: 'ふゆにじ',
    kyukana: '',
    season: 'winter',
    id: 2386,
    bodai: [],
  },
  {
    name: '冬野',
    yomigana: 'ふゆの',
    kyukana: '',
    bodai: ['冬の野', '冬の原', '雪野', '雪原'],
    season: 'winter',
    id: 2387,
  },
  {
    name: '冬の朝',
    yomigana: 'ふゆのあさ',
    kyukana: '',
    bodai: ['冬曙', '寒暁'],
    season: 'winter',
    id: 2388,
  },
  {
    name: '冬の虻',
    yomigana: 'ふゆのあぶ',
    kyukana: '',
    season: 'winter',
    id: 2389,
    bodai: [],
  },
  {
    name: '冬の雨',
    yomigana: 'ふゆのあめ',
    kyukana: '',
    bodai: ['寒の雨'],
    season: 'winter',
    id: 2390,
  },
  {
    name: '冬の鴬',
    yomigana: 'ふゆのうぐいす',
    kyukana: 'ふゆのうぐひす',
    bodai: ['寒鴬', '鴬の子', '笹子', '薮鴬'],
    season: 'winter',
    id: 2391,
  },
  {
    name: '冬の海',
    yomigana: 'ふゆのうみ',
    kyukana: '',
    bodai: ['冬海', '冬の浜'],
    season: 'winter',
    id: 2392,
  },
  {
    name: '冬の梅',
    yomigana: 'ふゆのうめ',
    kyukana: '',
    bodai: ['冬梅', '寒梅', '寒紅梅', '冬至梅'],
    season: 'winter',
    id: 2393,
  },
  {
    name: '冬の雁',
    yomigana: 'ふゆのかり',
    kyukana: '',
    bodai: ['寒雁'],
    season: 'winter',
    id: 2394,
  },
  {
    name: '冬の川',
    yomigana: 'ふゆのかわ',
    kyukana: 'ふゆのかは',
    bodai: ['冬川', '冬川原'],
    season: 'winter',
    id: 2395,
  },
  {
    name: '冬の霧',
    yomigana: 'ふゆのきり',
    kyukana: '',
    bodai: ['冬霧'],
    season: 'winter',
    id: 2396,
  },
  {
    name: '冬の雲',
    yomigana: 'ふゆのくも',
    kyukana: '',
    bodai: ['冬雲', '凍雲', '寒雲'],
    season: 'winter',
    id: 2397,
  },
  {
    name: '冬の暮',
    yomigana: 'ふゆのくれ',
    kyukana: '',
    bodai: ['冬の夕', '寒暮'],
    season: 'winter',
    id: 2398,
  },
  {
    name: '冬の空',
    yomigana: 'ふゆのそら',
    kyukana: '',
    bodai: ['冬天', '寒天', '寒空', '冬空'],
    season: 'winter',
    id: 2399,
  },
  {
    name: '冬の蝶',
    yomigana: 'ふゆのちょう',
    kyukana: 'ふゆのてふ',
    bodai: ['冬蝶', '凍蝶'],
    season: 'winter',
    id: 2400,
  },
  {
    name: '冬の月',
    yomigana: 'ふゆのつき',
    kyukana: '',
    bodai: ['寒月', '冬三日月', '月冴ゆ', '月氷る'],
    season: 'winter',
    id: 2401,
  },
  {
    name: '冬の鳥',
    yomigana: 'ふゆのとり',
    kyukana: '',
    bodai: ['寒禽'],
    season: 'winter',
    id: 2402,
  },
  {
    name: '冬の波',
    yomigana: 'ふゆのなみ',
    kyukana: '',
    bodai: ['冬浪', '冬涛', '寒涛', '冬怒濤'],
    season: 'winter',
    id: 2403,
  },
  {
    name: '冬の虹',
    yomigana: 'ふゆのにじ',
    kyukana: '',
    season: 'winter',
    id: 2404,
    bodai: [],
  },
  {
    name: '冬の蠅',
    yomigana: 'ふゆのはえ',
    kyukana: 'ふゆのはへ',
    bodai: ['冬蝿'],
    season: 'winter',
    id: 2405,
  },
  {
    name: '冬の蜂',
    yomigana: 'ふゆのはち',
    kyukana: '',
    bodai: ['冬蜂', '凍蜂'],
    season: 'winter',
    id: 2406,
  },
  {
    name: '冬の日',
    yomigana: 'ふゆのひ',
    kyukana: '',
    bodai: ['冬日', '冬日向', '冬日影'],
    season: 'winter',
    id: 2407,
  },
  {
    name: '冬の燈',
    yomigana: 'ふゆのひ',
    kyukana: '',
    bodai: ['冬の灯', '冬燈', '冬灯', '冬ともし', '寒燈', '寒灯'],
    season: 'winter',
    id: 2408,
  },
  {
    name: '冬の星',
    yomigana: 'ふゆのほし',
    kyukana: '',
    bodai: [
      '寒星',
      '荒星',
      '凍星',
      '冬銀河',
      '星冴ゆ',
      'オリオン',
      '寒昴',
      'シリウス',
      '天狼',
    ],
    season: 'winter',
    id: 2409,
  },
  {
    name: '冬の水',
    yomigana: 'ふゆのみず',
    kyukana: 'ふゆのみづ',
    bodai: ['冬の泉', '寒泉'],
    season: 'winter',
    id: 2410,
  },
  {
    name: '冬の虫',
    yomigana: 'ふゆのむし',
    kyukana: '',
    season: 'winter',
    id: 2411,
    bodai: [],
  },
  {
    name: '冬の鵙',
    yomigana: 'ふゆのもず',
    kyukana: '',
    season: 'winter',
    id: 2412,
    bodai: [],
  },
  {
    name: '冬の靄',
    yomigana: 'ふゆのもや',
    kyukana: '',
    bodai: ['冬靄', '寒靄'],
    season: 'winter',
    id: 2413,
  },
  {
    name: '冬の山',
    yomigana: 'ふゆのやま',
    kyukana: '',
    bodai: ['冬山', '枯山', '雪山', '冬嶺', '雪嶺', '冬山路', '冬山家'],
    season: 'winter',
    id: 2414,
  },
  {
    name: '冬の夕焼',
    yomigana: 'ふゆのゆうやけ',
    kyukana: 'ふゆのゆふやけ',
    bodai: ['寒夕焼', '冬茜', '寒茜', '寒落暉'],
    season: 'winter',
    id: 2415,
  },
  {
    name: '冬の夜',
    yomigana: 'ふゆのよ',
    kyukana: '',
    bodai: ['夜半の冬', '寒夜'],
    season: 'winter',
    id: 2416,
  },
  {
    name: '冬の雷',
    yomigana: 'ふゆのらい',
    kyukana: '',
    bodai: ['寒雷'],
    season: 'winter',
    id: 2417,
  },
  {
    name: '冬花火',
    yomigana: 'ふゆはなび',
    kyukana: '',
    season: 'winter',
    id: 2418,
    bodai: [],
  },
  {
    name: '冬晴',
    yomigana: 'ふゆばれ',
    kyukana: '',
    bodai: ['冬日和', '冬麗', '冬うらら'],
    season: 'winter',
    id: 2419,
  },
  {
    name: '冬旱',
    yomigana: 'ふゆひでり',
    kyukana: '',
    bodai: ['寒旱'],
    season: 'winter',
    id: 2420,
  },
  {
    name: '冬雲雀',
    yomigana: 'ふゆひばり',
    kyukana: '',
    season: 'winter',
    id: 2421,
    bodai: [],
  },
  {
    name: '冬深し',
    yomigana: 'ふゆふかし',
    kyukana: '',
    bodai: ['冬深む', '暮の冬', '真冬'],
    season: 'winter',
    id: 2422,
  },
  {
    name: '冬服',
    yomigana: 'ふゆふく',
    kyukana: '',
    bodai: ['冬着', '冬シャツ', '皮羽織'],
    season: 'winter',
    id: 2423,
  },
  {
    name: '冬帽子',
    yomigana: 'ふゆぼうし',
    kyukana: '',
    bodai: ['冬帽'],
    season: 'winter',
    id: 2424,
  },
  {
    name: '冬めく',
    yomigana: 'ふゆめく',
    kyukana: '',
    season: 'winter',
    id: 2425,
    bodai: [],
  },
  {
    name: '冬萌',
    yomigana: 'ふゆもえ',
    kyukana: '',
    bodai: ['冬木の芽', '冬芽'],
    season: 'winter',
    id: 2426,
  },
  {
    name: '冬紅葉',
    yomigana: 'ふゆもみじ',
    kyukana: 'ふゆもみぢ',
    season: 'winter',
    id: 2427,
    bodai: [],
  },
  {
    name: '冬館',
    yomigana: 'ふゆやかた',
    kyukana: '',
    bodai: ['冬の家', '冬の宿'],
    season: 'winter',
    id: 2428,
  },
  {
    name: '冬休み',
    yomigana: 'ふゆやすみ',
    kyukana: '',
    season: 'winter',
    id: 2429,
    bodai: [],
  },
  {
    name: '古暦',
    yomigana: 'ふるごよみ',
    kyukana: '',
    bodai: ['暦の果', '暦の終り'],
    season: 'winter',
    id: 2430,
  },
  {
    name: '風呂吹',
    yomigana: 'ふろふき',
    kyukana: '',
    bodai: ['風呂吹大根'],
    season: 'winter',
    id: 2431,
  },
  {
    name: '蕪村忌',
    yomigana: 'ぶそんき',
    kyukana: '',
    bodai: ['春星忌', '夜半亭忌'],
    season: 'winter',
    id: 2432,
  },
  {
    name: '仏手柑',
    yomigana: 'ぶっしゅかん',
    kyukana: '',
    bodai: ['ぶしゅ柑'],
    season: 'winter',
    id: 2433,
  },
  {
    name: '鰤',
    yomigana: 'ぶり',
    kyukana: '',
    bodai: ['寒鰤'],
    season: 'winter',
    id: 2434,
  },
  {
    name: '鰤網',
    yomigana: 'ぶりあみ',
    kyukana: '',
    bodai: ['鰤場'],
    season: 'winter',
    id: 2435,
  },
  {
    name: '鰤起し',
    yomigana: 'ぶりおこし',
    kyukana: '',
    season: 'winter',
    id: 2436,
    bodai: [],
  },
  {
    name: '碧梧桐忌',
    yomigana: 'へきごとうき',
    kyukana: '',
    bodai: ['寒明忌'],
    season: 'winter',
    id: 2437,
  },
  {
    name: '報恩講',
    yomigana: 'ほうおんこう',
    kyukana: '',
    bodai: ['御正忌', '御七夜', '御講', '御霜月', '親鸞忌'],
    season: 'winter',
    id: 2438,
  },
  {
    name: '魴鮄',
    yomigana: 'ほうぼう',
    kyukana: 'はうぼう',
    season: 'winter',
    id: 2439,
    bodai: [],
  },
  {
    name: '捕鯨',
    yomigana: 'ほげい',
    kyukana: '',
    bodai: ['捕鯨船'],
    season: 'winter',
    id: 2440,
  },
  {
    name: '干菜汁',
    yomigana: 'ほしなじる',
    kyukana: '',
    season: 'winter',
    id: 2441,
    bodai: [],
  },
  {
    name: '干菜吊る',
    yomigana: 'ほしなつる',
    kyukana: '',
    bodai: ['干菜', '懸菜', '吊菜', '干葉'],
    season: 'winter',
    id: 2442,
  },
  {
    name: '榾',
    yomigana: 'ほだ',
    kyukana: '',
    bodai: ['ほた', '榾火', '榾明り'],
    season: 'winter',
    id: 2443,
  },
  {
    name: '朴落葉',
    yomigana: 'ほほおちば',
    kyukana: '',
    bodai: ['朴散る'],
    season: 'winter',
    id: 2444,
  },
  {
    name: '頬被',
    yomigana: 'ほほかむり',
    kyukana: '',
    bodai: ['ほほかぶり'],
    season: 'winter',
    id: 2445,
  },
  {
    name: '防雪林',
    yomigana: 'ぼうせつりん',
    kyukana: '',
    season: 'winter',
    id: 2446,
    bodai: [],
  },
  {
    name: 'ボジョレー・ヌーヴォー',
    yomigana: 'ぼじょれーぬーぼー',
    kyukana: '',
    season: 'winter',
    id: 2447,
    bodai: [],
  },
  {
    name: '牡丹焚火',
    yomigana: 'ぼたんたきび',
    kyukana: '',
    bodai: ['牡丹焚く', '牡丹供養'],
    season: 'winter',
    id: 2448,
  },
  {
    name: '牡丹鍋',
    yomigana: 'ぼたんなべ',
    kyukana: '',
    bodai: ['猪鍋', '山鯨', '猪肉'],
    season: 'winter',
    id: 2449,
  },
  {
    name: 'ボロ市',
    yomigana: 'ぼろいち',
    kyukana: '',
    bodai: ['世田谷襤褸市'],
    season: 'winter',
    id: 2450,
  },
  {
    name: 'ポインセチア',
    yomigana: 'ぽいんせちあ',
    kyukana: '',
    bodai: ['猩々木', 'クリスマスフラワー'],
    season: 'winter',
    id: 2451,
  },
  {
    name: '鮪',
    yomigana: 'まぐろ',
    kyukana: '',
    bodai: ['鮪船', '鮪釣'],
    season: 'winter',
    id: 2452,
  },
  {
    name: 'マスク',
    yomigana: 'ますく',
    kyukana: '',
    season: 'winter',
    id: 2453,
    bodai: [],
  },
  {
    name: '松葉蟹',
    yomigana: 'まつばがに',
    kyukana: '',
    bodai: ['ずわい蟹', '越前蟹'],
    season: 'winter',
    id: 2454,
  },
  {
    name: '豆撒',
    yomigana: 'まめまき',
    kyukana: '',
    bodai: ['豆打', '年の豆', '鬼打豆', '鬼は外', '福は内', '年男'],
    season: 'winter',
    id: 2455,
  },
  {
    name: 'マント',
    yomigana: 'まんと',
    kyukana: '',
    bodai: ['二重廻し', 'トンビ', 'インバネス'],
    season: 'winter',
    id: 2456,
  },
  {
    name: '万両',
    yomigana: 'まんりょう',
    kyukana: 'まんりやう',
    bodai: ['実万両'],
    season: 'winter',
    id: 2457,
  },
  {
    name: '蜜柑',
    yomigana: 'みかん',
    kyukana: '',
    bodai: ['蜜柑山', '蜜柑狩'],
    season: 'winter',
    id: 2458,
  },
  {
    name: '三島忌',
    yomigana: 'みしまき',
    kyukana: '',
    bodai: ['憂国忌'],
    season: 'winter',
    id: 2459,
  },
  {
    name: '水涸る',
    yomigana: 'みずかる',
    kyukana: 'みづかる',
    bodai: ['川涸る', '沼涸る', '滝涸る'],
    season: 'winter',
    id: 2460,
  },
  {
    name: '水鳥',
    yomigana: 'みずどり',
    kyukana: 'みづどり',
    bodai: ['浮寝鳥'],
    season: 'winter',
    id: 2461,
  },
  {
    name: '水洟',
    yomigana: 'みずばな',
    kyukana: 'みづばな',
    bodai: ['鼻水'],
    season: 'winter',
    id: 2462,
  },
  {
    name: '瑞穂',
    yomigana: 'みずほ',
    kyukana: '',
    bodai: ['穂田'],
    season: 'winter',
    id: 2463,
  },
  {
    name: '水餅',
    yomigana: 'みずもち',
    kyukana: 'みづもち',
    season: 'winter',
    id: 2464,
    bodai: [],
  },
  {
    name: '晦日蕎麦',
    yomigana: 'みそかそば',
    kyukana: '',
    bodai: ['年越蕎麦', 'つごもり蕎麦'],
    season: 'winter',
    id: 2465,
  },
  {
    name: '鷦鷯',
    yomigana: 'みそさざい',
    kyukana: '',
    bodai: ['三十三才'],
    season: 'winter',
    id: 2466,
  },
  {
    name: '味噌搗',
    yomigana: 'みそつき',
    kyukana: '',
    bodai: ['味噌作る'],
    season: 'winter',
    id: 2467,
  },
  {
    name: '霙',
    yomigana: 'みぞれ',
    kyukana: '',
    bodai: ['霙るる'],
    season: 'winter',
    id: 2468,
  },
  {
    name: '木菟',
    yomigana: 'みみづく',
    kyukana: '',
    bodai: ['づく'],
    season: 'winter',
    id: 2469,
  },
  {
    name: '耳袋',
    yomigana: 'みみぶくろ',
    kyukana: '',
    bodai: ['耳掛'],
    season: 'winter',
    id: 2470,
  },
  {
    name: '都鳥',
    yomigana: 'みやこどり',
    kyukana: '',
    bodai: ['ゆりかもめ'],
    season: 'winter',
    id: 2471,
  },
  {
    name: '麦の芽',
    yomigana: 'むぎのめ',
    kyukana: '',
    bodai: ['芽麦'],
    season: 'winter',
    id: 2472,
  },
  {
    name: '麦蒔',
    yomigana: 'むぎまき',
    kyukana: '',
    season: 'winter',
    id: 2473,
    bodai: [],
  },
  {
    name: 'むささび',
    yomigana: 'むささび',
    kyukana: '',
    bodai: ['むささび'],
    season: 'winter',
    id: 2474,
  },
  {
    name: '霧氷',
    yomigana: 'むひょう',
    kyukana: '',
    bodai: ['樹霜', '粗氷', '霧氷林'],
    season: 'winter',
    id: 2475,
  },
  {
    name: '室咲',
    yomigana: 'むろざき',
    kyukana: '',
    bodai: ['室の花'],
    season: 'winter',
    id: 2476,
  },
  {
    name: '和布刈神事',
    yomigana: 'めかりのしんじ',
    kyukana: '',
    bodai: ['和布刈禰宜', '和布刈桶'],
    season: 'winter',
    id: 2477,
  },
  {
    name: '目貼',
    yomigana: 'めばり',
    kyukana: '',
    bodai: ['隙間貼る'],
    season: 'winter',
    id: 2478,
  },
  {
    name: '毛布',
    yomigana: 'もうふ',
    kyukana: '',
    bodai: ['ケット'],
    season: 'winter',
    id: 2479,
  },
  {
    name: '虎落笛',
    yomigana: 'もがりぶえ',
    kyukana: '',
    season: 'winter',
    id: 2480,
    bodai: [],
  },
  {
    name: '餅',
    yomigana: 'もち',
    kyukana: '',
    season: 'winter',
    id: 2481,
    bodai: [],
  },
  {
    name: '餅搗',
    yomigana: 'もちつき',
    kyukana: '',
    bodai: ['餅米洗ふ', '餅搗唄', '賃餅', '餅筵', '餅配'],
    season: 'winter',
    id: 2482,
  },
  {
    name: '紅葉散る',
    yomigana: 'もみじちる',
    kyukana: 'もみぢちる',
    bodai: ['散紅葉'],
    season: 'winter',
    id: 2483,
  },
  {
    name: '股引',
    yomigana: 'ももひき',
    kyukana: '',
    season: 'winter',
    id: 2484,
    bodai: [],
  },
  {
    name: '焼藷',
    yomigana: 'やきいも',
    kyukana: '',
    bodai: ['焼芋', '石焼芋'],
    season: 'winter',
    id: 2485,
  },
  {
    name: '厄払',
    yomigana: 'やくはらい',
    kyukana: '',
    bodai: ['厄落', '厄の薪', 'ふぐり落し'],
    season: 'winter',
    id: 2486,
  },
  {
    name: 'ヤッケ',
    yomigana: 'やっけ',
    kyukana: '',
    bodai: ['アノラック'],
    season: 'winter',
    id: 2487,
  },
  {
    name: '八手の花',
    yomigana: 'やつでのはな',
    kyukana: '',
    bodai: ['花八手'],
    season: 'winter',
    id: 2488,
  },
  {
    name: '藪柑子',
    yomigana: 'やぶこうじ',
    kyukana: 'やぶかうじ',
    bodai: ['薮柑子'],
    season: 'winter',
    id: 2489,
  },
  {
    name: '藪巻',
    yomigana: 'やぶまき',
    kyukana: '',
    bodai: ['竹巻', '菰巻'],
    season: 'winter',
    id: 2490,
  },
  {
    name: '山眠る',
    yomigana: 'やまねむる',
    kyukana: '',
    bodai: ['眠る山'],
    season: 'winter',
    id: 2491,
  },
  {
    name: '闇汁',
    yomigana: 'やみじる',
    kyukana: '',
    season: 'winter',
    id: 2492,
    bodai: [],
  },
  {
    name: '雪',
    yomigana: 'ゆき',
    kyukana: '',
    bodai: [
      '六花',
      '雪の華',
      '小雪',
      '大雪',
      '深雪',
      '粉雪',
      '綿雪',
      '細雪',
      '小米雪',
      '根雪',
      '飛雪',
      '雪明り',
      '雪の声',
      '朝の雪',
      '夜の雪',
      '暮雪',
      '雪の宿',
      '雪国',
      '雪空',
    ],
    season: 'winter',
    id: 2493,
  },
  {
    name: '雪遊び',
    yomigana: 'ゆきあそび',
    kyukana: '',
    bodai: ['雪投げ', '雪礫', '雪丸げ', '雪合戦'],
    season: 'winter',
    id: 2494,
  },
  {
    name: '雪起し',
    yomigana: 'ゆきおこし',
    kyukana: '',
    bodai: ['雪雷', '雪の雷'],
    season: 'winter',
    id: 2495,
  },
  {
    name: '雪折',
    yomigana: 'ゆきおれ',
    kyukana: 'ゆきをれ',
    season: 'winter',
    id: 2496,
    bodai: [],
  },
  {
    name: '雪下し',
    yomigana: 'ゆきおろし',
    kyukana: '',
    bodai: ['雪卸'],
    season: 'winter',
    id: 2497,
  },
  {
    name: '雪掻',
    yomigana: 'ゆきかき',
    kyukana: '',
    bodai: ['除雪', '除雪車', 'ラッセル車'],
    season: 'winter',
    id: 2498,
  },
  {
    name: '雪囲',
    yomigana: 'ゆきがこい',
    kyukana: 'ゆきがこひ',
    bodai: ['雪垣', '雪構', '雪除', '墓囲'],
    season: 'winter',
    id: 2499,
  },
  {
    name: '雪合羽',
    yomigana: 'ゆきがっぱ',
    kyukana: '',
    bodai: ['雪蓑'],
    season: 'winter',
    id: 2500,
  },
  {
    name: '雪沓',
    yomigana: 'ゆきぐつ',
    kyukana: '',
    bodai: ['藁沓', '爪篭'],
    season: 'winter',
    id: 2501,
  },
  {
    name: '雪しまき',
    yomigana: 'ゆきしまき',
    kyukana: '',
    bodai: ['しまき'],
    season: 'winter',
    id: 2502,
  },
  {
    name: '雪女郎',
    yomigana: 'ゆきじょろう',
    kyukana: 'ゆきぢよらう',
    bodai: ['雪女', '雪坊主'],
    season: 'winter',
    id: 2503,
  },
  {
    name: '雪達磨',
    yomigana: 'ゆきだるま',
    kyukana: '',
    bodai: ['雪兎', '雪釣'],
    season: 'winter',
    id: 2504,
  },
  {
    name: '雪吊',
    yomigana: 'ゆきつり',
    kyukana: '',
    season: 'winter',
    id: 2505,
    bodai: [],
  },
  {
    name: '雪晴',
    yomigana: 'ゆきばれ',
    kyukana: '',
    bodai: ['深雪晴'],
    season: 'winter',
    id: 2506,
  },
  {
    name: '雪踏',
    yomigana: 'ゆきふみ',
    kyukana: '',
    bodai: ['踏俵'],
    season: 'winter',
    id: 2507,
  },
  {
    name: '雪見',
    yomigana: 'ゆきみ',
    kyukana: '',
    bodai: ['雪見舟', '雪見酒'],
    season: 'winter',
    id: 2508,
  },
  {
    name: '雪眼',
    yomigana: 'ゆきめ',
    kyukana: '',
    season: 'winter',
    id: 2509,
    bodai: [],
  },
  {
    name: '雪眼鏡',
    yomigana: 'ゆきめがね',
    kyukana: '',
    bodai: ['ゴーグル'],
    season: 'winter',
    id: 2510,
  },
  {
    name: '雪催',
    yomigana: 'ゆきもよい',
    kyukana: 'ゆきもよひ',
    bodai: ['雪雲', '雪げ', '雪曇'],
    season: 'winter',
    id: 2511,
  },
  {
    name: '雪焼',
    yomigana: 'ゆきやけ',
    kyukana: '',
    bodai: ['雪眼'],
    season: 'winter',
    id: 2512,
  },
  {
    name: '行く年',
    yomigana: 'ゆくとし',
    kyukana: '',
    bodai: ['年逝く', '年流る', '年送る'],
    season: 'winter',
    id: 2513,
  },
  {
    name: '湯気立て',
    yomigana: 'ゆげたて',
    kyukana: '',
    season: 'winter',
    id: 2514,
    bodai: [],
  },
  {
    name: '湯ざめ',
    yomigana: 'ゆざめ',
    kyukana: '',
    season: 'winter',
    id: 2515,
    bodai: [],
  },
  {
    name: '柚子湯',
    yomigana: 'ゆずゆ',
    kyukana: '',
    bodai: ['柚子風呂', '冬至湯'],
    season: 'winter',
    id: 2516,
  },
  {
    name: '湯婆',
    yomigana: 'ゆたんぽ',
    kyukana: '',
    bodai: ['たんぽ'],
    season: 'winter',
    id: 2517,
  },
  {
    name: '湯豆腐',
    yomigana: 'ゆどうふ',
    kyukana: '',
    season: 'winter',
    id: 2518,
    bodai: [],
  },
  {
    name: '夜着',
    yomigana: 'よぎ',
    kyukana: '',
    bodai: ['掻巻', '小夜着'],
    season: 'winter',
    id: 2519,
  },
  {
    name: '寄鍋',
    yomigana: 'よせなべ',
    kyukana: '',
    season: 'winter',
    id: 2520,
    bodai: [],
  },
  {
    name: '夜鷹蕎麦',
    yomigana: 'よたかそば',
    kyukana: '',
    bodai: ['夜鳴蕎麦', '夜鳴うどん', '夜鳴ラーメン'],
    season: 'winter',
    id: 2521,
  },
  {
    name: 'ラグビー',
    yomigana: 'らぐびー',
    kyukana: '',
    bodai: ['ラガー'],
    season: 'winter',
    id: 2522,
  },
  {
    name: '嵐雪忌',
    yomigana: 'らんせつき',
    kyukana: '',
    season: 'winter',
    id: 2523,
    bodai: [],
  },
  {
    name: '立冬',
    yomigana: 'りっとう',
    kyukana: '',
    bodai: ['冬立つ', '冬に入る', '冬来る', '今朝の冬'],
    season: 'winter',
    id: 2524,
  },
  {
    name: '竜の玉',
    yomigana: 'りゅうのたま',
    kyukana: '',
    bodai: ['竜の髯の実', '蛇の髯の実', '龍の玉'],
    season: 'winter',
    id: 2525,
  },
  {
    name: 'ルミナリエ',
    yomigana: 'るみなりえ',
    kyukana: '',
    season: 'winter',
    id: 2526,
    bodai: [],
  },
  {
    name: '冷海',
    yomigana: 'れいかい',
    kyukana: '',
    season: 'winter',
    id: 2527,
    bodai: [],
  },
  {
    name: 'レノン忌',
    yomigana: 'れのんき',
    kyukana: '',
    bodai: ['レノンの忌'],
    season: 'winter',
    id: 2528,
  },
  {
    name: '煉炭',
    yomigana: 'れんたん',
    kyukana: '',
    season: 'winter',
    id: 2529,
    bodai: [],
  },
  {
    name: '臘八会',
    yomigana: 'ろうはつえ',
    kyukana: 'らふはつゑ',
    bodai: ['臘八', '成道会', '臘八接心', '臘八摂心'],
    season: 'winter',
    id: 2530,
  },
  {
    name: '臘梅',
    yomigana: 'ろうばい',
    kyukana: 'らふばい',
    bodai: ['唐梅'],
    season: 'winter',
    id: 2531,
  },
  {
    name: '炉開',
    yomigana: 'ろびらき',
    kyukana: '',
    season: 'winter',
    id: 2532,
    bodai: [],
  },
  {
    name: '鷲',
    yomigana: 'わし',
    kyukana: '',
    season: 'winter',
    id: 2533,
    bodai: [],
  },
  {
    name: '綿入',
    yomigana: 'わたいれ',
    kyukana: '',
    bodai: ['布子', '綿子'],
    season: 'winter',
    id: 2534,
  },
  {
    name: '綿虫',
    yomigana: 'わたむし',
    kyukana: '',
    bodai: ['大綿', '雪蛍', '雪婆', '白粉婆'],
    season: 'winter',
    id: 2535,
  },
  {
    name: '侘助',
    yomigana: 'わびすけ',
    kyukana: '',
    bodai: ['侘助', '唐椿'],
    season: 'winter',
    id: 2536,
  },
  {
    name: '藁仕事',
    yomigana: 'わらしごと',
    kyukana: '',
    bodai: ['縄綯ふ', '筵織る'],
    season: 'winter',
    id: 2537,
  },
]

export default winter
